/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigInfoEncodedWatcher
 */
@JsonPropertyOrder({
  ConfigInfoEncodedWatcher.JSON_PROPERTY_IGNORE
})
@JsonTypeName("Config_InfoEncoded_watcher")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ConfigInfoEncodedWatcher {
  public static final String JSON_PROPERTY_IGNORE = "ignore";
  @jakarta.annotation.Nullable
  private List<String> ignore = new ArrayList<>();

  public ConfigInfoEncodedWatcher() {
  }

  public ConfigInfoEncodedWatcher ignore(@jakarta.annotation.Nullable List<String> ignore) {

    this.ignore = ignore;
    return this;
  }

  public ConfigInfoEncodedWatcher addIgnoreItem(String ignoreItem) {
    if (this.ignore == null) {
      this.ignore = new ArrayList<>();
    }
    this.ignore.add(ignoreItem);
    return this;
  }

  /**
   * Get ignore
   * @return ignore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IGNORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getIgnore() {
    return ignore;
  }


  @JsonProperty(value = JSON_PROPERTY_IGNORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIgnore(@jakarta.annotation.Nullable List<String> ignore) {
    this.ignore = ignore;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigInfoEncodedWatcher configInfoEncodedWatcher = (ConfigInfoEncodedWatcher) o;
    return Objects.equals(this.ignore, configInfoEncodedWatcher.ignore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ignore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigInfoEncodedWatcher {\n");
    sb.append("    ignore: ").append(toIndentedString(ignore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
