/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ConfigModelSettings;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigModelEncodedVariantsInner
 */
@JsonPropertyOrder({
  ConfigModelEncodedVariantsInner.JSON_PROPERTY_ID,
  ConfigModelEncodedVariantsInner.JSON_PROPERTY_SETTINGS,
  ConfigModelEncodedVariantsInner.JSON_PROPERTY_HEADERS,
  ConfigModelEncodedVariantsInner.JSON_PROPERTY_BODY
})
@JsonTypeName("Config_ModelEncoded_variants_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ConfigModelEncodedVariantsInner {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_SETTINGS = "settings";
  @jakarta.annotation.Nullable
  private ConfigModelSettings settings;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @jakarta.annotation.Nullable
  private Map<String, String> headers = new HashMap<>();

  public static final String JSON_PROPERTY_BODY = "body";
  @jakarta.annotation.Nullable
  private Object body;

  public ConfigModelEncodedVariantsInner() {
  }

  public ConfigModelEncodedVariantsInner id(@jakarta.annotation.Nullable String id) {

    this.id = id;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public ConfigModelEncodedVariantsInner settings(@jakarta.annotation.Nullable ConfigModelSettings settings) {

    this.settings = settings;
    return this;
  }

  /**
   * Get settings
   * @return settings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigModelSettings getSettings() {
    return settings;
  }


  @JsonProperty(value = JSON_PROPERTY_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSettings(@jakarta.annotation.Nullable ConfigModelSettings settings) {
    this.settings = settings;
  }

  public ConfigModelEncodedVariantsInner headers(@jakarta.annotation.Nullable Map<String, String> headers) {

    this.headers = headers;
    return this;
  }

  public ConfigModelEncodedVariantsInner putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeaders(@jakarta.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
  }

  public ConfigModelEncodedVariantsInner body(@jakarta.annotation.Nullable Object body) {

    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(@jakarta.annotation.Nullable Object body) {
    this.body = body;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigModelEncodedVariantsInner configModelEncodedVariantsInner = (ConfigModelEncodedVariantsInner) o;
    return Objects.equals(this.id, configModelEncodedVariantsInner.id) &&
        Objects.equals(this.settings, configModelEncodedVariantsInner.settings) &&
        Objects.equals(this.headers, configModelEncodedVariantsInner.headers) &&
        Objects.equals(this.body, configModelEncodedVariantsInner.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, settings, headers, body);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigModelEncodedVariantsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
