/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigToolOutput
 */
@JsonPropertyOrder({
  ConfigToolOutput.JSON_PROPERTY_MAX_LINES,
  ConfigToolOutput.JSON_PROPERTY_MAX_BYTES
})
@JsonTypeName("Config_tool_output")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ConfigToolOutput {
  public static final String JSON_PROPERTY_MAX_LINES = "max_lines";
  @jakarta.annotation.Nullable
  private Integer maxLines;

  public static final String JSON_PROPERTY_MAX_BYTES = "max_bytes";
  @jakarta.annotation.Nullable
  private Integer maxBytes;

  public ConfigToolOutput() {
  }

  public ConfigToolOutput maxLines(@jakarta.annotation.Nullable Integer maxLines) {
    
    this.maxLines = maxLines;
    return this;
  }

  /**
   * Get maxLines
   * minimum: 0
   * @return maxLines
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_LINES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxLines() {
    return maxLines;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_LINES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxLines(@jakarta.annotation.Nullable Integer maxLines) {
    this.maxLines = maxLines;
  }

  public ConfigToolOutput maxBytes(@jakarta.annotation.Nullable Integer maxBytes) {
    
    this.maxBytes = maxBytes;
    return this;
  }

  /**
   * Get maxBytes
   * minimum: 0
   * @return maxBytes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_BYTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxBytes() {
    return maxBytes;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_BYTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxBytes(@jakarta.annotation.Nullable Integer maxBytes) {
    this.maxBytes = maxBytes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigToolOutput configToolOutput = (ConfigToolOutput) o;
    return Objects.equals(this.maxLines, configToolOutput.maxLines) &&
        Objects.equals(this.maxBytes, configToolOutput.maxBytes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxLines, maxBytes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigToolOutput {\n");
    sb.append("    maxLines: ").append(toIndentedString(maxLines)).append("\n");
    sb.append("    maxBytes: ").append(toIndentedString(maxBytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

