/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ConfigInfoEncoded;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigDocumentEncoded
 */
@JsonPropertyOrder({
  ConfigDocumentEncoded.JSON_PROPERTY_TYPE,
  ConfigDocumentEncoded.JSON_PROPERTY_PATH,
  ConfigDocumentEncoded.JSON_PROPERTY_INFO
})
@JsonTypeName("Config.DocumentEncoded")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ConfigDocumentEncoded {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    DOCUMENT(String.valueOf("document"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_PATH = "path";
  @jakarta.annotation.Nullable
  private String path;

  public static final String JSON_PROPERTY_INFO = "info";
  @jakarta.annotation.Nonnull
  private ConfigInfoEncoded info;

  public ConfigDocumentEncoded() {
  }

  public ConfigDocumentEncoded type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public ConfigDocumentEncoded path(@jakarta.annotation.Nullable String path) {

    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPath(@jakarta.annotation.Nullable String path) {
    this.path = path;
  }

  public ConfigDocumentEncoded info(@jakarta.annotation.Nonnull ConfigInfoEncoded info) {

    this.info = info;
    return this;
  }

  /**
   * Get info
   * @return info
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ConfigInfoEncoded getInfo() {
    return info;
  }


  @JsonProperty(value = JSON_PROPERTY_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInfo(@jakarta.annotation.Nonnull ConfigInfoEncoded info) {
    this.info = info;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigDocumentEncoded configDocumentEncoded = (ConfigDocumentEncoded) o;
    return Objects.equals(this.type, configDocumentEncoded.type) &&
        Objects.equals(this.path, configDocumentEncoded.path) &&
        Objects.equals(this.info, configDocumentEncoded.info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, path, info);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigDocumentEncoded {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
