/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigLspAnyOfValueAnyOf
 */
@JsonPropertyOrder({
  ConfigLspAnyOfValueAnyOf.JSON_PROPERTY_DISABLED
})
@JsonTypeName("Config_lsp_anyOf_value_anyOf")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ConfigLspAnyOfValueAnyOf {
  /**
   * Gets or Sets disabled
   */
  public enum DisabledEnum {
    TRUE(Boolean.valueOf("true"));

    private Boolean value;

    DisabledEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DisabledEnum fromValue(Boolean value) {
      for (DisabledEnum b : DisabledEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DISABLED = "disabled";
  @jakarta.annotation.Nonnull
  private DisabledEnum disabled;

  public ConfigLspAnyOfValueAnyOf() {
  }

  public ConfigLspAnyOfValueAnyOf disabled(@jakarta.annotation.Nonnull DisabledEnum disabled) {
    
    this.disabled = disabled;
    return this;
  }

  /**
   * Get disabled
   * @return disabled
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DisabledEnum getDisabled() {
    return disabled;
  }


  @JsonProperty(value = JSON_PROPERTY_DISABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisabled(@jakarta.annotation.Nonnull DisabledEnum disabled) {
    this.disabled = disabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigLspAnyOfValueAnyOf configLspAnyOfValueAnyOf = (ConfigLspAnyOfValueAnyOf) o;
    return Objects.equals(this.disabled, configLspAnyOfValueAnyOf.disabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigLspAnyOfValueAnyOf {\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

