/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GlobalEventPayloadAnyOf73Properties
 */
@JsonPropertyOrder({
  GlobalEventPayloadAnyOf73Properties.JSON_PROPERTY_NAME,
  GlobalEventPayloadAnyOf73Properties.JSON_PROPERTY_SESSION_I_D,
  GlobalEventPayloadAnyOf73Properties.JSON_PROPERTY_ARGUMENTS,
  GlobalEventPayloadAnyOf73Properties.JSON_PROPERTY_MESSAGE_I_D
})
@JsonTypeName("GlobalEvent_payload_anyOf_73_properties")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class GlobalEventPayloadAnyOf73Properties {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SESSION_I_D = "sessionID";
  @jakarta.annotation.Nonnull
  private String sessionID;

  public static final String JSON_PROPERTY_ARGUMENTS = "arguments";
  @jakarta.annotation.Nonnull
  private String arguments;

  public static final String JSON_PROPERTY_MESSAGE_I_D = "messageID";
  @jakarta.annotation.Nonnull
  private String messageID;

  public GlobalEventPayloadAnyOf73Properties() {
  }

  public GlobalEventPayloadAnyOf73Properties name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public GlobalEventPayloadAnyOf73Properties sessionID(@jakarta.annotation.Nonnull String sessionID) {
    
    this.sessionID = sessionID;
    return this;
  }

  /**
   * Get sessionID
   * @return sessionID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSessionID() {
    return sessionID;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionID(@jakarta.annotation.Nonnull String sessionID) {
    this.sessionID = sessionID;
  }

  public GlobalEventPayloadAnyOf73Properties arguments(@jakarta.annotation.Nonnull String arguments) {
    
    this.arguments = arguments;
    return this;
  }

  /**
   * Get arguments
   * @return arguments
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getArguments() {
    return arguments;
  }


  @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setArguments(@jakarta.annotation.Nonnull String arguments) {
    this.arguments = arguments;
  }

  public GlobalEventPayloadAnyOf73Properties messageID(@jakarta.annotation.Nonnull String messageID) {
    
    this.messageID = messageID;
    return this;
  }

  /**
   * Get messageID
   * @return messageID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessageID() {
    return messageID;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageID(@jakarta.annotation.Nonnull String messageID) {
    this.messageID = messageID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalEventPayloadAnyOf73Properties globalEventPayloadAnyOf73Properties = (GlobalEventPayloadAnyOf73Properties) o;
    return Objects.equals(this.name, globalEventPayloadAnyOf73Properties.name) &&
        Objects.equals(this.sessionID, globalEventPayloadAnyOf73Properties.sessionID) &&
        Objects.equals(this.arguments, globalEventPayloadAnyOf73Properties.arguments) &&
        Objects.equals(this.messageID, globalEventPayloadAnyOf73Properties.messageID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, sessionID, arguments, messageID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalEventPayloadAnyOf73Properties {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

