/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ToolFileContent;
import com.example.opencode.sdk.model.ToolTextContent;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GlobalEventPayloadAnyOf39PropertiesContentInner
 */
@JsonPropertyOrder({
  GlobalEventPayloadAnyOf39PropertiesContentInner.JSON_PROPERTY_TYPE,
  GlobalEventPayloadAnyOf39PropertiesContentInner.JSON_PROPERTY_TEXT,
  GlobalEventPayloadAnyOf39PropertiesContentInner.JSON_PROPERTY_URI,
  GlobalEventPayloadAnyOf39PropertiesContentInner.JSON_PROPERTY_MIME,
  GlobalEventPayloadAnyOf39PropertiesContentInner.JSON_PROPERTY_NAME
})
@JsonTypeName("GlobalEvent_payload_anyOf_39_properties_content_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class GlobalEventPayloadAnyOf39PropertiesContentInner {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TEXT(String.valueOf("text")),
    
    FILE(String.valueOf("file"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nonnull
  private String text;

  public static final String JSON_PROPERTY_URI = "uri";
  @jakarta.annotation.Nonnull
  private String uri;

  public static final String JSON_PROPERTY_MIME = "mime";
  @jakarta.annotation.Nonnull
  private String mime;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public GlobalEventPayloadAnyOf39PropertiesContentInner() {
  }

  public GlobalEventPayloadAnyOf39PropertiesContentInner type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public GlobalEventPayloadAnyOf39PropertiesContentInner text(@jakarta.annotation.Nonnull String text) {
    
    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@jakarta.annotation.Nonnull String text) {
    this.text = text;
  }

  public GlobalEventPayloadAnyOf39PropertiesContentInner uri(@jakarta.annotation.Nonnull String uri) {
    
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   * @return uri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUri() {
    return uri;
  }


  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUri(@jakarta.annotation.Nonnull String uri) {
    this.uri = uri;
  }

  public GlobalEventPayloadAnyOf39PropertiesContentInner mime(@jakarta.annotation.Nonnull String mime) {
    
    this.mime = mime;
    return this;
  }

  /**
   * Get mime
   * @return mime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMime() {
    return mime;
  }


  @JsonProperty(value = JSON_PROPERTY_MIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMime(@jakarta.annotation.Nonnull String mime) {
    this.mime = mime;
  }

  public GlobalEventPayloadAnyOf39PropertiesContentInner name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalEventPayloadAnyOf39PropertiesContentInner globalEventPayloadAnyOf39PropertiesContentInner = (GlobalEventPayloadAnyOf39PropertiesContentInner) o;
    return Objects.equals(this.type, globalEventPayloadAnyOf39PropertiesContentInner.type) &&
        Objects.equals(this.text, globalEventPayloadAnyOf39PropertiesContentInner.text) &&
        Objects.equals(this.uri, globalEventPayloadAnyOf39PropertiesContentInner.uri) &&
        Objects.equals(this.mime, globalEventPayloadAnyOf39PropertiesContentInner.mime) &&
        Objects.equals(this.name, globalEventPayloadAnyOf39PropertiesContentInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, text, uri, mime, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalEventPayloadAnyOf39PropertiesContentInner {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    mime: ").append(toIndentedString(mime)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

