/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.LocationRef;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GlobalEventPayloadAnyOf13Properties
 */
@JsonPropertyOrder({
  GlobalEventPayloadAnyOf13Properties.JSON_PROPERTY_TIMESTAMP,
  GlobalEventPayloadAnyOf13Properties.JSON_PROPERTY_SESSION_I_D,
  GlobalEventPayloadAnyOf13Properties.JSON_PROPERTY_LOCATION,
  GlobalEventPayloadAnyOf13Properties.JSON_PROPERTY_SUBDIRECTORY
})
@JsonTypeName("GlobalEvent_payload_anyOf_13_properties")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GlobalEventPayloadAnyOf13Properties {
  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nonnull
  private BigDecimal timestamp;

  public static final String JSON_PROPERTY_SESSION_I_D = "sessionID";
  @jakarta.annotation.Nonnull
  private String sessionID;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @jakarta.annotation.Nonnull
  private LocationRef location;

  public static final String JSON_PROPERTY_SUBDIRECTORY = "subdirectory";
  @jakarta.annotation.Nullable
  private String subdirectory;

  public GlobalEventPayloadAnyOf13Properties() {
  }

  public GlobalEventPayloadAnyOf13Properties timestamp(@jakarta.annotation.Nonnull BigDecimal timestamp) {

    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@jakarta.annotation.Nonnull BigDecimal timestamp) {
    this.timestamp = timestamp;
  }

  public GlobalEventPayloadAnyOf13Properties sessionID(@jakarta.annotation.Nonnull String sessionID) {

    this.sessionID = sessionID;
    return this;
  }

  /**
   * Get sessionID
   * @return sessionID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSessionID() {
    return sessionID;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionID(@jakarta.annotation.Nonnull String sessionID) {
    this.sessionID = sessionID;
  }

  public GlobalEventPayloadAnyOf13Properties location(@jakarta.annotation.Nonnull LocationRef location) {

    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocationRef getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(@jakarta.annotation.Nonnull LocationRef location) {
    this.location = location;
  }

  public GlobalEventPayloadAnyOf13Properties subdirectory(@jakarta.annotation.Nullable String subdirectory) {

    this.subdirectory = subdirectory;
    return this;
  }

  /**
   * Get subdirectory
   * @return subdirectory
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBDIRECTORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubdirectory() {
    return subdirectory;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBDIRECTORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubdirectory(@jakarta.annotation.Nullable String subdirectory) {
    this.subdirectory = subdirectory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalEventPayloadAnyOf13Properties globalEventPayloadAnyOf13Properties = (GlobalEventPayloadAnyOf13Properties) o;
    return Objects.equals(this.timestamp, globalEventPayloadAnyOf13Properties.timestamp) &&
        Objects.equals(this.sessionID, globalEventPayloadAnyOf13Properties.sessionID) &&
        Objects.equals(this.location, globalEventPayloadAnyOf13Properties.location) &&
        Objects.equals(this.subdirectory, globalEventPayloadAnyOf13Properties.subdirectory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, sessionID, location, subdirectory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalEventPayloadAnyOf13Properties {\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    subdirectory: ").append(toIndentedString(subdirectory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
