/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.IntegrationAttemptNotFoundErrorEncoded;
import com.example.opencode.sdk.model.IntegrationNotFoundErrorEncoded;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * IntegrationOauthStatus404Response
 */
@JsonPropertyOrder({
  IntegrationOauthStatus404Response.JSON_PROPERTY_TAG,
  IntegrationOauthStatus404Response.JSON_PROPERTY_INTEGRATION_I_D,
  IntegrationOauthStatus404Response.JSON_PROPERTY_MESSAGE,
  IntegrationOauthStatus404Response.JSON_PROPERTY_ATTEMPT_I_D
})
@JsonTypeName("integration_oauth_status_404_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class IntegrationOauthStatus404Response {
  /**
   * Gets or Sets tag
   */
  public enum TagEnum {
    INTEGRATION_ATTEMPT_NOT_FOUND_ERROR(String.valueOf("IntegrationAttemptNotFoundError"));

    private String value;

    TagEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TagEnum fromValue(String value) {
      for (TagEnum b : TagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TAG = "_tag";
  @jakarta.annotation.Nonnull
  private TagEnum tag;

  public static final String JSON_PROPERTY_INTEGRATION_I_D = "integrationID";
  @jakarta.annotation.Nonnull
  private String integrationID;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_ATTEMPT_I_D = "attemptID";
  @jakarta.annotation.Nonnull
  private String attemptID;

  public IntegrationOauthStatus404Response() {
  }

  public IntegrationOauthStatus404Response tag(@jakarta.annotation.Nonnull TagEnum tag) {

    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TagEnum getTag() {
    return tag;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTag(@jakarta.annotation.Nonnull TagEnum tag) {
    this.tag = tag;
  }

  public IntegrationOauthStatus404Response integrationID(@jakarta.annotation.Nonnull String integrationID) {

    this.integrationID = integrationID;
    return this;
  }

  /**
   * Get integrationID
   * @return integrationID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INTEGRATION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIntegrationID() {
    return integrationID;
  }


  @JsonProperty(value = JSON_PROPERTY_INTEGRATION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIntegrationID(@jakarta.annotation.Nonnull String integrationID) {
    this.integrationID = integrationID;
  }

  public IntegrationOauthStatus404Response message(@jakarta.annotation.Nonnull String message) {

    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }

  public IntegrationOauthStatus404Response attemptID(@jakarta.annotation.Nonnull String attemptID) {

    this.attemptID = attemptID;
    return this;
  }

  /**
   * Get attemptID
   * @return attemptID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ATTEMPT_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAttemptID() {
    return attemptID;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTEMPT_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttemptID(@jakarta.annotation.Nonnull String attemptID) {
    this.attemptID = attemptID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationOauthStatus404Response integrationOauthStatus404Response = (IntegrationOauthStatus404Response) o;
    return Objects.equals(this.tag, integrationOauthStatus404Response.tag) &&
        Objects.equals(this.integrationID, integrationOauthStatus404Response.integrationID) &&
        Objects.equals(this.message, integrationOauthStatus404Response.message) &&
        Objects.equals(this.attemptID, integrationOauthStatus404Response.attemptID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, integrationID, message, attemptID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationOauthStatus404Response {\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    integrationID: ").append(toIndentedString(integrationID)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    attemptID: ").append(toIndentedString(attemptID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
