/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * McpOAuthConfigEncoded
 */
@JsonPropertyOrder({
  McpOAuthConfigEncoded.JSON_PROPERTY_CLIENT_ID,
  McpOAuthConfigEncoded.JSON_PROPERTY_CLIENT_SECRET,
  McpOAuthConfigEncoded.JSON_PROPERTY_SCOPE,
  McpOAuthConfigEncoded.JSON_PROPERTY_CALLBACK_PORT,
  McpOAuthConfigEncoded.JSON_PROPERTY_REDIRECT_URI,
  McpOAuthConfigEncoded.JSON_PROPERTY_AUTH_SERVER_METADATA_URL
})
@JsonTypeName("Mcp.OAuthConfigEncoded")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class McpOAuthConfigEncoded {
  public static final String JSON_PROPERTY_CLIENT_ID = "client_id";
  @jakarta.annotation.Nullable
  private String clientId;

  public static final String JSON_PROPERTY_CLIENT_SECRET = "client_secret";
  @jakarta.annotation.Nullable
  private String clientSecret;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @jakarta.annotation.Nullable
  private String scope;

  public static final String JSON_PROPERTY_CALLBACK_PORT = "callback_port";
  @jakarta.annotation.Nullable
  private Integer callbackPort;

  public static final String JSON_PROPERTY_REDIRECT_URI = "redirect_uri";
  @jakarta.annotation.Nullable
  private String redirectUri;

  public static final String JSON_PROPERTY_AUTH_SERVER_METADATA_URL = "auth_server_metadata_url";
  @jakarta.annotation.Nullable
  private String authServerMetadataUrl;

  public McpOAuthConfigEncoded() {
  }

  public McpOAuthConfigEncoded clientId(@jakarta.annotation.Nullable String clientId) {

    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientId() {
    return clientId;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientId(@jakarta.annotation.Nullable String clientId) {
    this.clientId = clientId;
  }

  public McpOAuthConfigEncoded clientSecret(@jakarta.annotation.Nullable String clientSecret) {

    this.clientSecret = clientSecret;
    return this;
  }

  /**
   * Get clientSecret
   * @return clientSecret
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientSecret() {
    return clientSecret;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientSecret(@jakarta.annotation.Nullable String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public McpOAuthConfigEncoded scope(@jakarta.annotation.Nullable String scope) {

    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@jakarta.annotation.Nullable String scope) {
    this.scope = scope;
  }

  public McpOAuthConfigEncoded callbackPort(@jakarta.annotation.Nullable Integer callbackPort) {

    this.callbackPort = callbackPort;
    return this;
  }

  /**
   * Get callbackPort
   * minimum: 1
   * maximum: 65535
   * @return callbackPort
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALLBACK_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCallbackPort() {
    return callbackPort;
  }


  @JsonProperty(value = JSON_PROPERTY_CALLBACK_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallbackPort(@jakarta.annotation.Nullable Integer callbackPort) {
    this.callbackPort = callbackPort;
  }

  public McpOAuthConfigEncoded redirectUri(@jakarta.annotation.Nullable String redirectUri) {

    this.redirectUri = redirectUri;
    return this;
  }

  /**
   * Get redirectUri
   * @return redirectUri
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRedirectUri() {
    return redirectUri;
  }


  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedirectUri(@jakarta.annotation.Nullable String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public McpOAuthConfigEncoded authServerMetadataUrl(@jakarta.annotation.Nullable String authServerMetadataUrl) {

    this.authServerMetadataUrl = authServerMetadataUrl;
    return this;
  }

  /**
   * Get authServerMetadataUrl
   * @return authServerMetadataUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTH_SERVER_METADATA_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthServerMetadataUrl() {
    return authServerMetadataUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH_SERVER_METADATA_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthServerMetadataUrl(@jakarta.annotation.Nullable String authServerMetadataUrl) {
    this.authServerMetadataUrl = authServerMetadataUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    McpOAuthConfigEncoded mcpOAuthConfigEncoded = (McpOAuthConfigEncoded) o;
    return Objects.equals(this.clientId, mcpOAuthConfigEncoded.clientId) &&
        Objects.equals(this.clientSecret, mcpOAuthConfigEncoded.clientSecret) &&
        Objects.equals(this.scope, mcpOAuthConfigEncoded.scope) &&
        Objects.equals(this.callbackPort, mcpOAuthConfigEncoded.callbackPort) &&
        Objects.equals(this.redirectUri, mcpOAuthConfigEncoded.redirectUri) &&
        Objects.equals(this.authServerMetadataUrl, mcpOAuthConfigEncoded.authServerMetadataUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, clientSecret, scope, callbackPort, redirectUri, authServerMetadataUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class McpOAuthConfigEncoded {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    callbackPort: ").append(toIndentedString(callbackPort)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    authServerMetadataUrl: ").append(toIndentedString(authServerMetadataUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
