/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * McpResourceTemplate
 */
@JsonPropertyOrder({
  McpResourceTemplate.JSON_PROPERTY_SERVER,
  McpResourceTemplate.JSON_PROPERTY_NAME,
  McpResourceTemplate.JSON_PROPERTY_URI_TEMPLATE,
  McpResourceTemplate.JSON_PROPERTY_DESCRIPTION,
  McpResourceTemplate.JSON_PROPERTY_MIME_TYPE
})
@JsonTypeName("Mcp.ResourceTemplate")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class McpResourceTemplate {
  public static final String JSON_PROPERTY_SERVER = "server";
  @jakarta.annotation.Nonnull
  private String server;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_URI_TEMPLATE = "uriTemplate";
  @jakarta.annotation.Nonnull
  private String uriTemplate;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_MIME_TYPE = "mimeType";
  @jakarta.annotation.Nullable
  private String mimeType;

  public McpResourceTemplate() {
  }

  public McpResourceTemplate server(@jakarta.annotation.Nonnull String server) {

    this.server = server;
    return this;
  }

  /**
   * Get server
   * @return server
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SERVER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getServer() {
    return server;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setServer(@jakarta.annotation.Nonnull String server) {
    this.server = server;
  }

  public McpResourceTemplate name(@jakarta.annotation.Nonnull String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public McpResourceTemplate uriTemplate(@jakarta.annotation.Nonnull String uriTemplate) {

    this.uriTemplate = uriTemplate;
    return this;
  }

  /**
   * Get uriTemplate
   * @return uriTemplate
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URI_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUriTemplate() {
    return uriTemplate;
  }


  @JsonProperty(value = JSON_PROPERTY_URI_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUriTemplate(@jakarta.annotation.Nonnull String uriTemplate) {
    this.uriTemplate = uriTemplate;
  }

  public McpResourceTemplate description(@jakarta.annotation.Nullable String description) {

    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public McpResourceTemplate mimeType(@jakarta.annotation.Nullable String mimeType) {

    this.mimeType = mimeType;
    return this;
  }

  /**
   * Get mimeType
   * @return mimeType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MIME_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMimeType() {
    return mimeType;
  }


  @JsonProperty(value = JSON_PROPERTY_MIME_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMimeType(@jakarta.annotation.Nullable String mimeType) {
    this.mimeType = mimeType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    McpResourceTemplate mcpResourceTemplate = (McpResourceTemplate) o;
    return Objects.equals(this.server, mcpResourceTemplate.server) &&
        Objects.equals(this.name, mcpResourceTemplate.name) &&
        Objects.equals(this.uriTemplate, mcpResourceTemplate.uriTemplate) &&
        Objects.equals(this.description, mcpResourceTemplate.description) &&
        Objects.equals(this.mimeType, mcpResourceTemplate.mimeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(server, name, uriTemplate, description, mimeType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class McpResourceTemplate {\n");
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    uriTemplate: ").append(toIndentedString(uriTemplate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
