/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.AssistantMessage;
import com.example.opencode.sdk.model.AssistantMessageError;
import com.example.opencode.sdk.model.AssistantMessagePath;
import com.example.opencode.sdk.model.AssistantMessageTime;
import com.example.opencode.sdk.model.AssistantMessageTokens;
import com.example.opencode.sdk.model.OutputFormat;
import com.example.opencode.sdk.model.UserMessage;
import com.example.opencode.sdk.model.UserMessageModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Message
 */
@JsonPropertyOrder({
  Message.JSON_PROPERTY_ID,
  Message.JSON_PROPERTY_SESSION_I_D,
  Message.JSON_PROPERTY_ROLE,
  Message.JSON_PROPERTY_TIME,
  Message.JSON_PROPERTY_FORMAT,
  Message.JSON_PROPERTY_SUMMARY,
  Message.JSON_PROPERTY_AGENT,
  Message.JSON_PROPERTY_MODEL,
  Message.JSON_PROPERTY_SYSTEM,
  Message.JSON_PROPERTY_TOOLS,
  Message.JSON_PROPERTY_ERROR,
  Message.JSON_PROPERTY_PARENT_I_D,
  Message.JSON_PROPERTY_MODEL_I_D,
  Message.JSON_PROPERTY_PROVIDER_I_D,
  Message.JSON_PROPERTY_MODE,
  Message.JSON_PROPERTY_PATH,
  Message.JSON_PROPERTY_COST,
  Message.JSON_PROPERTY_TOKENS,
  Message.JSON_PROPERTY_STRUCTURED,
  Message.JSON_PROPERTY_VARIANT,
  Message.JSON_PROPERTY_FINISH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Message {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_SESSION_I_D = "sessionID";
  @jakarta.annotation.Nonnull
  private String sessionID;

  /**
   * Gets or Sets role
   */
  public enum RoleEnum {
    ASSISTANT(String.valueOf("assistant"));

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RoleEnum fromValue(String value) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ROLE = "role";
  @jakarta.annotation.Nonnull
  private RoleEnum role;

  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nonnull
  private AssistantMessageTime time;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nullable
  private OutputFormat format;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @jakarta.annotation.Nullable
  private Boolean summary;

  public static final String JSON_PROPERTY_AGENT = "agent";
  @jakarta.annotation.Nonnull
  private String agent;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nonnull
  private UserMessageModel model;

  public static final String JSON_PROPERTY_SYSTEM = "system";
  @jakarta.annotation.Nullable
  private String system;

  public static final String JSON_PROPERTY_TOOLS = "tools";
  @jakarta.annotation.Nullable
  private Map<String, Boolean> tools = new HashMap<>();

  public static final String JSON_PROPERTY_ERROR = "error";
  @jakarta.annotation.Nullable
  private AssistantMessageError error;

  public static final String JSON_PROPERTY_PARENT_I_D = "parentID";
  @jakarta.annotation.Nonnull
  private String parentID;

  public static final String JSON_PROPERTY_MODEL_I_D = "modelID";
  @jakarta.annotation.Nonnull
  private String modelID;

  public static final String JSON_PROPERTY_PROVIDER_I_D = "providerID";
  @jakarta.annotation.Nonnull
  private String providerID;

  public static final String JSON_PROPERTY_MODE = "mode";
  @jakarta.annotation.Nonnull
  private String mode;

  public static final String JSON_PROPERTY_PATH = "path";
  @jakarta.annotation.Nonnull
  private AssistantMessagePath path;

  public static final String JSON_PROPERTY_COST = "cost";
  @jakarta.annotation.Nonnull
  private BigDecimal cost;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  @jakarta.annotation.Nonnull
  private AssistantMessageTokens tokens;

  public static final String JSON_PROPERTY_STRUCTURED = "structured";
  @jakarta.annotation.Nullable
  private Object structured = null;

  public static final String JSON_PROPERTY_VARIANT = "variant";
  @jakarta.annotation.Nullable
  private String variant;

  public static final String JSON_PROPERTY_FINISH = "finish";
  @jakarta.annotation.Nullable
  private String finish;

  public Message() {
  }

  public Message id(@jakarta.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public Message sessionID(@jakarta.annotation.Nonnull String sessionID) {

    this.sessionID = sessionID;
    return this;
  }

  /**
   * Get sessionID
   * @return sessionID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSessionID() {
    return sessionID;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionID(@jakarta.annotation.Nonnull String sessionID) {
    this.sessionID = sessionID;
  }

  public Message role(@jakarta.annotation.Nonnull RoleEnum role) {

    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RoleEnum getRole() {
    return role;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRole(@jakarta.annotation.Nonnull RoleEnum role) {
    this.role = role;
  }

  public Message time(@jakarta.annotation.Nonnull AssistantMessageTime time) {

    this.time = time;
    return this;
  }

  /**
   * Get time
   * @return time
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AssistantMessageTime getTime() {
    return time;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(@jakarta.annotation.Nonnull AssistantMessageTime time) {
    this.time = time;
  }

  public Message format(@jakarta.annotation.Nullable OutputFormat format) {

    this.format = format;
    return this;
  }

  /**
   * Get format
   * @return format
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OutputFormat getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@jakarta.annotation.Nullable OutputFormat format) {
    this.format = format;
  }

  public Message summary(@jakarta.annotation.Nullable Boolean summary) {

    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@jakarta.annotation.Nullable Boolean summary) {
    this.summary = summary;
  }

  public Message agent(@jakarta.annotation.Nonnull String agent) {

    this.agent = agent;
    return this;
  }

  /**
   * Get agent
   * @return agent
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgent(@jakarta.annotation.Nonnull String agent) {
    this.agent = agent;
  }

  public Message model(@jakarta.annotation.Nonnull UserMessageModel model) {

    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UserMessageModel getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@jakarta.annotation.Nonnull UserMessageModel model) {
    this.model = model;
  }

  public Message system(@jakarta.annotation.Nullable String system) {

    this.system = system;
    return this;
  }

  /**
   * Get system
   * @return system
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYSTEM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSystem() {
    return system;
  }


  @JsonProperty(value = JSON_PROPERTY_SYSTEM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystem(@jakarta.annotation.Nullable String system) {
    this.system = system;
  }

  public Message tools(@jakarta.annotation.Nullable Map<String, Boolean> tools) {

    this.tools = tools;
    return this;
  }

  public Message putToolsItem(String key, Boolean toolsItem) {
    if (this.tools == null) {
      this.tools = new HashMap<>();
    }
    this.tools.put(key, toolsItem);
    return this;
  }

  /**
   * Get tools
   * @return tools
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Boolean> getTools() {
    return tools;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTools(@jakarta.annotation.Nullable Map<String, Boolean> tools) {
    this.tools = tools;
  }

  public Message error(@jakarta.annotation.Nullable AssistantMessageError error) {

    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AssistantMessageError getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@jakarta.annotation.Nullable AssistantMessageError error) {
    this.error = error;
  }

  public Message parentID(@jakarta.annotation.Nonnull String parentID) {

    this.parentID = parentID;
    return this;
  }

  /**
   * Get parentID
   * @return parentID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PARENT_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getParentID() {
    return parentID;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParentID(@jakarta.annotation.Nonnull String parentID) {
    this.parentID = parentID;
  }

  public Message modelID(@jakarta.annotation.Nonnull String modelID) {

    this.modelID = modelID;
    return this;
  }

  /**
   * Get modelID
   * @return modelID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModelID() {
    return modelID;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelID(@jakarta.annotation.Nonnull String modelID) {
    this.modelID = modelID;
  }

  public Message providerID(@jakarta.annotation.Nonnull String providerID) {

    this.providerID = providerID;
    return this;
  }

  /**
   * Get providerID
   * @return providerID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProviderID() {
    return providerID;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProviderID(@jakarta.annotation.Nonnull String providerID) {
    this.providerID = providerID;
  }

  public Message mode(@jakarta.annotation.Nonnull String mode) {

    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMode() {
    return mode;
  }


  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMode(@jakarta.annotation.Nonnull String mode) {
    this.mode = mode;
  }

  public Message path(@jakarta.annotation.Nonnull AssistantMessagePath path) {

    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AssistantMessagePath getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPath(@jakarta.annotation.Nonnull AssistantMessagePath path) {
    this.path = path;
  }

  public Message cost(@jakarta.annotation.Nonnull BigDecimal cost) {

    this.cost = cost;
    return this;
  }

  /**
   * Get cost
   * @return cost
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCost() {
    return cost;
  }


  @JsonProperty(value = JSON_PROPERTY_COST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCost(@jakarta.annotation.Nonnull BigDecimal cost) {
    this.cost = cost;
  }

  public Message tokens(@jakarta.annotation.Nonnull AssistantMessageTokens tokens) {

    this.tokens = tokens;
    return this;
  }

  /**
   * Get tokens
   * @return tokens
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AssistantMessageTokens getTokens() {
    return tokens;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokens(@jakarta.annotation.Nonnull AssistantMessageTokens tokens) {
    this.tokens = tokens;
  }

  public Message structured(@jakarta.annotation.Nullable Object structured) {

    this.structured = structured;
    return this;
  }

  /**
   * Get structured
   * @return structured
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STRUCTURED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getStructured() {
    return structured;
  }


  @JsonProperty(value = JSON_PROPERTY_STRUCTURED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStructured(@jakarta.annotation.Nullable Object structured) {
    this.structured = structured;
  }

  public Message variant(@jakarta.annotation.Nullable String variant) {

    this.variant = variant;
    return this;
  }

  /**
   * Get variant
   * @return variant
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVariant() {
    return variant;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariant(@jakarta.annotation.Nullable String variant) {
    this.variant = variant;
  }

  public Message finish(@jakarta.annotation.Nullable String finish) {

    this.finish = finish;
    return this;
  }

  /**
   * Get finish
   * @return finish
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINISH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFinish() {
    return finish;
  }


  @JsonProperty(value = JSON_PROPERTY_FINISH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinish(@jakarta.annotation.Nullable String finish) {
    this.finish = finish;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.id, message.id) &&
        Objects.equals(this.sessionID, message.sessionID) &&
        Objects.equals(this.role, message.role) &&
        Objects.equals(this.time, message.time) &&
        Objects.equals(this.format, message.format) &&
        Objects.equals(this.summary, message.summary) &&
        Objects.equals(this.agent, message.agent) &&
        Objects.equals(this.model, message.model) &&
        Objects.equals(this.system, message.system) &&
        Objects.equals(this.tools, message.tools) &&
        Objects.equals(this.error, message.error) &&
        Objects.equals(this.parentID, message.parentID) &&
        Objects.equals(this.modelID, message.modelID) &&
        Objects.equals(this.providerID, message.providerID) &&
        Objects.equals(this.mode, message.mode) &&
        Objects.equals(this.path, message.path) &&
        Objects.equals(this.cost, message.cost) &&
        Objects.equals(this.tokens, message.tokens) &&
        Objects.equals(this.structured, message.structured) &&
        Objects.equals(this.variant, message.variant) &&
        Objects.equals(this.finish, message.finish);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sessionID, role, time, format, summary, agent, model, system, tools, error, parentID, modelID, providerID, mode, path, cost, tokens, structured, variant, finish);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    parentID: ").append(toIndentedString(parentID)).append("\n");
    sb.append("    modelID: ").append(toIndentedString(modelID)).append("\n");
    sb.append("    providerID: ").append(toIndentedString(providerID)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    structured: ").append(toIndentedString(structured)).append("\n");
    sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
    sb.append("    finish: ").append(toIndentedString(finish)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
