/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PluginSourceAnyOf1
 */
@JsonPropertyOrder({
  PluginSourceAnyOf1.JSON_PROPERTY_TYPE,
  PluginSourceAnyOf1.JSON_PROPERTY_TARGET,
  PluginSourceAnyOf1.JSON_PROPERTY_VERSION,
  PluginSourceAnyOf1.JSON_PROPERTY_OUTDATED,
  PluginSourceAnyOf1.JSON_PROPERTY_UPDATING
})
@JsonTypeName("Plugin_Source_anyOf_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PluginSourceAnyOf1 {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    PACKAGE(String.valueOf("package"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_TARGET = "target";
  @jakarta.annotation.Nullable
  private String target;

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nullable
  private String version;

  /**
   * Gets or Sets outdated
   */
  public enum OutdatedEnum {
    TRUE(Boolean.valueOf("true"));

    private Boolean value;

    OutdatedEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OutdatedEnum fromValue(Boolean value) {
      for (OutdatedEnum b : OutdatedEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OUTDATED = "outdated";
  @jakarta.annotation.Nullable
  private OutdatedEnum outdated;

  /**
   * Gets or Sets updating
   */
  public enum UpdatingEnum {
    TRUE(Boolean.valueOf("true"));

    private Boolean value;

    UpdatingEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static UpdatingEnum fromValue(Boolean value) {
      for (UpdatingEnum b : UpdatingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_UPDATING = "updating";
  @jakarta.annotation.Nullable
  private UpdatingEnum updating;

  public PluginSourceAnyOf1() {
  }

  public PluginSourceAnyOf1 type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public PluginSourceAnyOf1 target(@jakarta.annotation.Nullable String target) {

    this.target = target;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return target
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTarget() {
    return target;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTarget(@jakarta.annotation.Nullable String target) {
    this.target = target;
  }

  public PluginSourceAnyOf1 version(@jakarta.annotation.Nullable String version) {

    this.version = version;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@jakarta.annotation.Nullable String version) {
    this.version = version;
  }

  public PluginSourceAnyOf1 outdated(@jakarta.annotation.Nullable OutdatedEnum outdated) {

    this.outdated = outdated;
    return this;
  }

  /**
   * Get outdated
   * @return outdated
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OUTDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OutdatedEnum getOutdated() {
    return outdated;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutdated(@jakarta.annotation.Nullable OutdatedEnum outdated) {
    this.outdated = outdated;
  }

  public PluginSourceAnyOf1 updating(@jakarta.annotation.Nullable UpdatingEnum updating) {

    this.updating = updating;
    return this;
  }

  /**
   * Get updating
   * @return updating
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdatingEnum getUpdating() {
    return updating;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdating(@jakarta.annotation.Nullable UpdatingEnum updating) {
    this.updating = updating;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PluginSourceAnyOf1 pluginSourceAnyOf1 = (PluginSourceAnyOf1) o;
    return Objects.equals(this.type, pluginSourceAnyOf1.type) &&
        Objects.equals(this.target, pluginSourceAnyOf1.target) &&
        Objects.equals(this.version, pluginSourceAnyOf1.version) &&
        Objects.equals(this.outdated, pluginSourceAnyOf1.outdated) &&
        Objects.equals(this.updating, pluginSourceAnyOf1.updating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, target, version, outdated, updating);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PluginSourceAnyOf1 {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    outdated: ").append(toIndentedString(outdated)).append("\n");
    sb.append("    updating: ").append(toIndentedString(updating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
