/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProjectSummary
 */
@JsonPropertyOrder({
  ProjectSummary.JSON_PROPERTY_ID,
  ProjectSummary.JSON_PROPERTY_NAME,
  ProjectSummary.JSON_PROPERTY_WORKTREE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ProjectSummary {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_WORKTREE = "worktree";
  @jakarta.annotation.Nonnull
  private String worktree;

  public ProjectSummary() {
  }

  public ProjectSummary id(@jakarta.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public ProjectSummary name(@jakarta.annotation.Nullable String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public ProjectSummary worktree(@jakarta.annotation.Nonnull String worktree) {

    this.worktree = worktree;
    return this;
  }

  /**
   * Get worktree
   * @return worktree
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WORKTREE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorktree() {
    return worktree;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKTREE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorktree(@jakarta.annotation.Nonnull String worktree) {
    this.worktree = worktree;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectSummary projectSummary = (ProjectSummary) o;
    return Objects.equals(this.id, projectSummary.id) &&
        Objects.equals(this.name, projectSummary.name) &&
        Objects.equals(this.worktree, projectSummary.worktree);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, worktree);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectSummary {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    worktree: ").append(toIndentedString(worktree)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
