/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ProjectCommands;
import com.example.opencode.sdk.model.ProjectIcon;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProjectUpdateRequest
 */
@JsonPropertyOrder({
  ProjectUpdateRequest.JSON_PROPERTY_NAME,
  ProjectUpdateRequest.JSON_PROPERTY_ICON,
  ProjectUpdateRequest.JSON_PROPERTY_COMMANDS
})
@JsonTypeName("project_update_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ProjectUpdateRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ICON = "icon";
  @jakarta.annotation.Nullable
  private ProjectIcon icon;

  public static final String JSON_PROPERTY_COMMANDS = "commands";
  @jakarta.annotation.Nullable
  private ProjectCommands commands;

  public ProjectUpdateRequest() {
  }

  public ProjectUpdateRequest name(@jakarta.annotation.Nullable String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public ProjectUpdateRequest icon(@jakarta.annotation.Nullable ProjectIcon icon) {

    this.icon = icon;
    return this;
  }

  /**
   * Get icon
   * @return icon
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ICON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProjectIcon getIcon() {
    return icon;
  }


  @JsonProperty(value = JSON_PROPERTY_ICON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIcon(@jakarta.annotation.Nullable ProjectIcon icon) {
    this.icon = icon;
  }

  public ProjectUpdateRequest commands(@jakarta.annotation.Nullable ProjectCommands commands) {

    this.commands = commands;
    return this;
  }

  /**
   * Get commands
   * @return commands
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMANDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProjectCommands getCommands() {
    return commands;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMANDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommands(@jakarta.annotation.Nullable ProjectCommands commands) {
    this.commands = commands;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectUpdateRequest projectUpdateRequest = (ProjectUpdateRequest) o;
    return Objects.equals(this.name, projectUpdateRequest.name) &&
        Objects.equals(this.icon, projectUpdateRequest.icon) &&
        Objects.equals(this.commands, projectUpdateRequest.commands);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, icon, commands);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectUpdateRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
