/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ProjectCommands;
import com.example.opencode.sdk.model.ProjectIcon;
import com.example.opencode.sdk.model.ProjectTime;
import com.example.opencode.sdk.model.ProjectVcs;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Project
 */
@JsonPropertyOrder({
  Project.JSON_PROPERTY_ID,
  Project.JSON_PROPERTY_WORKTREE,
  Project.JSON_PROPERTY_VCS,
  Project.JSON_PROPERTY_NAME,
  Project.JSON_PROPERTY_ICON,
  Project.JSON_PROPERTY_COMMANDS,
  Project.JSON_PROPERTY_TIME,
  Project.JSON_PROPERTY_SANDBOXES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Project {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_WORKTREE = "worktree";
  @jakarta.annotation.Nonnull
  private String worktree;

  public static final String JSON_PROPERTY_VCS = "vcs";
  @jakarta.annotation.Nullable
  private ProjectVcs vcs;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ICON = "icon";
  @jakarta.annotation.Nullable
  private ProjectIcon icon;

  public static final String JSON_PROPERTY_COMMANDS = "commands";
  @jakarta.annotation.Nullable
  private ProjectCommands commands;

  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nonnull
  private ProjectTime time;

  public static final String JSON_PROPERTY_SANDBOXES = "sandboxes";
  @jakarta.annotation.Nonnull
  private List<String> sandboxes = new ArrayList<>();

  public Project() {
  }

  public Project id(@jakarta.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public Project worktree(@jakarta.annotation.Nonnull String worktree) {

    this.worktree = worktree;
    return this;
  }

  /**
   * Get worktree
   * @return worktree
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WORKTREE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorktree() {
    return worktree;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKTREE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorktree(@jakarta.annotation.Nonnull String worktree) {
    this.worktree = worktree;
  }

  public Project vcs(@jakarta.annotation.Nullable ProjectVcs vcs) {

    this.vcs = vcs;
    return this;
  }

  /**
   * Get vcs
   * @return vcs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VCS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProjectVcs getVcs() {
    return vcs;
  }


  @JsonProperty(value = JSON_PROPERTY_VCS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVcs(@jakarta.annotation.Nullable ProjectVcs vcs) {
    this.vcs = vcs;
  }

  public Project name(@jakarta.annotation.Nullable String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Project icon(@jakarta.annotation.Nullable ProjectIcon icon) {

    this.icon = icon;
    return this;
  }

  /**
   * Get icon
   * @return icon
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ICON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProjectIcon getIcon() {
    return icon;
  }


  @JsonProperty(value = JSON_PROPERTY_ICON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIcon(@jakarta.annotation.Nullable ProjectIcon icon) {
    this.icon = icon;
  }

  public Project commands(@jakarta.annotation.Nullable ProjectCommands commands) {

    this.commands = commands;
    return this;
  }

  /**
   * Get commands
   * @return commands
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMANDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProjectCommands getCommands() {
    return commands;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMANDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommands(@jakarta.annotation.Nullable ProjectCommands commands) {
    this.commands = commands;
  }

  public Project time(@jakarta.annotation.Nonnull ProjectTime time) {

    this.time = time;
    return this;
  }

  /**
   * Get time
   * @return time
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ProjectTime getTime() {
    return time;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(@jakarta.annotation.Nonnull ProjectTime time) {
    this.time = time;
  }

  public Project sandboxes(@jakarta.annotation.Nonnull List<String> sandboxes) {

    this.sandboxes = sandboxes;
    return this;
  }

  public Project addSandboxesItem(String sandboxesItem) {
    if (this.sandboxes == null) {
      this.sandboxes = new ArrayList<>();
    }
    this.sandboxes.add(sandboxesItem);
    return this;
  }

  /**
   * Get sandboxes
   * @return sandboxes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SANDBOXES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getSandboxes() {
    return sandboxes;
  }


  @JsonProperty(value = JSON_PROPERTY_SANDBOXES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSandboxes(@jakarta.annotation.Nonnull List<String> sandboxes) {
    this.sandboxes = sandboxes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Project project = (Project) o;
    return Objects.equals(this.id, project.id) &&
        Objects.equals(this.worktree, project.worktree) &&
        Objects.equals(this.vcs, project.vcs) &&
        Objects.equals(this.name, project.name) &&
        Objects.equals(this.icon, project.icon) &&
        Objects.equals(this.commands, project.commands) &&
        Objects.equals(this.time, project.time) &&
        Objects.equals(this.sandboxes, project.sandboxes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, worktree, vcs, name, icon, commands, time, sandboxes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Project {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    worktree: ").append(toIndentedString(worktree)).append("\n");
    sb.append("    vcs: ").append(toIndentedString(vcs)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    sandboxes: ").append(toIndentedString(sandboxes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
