/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ProviderAuthMethodPromptsInnerAnyOf1OptionsInner;
import com.example.opencode.sdk.model.ProviderAuthMethodPromptsInnerAnyOfWhen;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProviderAuthMethodPromptsInnerAnyOf1
 */
@JsonPropertyOrder({
  ProviderAuthMethodPromptsInnerAnyOf1.JSON_PROPERTY_TYPE,
  ProviderAuthMethodPromptsInnerAnyOf1.JSON_PROPERTY_KEY,
  ProviderAuthMethodPromptsInnerAnyOf1.JSON_PROPERTY_MESSAGE,
  ProviderAuthMethodPromptsInnerAnyOf1.JSON_PROPERTY_OPTIONS,
  ProviderAuthMethodPromptsInnerAnyOf1.JSON_PROPERTY_WHEN
})
@JsonTypeName("ProviderAuthMethod_prompts_inner_anyOf_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ProviderAuthMethodPromptsInnerAnyOf1 {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    SELECT(String.valueOf("select"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @jakarta.annotation.Nonnull
  private List<ProviderAuthMethodPromptsInnerAnyOf1OptionsInner> options = new ArrayList<>();

  public static final String JSON_PROPERTY_WHEN = "when";
  @jakarta.annotation.Nullable
  private ProviderAuthMethodPromptsInnerAnyOfWhen when;

  public ProviderAuthMethodPromptsInnerAnyOf1() {
  }

  public ProviderAuthMethodPromptsInnerAnyOf1 type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public ProviderAuthMethodPromptsInnerAnyOf1 key(@jakarta.annotation.Nonnull String key) {

    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@jakarta.annotation.Nonnull String key) {
    this.key = key;
  }

  public ProviderAuthMethodPromptsInnerAnyOf1 message(@jakarta.annotation.Nonnull String message) {

    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }

  public ProviderAuthMethodPromptsInnerAnyOf1 options(@jakarta.annotation.Nonnull List<ProviderAuthMethodPromptsInnerAnyOf1OptionsInner> options) {

    this.options = options;
    return this;
  }

  public ProviderAuthMethodPromptsInnerAnyOf1 addOptionsItem(ProviderAuthMethodPromptsInnerAnyOf1OptionsInner optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }
    this.options.add(optionsItem);
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ProviderAuthMethodPromptsInnerAnyOf1OptionsInner> getOptions() {
    return options;
  }


  @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOptions(@jakarta.annotation.Nonnull List<ProviderAuthMethodPromptsInnerAnyOf1OptionsInner> options) {
    this.options = options;
  }

  public ProviderAuthMethodPromptsInnerAnyOf1 when(@jakarta.annotation.Nullable ProviderAuthMethodPromptsInnerAnyOfWhen when) {

    this.when = when;
    return this;
  }

  /**
   * Get when
   * @return when
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WHEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProviderAuthMethodPromptsInnerAnyOfWhen getWhen() {
    return when;
  }


  @JsonProperty(value = JSON_PROPERTY_WHEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWhen(@jakarta.annotation.Nullable ProviderAuthMethodPromptsInnerAnyOfWhen when) {
    this.when = when;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProviderAuthMethodPromptsInnerAnyOf1 providerAuthMethodPromptsInnerAnyOf1 = (ProviderAuthMethodPromptsInnerAnyOf1) o;
    return Objects.equals(this.type, providerAuthMethodPromptsInnerAnyOf1.type) &&
        Objects.equals(this.key, providerAuthMethodPromptsInnerAnyOf1.key) &&
        Objects.equals(this.message, providerAuthMethodPromptsInnerAnyOf1.message) &&
        Objects.equals(this.options, providerAuthMethodPromptsInnerAnyOf1.options) &&
        Objects.equals(this.when, providerAuthMethodPromptsInnerAnyOf1.when);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, key, message, options, when);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProviderAuthMethodPromptsInnerAnyOf1 {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    when: ").append(toIndentedString(when)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
