/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PtyNotFoundError
 */
@JsonPropertyOrder({
  PtyNotFoundError.JSON_PROPERTY_TAG,
  PtyNotFoundError.JSON_PROPERTY_PTY_I_D,
  PtyNotFoundError.JSON_PROPERTY_MESSAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PtyNotFoundError {
  /**
   * Gets or Sets tag
   */
  public enum TagEnum {
    PTY_NOT_FOUND_ERROR(String.valueOf("PtyNotFoundError"));

    private String value;

    TagEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TagEnum fromValue(String value) {
      for (TagEnum b : TagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TAG = "_tag";
  @jakarta.annotation.Nonnull
  private TagEnum tag;

  public static final String JSON_PROPERTY_PTY_I_D = "ptyID";
  @jakarta.annotation.Nonnull
  private String ptyID;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public PtyNotFoundError() {
  }

  public PtyNotFoundError tag(@jakarta.annotation.Nonnull TagEnum tag) {

    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TagEnum getTag() {
    return tag;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTag(@jakarta.annotation.Nonnull TagEnum tag) {
    this.tag = tag;
  }

  public PtyNotFoundError ptyID(@jakarta.annotation.Nonnull String ptyID) {

    this.ptyID = ptyID;
    return this;
  }

  /**
   * Get ptyID
   * @return ptyID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PTY_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPtyID() {
    return ptyID;
  }


  @JsonProperty(value = JSON_PROPERTY_PTY_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPtyID(@jakarta.annotation.Nonnull String ptyID) {
    this.ptyID = ptyID;
  }

  public PtyNotFoundError message(@jakarta.annotation.Nonnull String message) {

    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtyNotFoundError ptyNotFoundError = (PtyNotFoundError) o;
    return Objects.equals(this.tag, ptyNotFoundError.tag) &&
        Objects.equals(this.ptyID, ptyNotFoundError.ptyID) &&
        Objects.equals(this.message, ptyNotFoundError.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, ptyID, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtyNotFoundError {\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    ptyID: ").append(toIndentedString(ptyID)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
