/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.FileDiff;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RevertState
 */
@JsonPropertyOrder({
  RevertState.JSON_PROPERTY_MESSAGE_I_D,
  RevertState.JSON_PROPERTY_PART_I_D,
  RevertState.JSON_PROPERTY_SNAPSHOT,
  RevertState.JSON_PROPERTY_DIFF,
  RevertState.JSON_PROPERTY_FILES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class RevertState {
  public static final String JSON_PROPERTY_MESSAGE_I_D = "messageID";
  @jakarta.annotation.Nonnull
  private String messageID;

  public static final String JSON_PROPERTY_PART_I_D = "partID";
  @jakarta.annotation.Nullable
  private String partID;

  public static final String JSON_PROPERTY_SNAPSHOT = "snapshot";
  @jakarta.annotation.Nullable
  private String snapshot;

  public static final String JSON_PROPERTY_DIFF = "diff";
  @jakarta.annotation.Nullable
  private String diff;

  public static final String JSON_PROPERTY_FILES = "files";
  @jakarta.annotation.Nullable
  private List<FileDiff> files = new ArrayList<>();

  public RevertState() {
  }

  public RevertState messageID(@jakarta.annotation.Nonnull String messageID) {

    this.messageID = messageID;
    return this;
  }

  /**
   * Get messageID
   * @return messageID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessageID() {
    return messageID;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageID(@jakarta.annotation.Nonnull String messageID) {
    this.messageID = messageID;
  }

  public RevertState partID(@jakarta.annotation.Nullable String partID) {

    this.partID = partID;
    return this;
  }

  /**
   * Get partID
   * @return partID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PART_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartID() {
    return partID;
  }


  @JsonProperty(value = JSON_PROPERTY_PART_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartID(@jakarta.annotation.Nullable String partID) {
    this.partID = partID;
  }

  public RevertState snapshot(@jakarta.annotation.Nullable String snapshot) {

    this.snapshot = snapshot;
    return this;
  }

  /**
   * Get snapshot
   * @return snapshot
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSnapshot() {
    return snapshot;
  }


  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSnapshot(@jakarta.annotation.Nullable String snapshot) {
    this.snapshot = snapshot;
  }

  public RevertState diff(@jakarta.annotation.Nullable String diff) {

    this.diff = diff;
    return this;
  }

  /**
   * Get diff
   * @return diff
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIFF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDiff() {
    return diff;
  }


  @JsonProperty(value = JSON_PROPERTY_DIFF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiff(@jakarta.annotation.Nullable String diff) {
    this.diff = diff;
  }

  public RevertState files(@jakarta.annotation.Nullable List<FileDiff> files) {

    this.files = files;
    return this;
  }

  public RevertState addFilesItem(FileDiff filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

  /**
   * Get files
   * @return files
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FileDiff> getFiles() {
    return files;
  }


  @JsonProperty(value = JSON_PROPERTY_FILES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiles(@jakarta.annotation.Nullable List<FileDiff> files) {
    this.files = files;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RevertState revertState = (RevertState) o;
    return Objects.equals(this.messageID, revertState.messageID) &&
        Objects.equals(this.partID, revertState.partID) &&
        Objects.equals(this.snapshot, revertState.snapshot) &&
        Objects.equals(this.diff, revertState.diff) &&
        Objects.equals(this.files, revertState.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageID, partID, snapshot, diff, files);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RevertState {\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    partID: ").append(toIndentedString(partID)).append("\n");
    sb.append("    snapshot: ").append(toIndentedString(snapshot)).append("\n");
    sb.append("    diff: ").append(toIndentedString(diff)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
