/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.OutputFormat;
import com.example.opencode.sdk.model.SessionPromptRequestModel;
import com.example.opencode.sdk.model.SessionPromptRequestPartsInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SessionPromptRequest
 */
@JsonPropertyOrder({
  SessionPromptRequest.JSON_PROPERTY_MESSAGE_I_D,
  SessionPromptRequest.JSON_PROPERTY_MODEL,
  SessionPromptRequest.JSON_PROPERTY_AGENT,
  SessionPromptRequest.JSON_PROPERTY_NO_REPLY,
  SessionPromptRequest.JSON_PROPERTY_TOOLS,
  SessionPromptRequest.JSON_PROPERTY_FORMAT,
  SessionPromptRequest.JSON_PROPERTY_SYSTEM,
  SessionPromptRequest.JSON_PROPERTY_VARIANT,
  SessionPromptRequest.JSON_PROPERTY_PARTS
})
@JsonTypeName("session_prompt_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SessionPromptRequest {
  public static final String JSON_PROPERTY_MESSAGE_I_D = "messageID";
  @jakarta.annotation.Nullable
  private String messageID;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nullable
  private SessionPromptRequestModel model;

  public static final String JSON_PROPERTY_AGENT = "agent";
  @jakarta.annotation.Nullable
  private String agent;

  public static final String JSON_PROPERTY_NO_REPLY = "noReply";
  @jakarta.annotation.Nullable
  private Boolean noReply;

  public static final String JSON_PROPERTY_TOOLS = "tools";
  @jakarta.annotation.Nullable
  private Map<String, Boolean> tools = new HashMap<>();

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nullable
  private OutputFormat format;

  public static final String JSON_PROPERTY_SYSTEM = "system";
  @jakarta.annotation.Nullable
  private String system;

  public static final String JSON_PROPERTY_VARIANT = "variant";
  @jakarta.annotation.Nullable
  private String variant;

  public static final String JSON_PROPERTY_PARTS = "parts";
  @jakarta.annotation.Nonnull
  private List<SessionPromptRequestPartsInner> parts = new ArrayList<>();

  public SessionPromptRequest() {
  }

  public SessionPromptRequest messageID(@jakarta.annotation.Nullable String messageID) {

    this.messageID = messageID;
    return this;
  }

  /**
   * Get messageID
   * @return messageID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessageID() {
    return messageID;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageID(@jakarta.annotation.Nullable String messageID) {
    this.messageID = messageID;
  }

  public SessionPromptRequest model(@jakarta.annotation.Nullable SessionPromptRequestModel model) {

    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionPromptRequestModel getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@jakarta.annotation.Nullable SessionPromptRequestModel model) {
    this.model = model;
  }

  public SessionPromptRequest agent(@jakarta.annotation.Nullable String agent) {

    this.agent = agent;
    return this;
  }

  /**
   * Get agent
   * @return agent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgent(@jakarta.annotation.Nullable String agent) {
    this.agent = agent;
  }

  public SessionPromptRequest noReply(@jakarta.annotation.Nullable Boolean noReply) {

    this.noReply = noReply;
    return this;
  }

  /**
   * Get noReply
   * @return noReply
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NO_REPLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoReply() {
    return noReply;
  }


  @JsonProperty(value = JSON_PROPERTY_NO_REPLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoReply(@jakarta.annotation.Nullable Boolean noReply) {
    this.noReply = noReply;
  }

  public SessionPromptRequest tools(@jakarta.annotation.Nullable Map<String, Boolean> tools) {

    this.tools = tools;
    return this;
  }

  public SessionPromptRequest putToolsItem(String key, Boolean toolsItem) {
    if (this.tools == null) {
      this.tools = new HashMap<>();
    }
    this.tools.put(key, toolsItem);
    return this;
  }

  /**
   * Get tools
   * @return tools
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Boolean> getTools() {
    return tools;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTools(@jakarta.annotation.Nullable Map<String, Boolean> tools) {
    this.tools = tools;
  }

  public SessionPromptRequest format(@jakarta.annotation.Nullable OutputFormat format) {

    this.format = format;
    return this;
  }

  /**
   * Get format
   * @return format
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OutputFormat getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@jakarta.annotation.Nullable OutputFormat format) {
    this.format = format;
  }

  public SessionPromptRequest system(@jakarta.annotation.Nullable String system) {

    this.system = system;
    return this;
  }

  /**
   * Get system
   * @return system
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYSTEM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSystem() {
    return system;
  }


  @JsonProperty(value = JSON_PROPERTY_SYSTEM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystem(@jakarta.annotation.Nullable String system) {
    this.system = system;
  }

  public SessionPromptRequest variant(@jakarta.annotation.Nullable String variant) {

    this.variant = variant;
    return this;
  }

  /**
   * Get variant
   * @return variant
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVariant() {
    return variant;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariant(@jakarta.annotation.Nullable String variant) {
    this.variant = variant;
  }

  public SessionPromptRequest parts(@jakarta.annotation.Nonnull List<SessionPromptRequestPartsInner> parts) {

    this.parts = parts;
    return this;
  }

  public SessionPromptRequest addPartsItem(SessionPromptRequestPartsInner partsItem) {
    if (this.parts == null) {
      this.parts = new ArrayList<>();
    }
    this.parts.add(partsItem);
    return this;
  }

  /**
   * Get parts
   * @return parts
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PARTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SessionPromptRequestPartsInner> getParts() {
    return parts;
  }


  @JsonProperty(value = JSON_PROPERTY_PARTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParts(@jakarta.annotation.Nonnull List<SessionPromptRequestPartsInner> parts) {
    this.parts = parts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionPromptRequest sessionPromptRequest = (SessionPromptRequest) o;
    return Objects.equals(this.messageID, sessionPromptRequest.messageID) &&
        Objects.equals(this.model, sessionPromptRequest.model) &&
        Objects.equals(this.agent, sessionPromptRequest.agent) &&
        Objects.equals(this.noReply, sessionPromptRequest.noReply) &&
        Objects.equals(this.tools, sessionPromptRequest.tools) &&
        Objects.equals(this.format, sessionPromptRequest.format) &&
        Objects.equals(this.system, sessionPromptRequest.system) &&
        Objects.equals(this.variant, sessionPromptRequest.variant) &&
        Objects.equals(this.parts, sessionPromptRequest.parts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageID, model, agent, noReply, tools, format, system, variant, parts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionPromptRequest {\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    noReply: ").append(toIndentedString(noReply)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
