/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SessionV2InfoTime
 */
@JsonPropertyOrder({
  SessionV2InfoTime.JSON_PROPERTY_CREATED,
  SessionV2InfoTime.JSON_PROPERTY_UPDATED,
  SessionV2InfoTime.JSON_PROPERTY_ARCHIVED
})
@JsonTypeName("SessionV2Info_time")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SessionV2InfoTime {
  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nonnull
  private BigDecimal created;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @jakarta.annotation.Nonnull
  private BigDecimal updated;

  public static final String JSON_PROPERTY_ARCHIVED = "archived";
  @jakarta.annotation.Nullable
  private BigDecimal archived;

  public SessionV2InfoTime() {
  }

  public SessionV2InfoTime created(@jakarta.annotation.Nonnull BigDecimal created) {

    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@jakarta.annotation.Nonnull BigDecimal created) {
    this.created = created;
  }

  public SessionV2InfoTime updated(@jakarta.annotation.Nonnull BigDecimal updated) {

    this.updated = updated;
    return this;
  }

  /**
   * Get updated
   * @return updated
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getUpdated() {
    return updated;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdated(@jakarta.annotation.Nonnull BigDecimal updated) {
    this.updated = updated;
  }

  public SessionV2InfoTime archived(@jakarta.annotation.Nullable BigDecimal archived) {

    this.archived = archived;
    return this;
  }

  /**
   * Get archived
   * @return archived
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARCHIVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getArchived() {
    return archived;
  }


  @JsonProperty(value = JSON_PROPERTY_ARCHIVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchived(@jakarta.annotation.Nullable BigDecimal archived) {
    this.archived = archived;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionV2InfoTime sessionV2InfoTime = (SessionV2InfoTime) o;
    return Objects.equals(this.created, sessionV2InfoTime.created) &&
        Objects.equals(this.updated, sessionV2InfoTime.updated) &&
        Objects.equals(this.archived, sessionV2InfoTime.archived);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, updated, archived);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionV2InfoTime {\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
