/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SessionForkBoundaryAnyOf1
 */
@JsonPropertyOrder({
  SessionForkBoundaryAnyOf1.JSON_PROPERTY_TYPE,
  SessionForkBoundaryAnyOf1.JSON_PROPERTY_MESSAGE_I_D
})
@JsonTypeName("Session_ForkBoundary_anyOf_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SessionForkBoundaryAnyOf1 {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    THROUGH(String.valueOf("through"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_MESSAGE_I_D = "messageID";
  @jakarta.annotation.Nullable
  private String messageID;

  public SessionForkBoundaryAnyOf1() {
  }

  public SessionForkBoundaryAnyOf1 type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public SessionForkBoundaryAnyOf1 messageID(@jakarta.annotation.Nullable String messageID) {

    this.messageID = messageID;
    return this;
  }

  /**
   * User message whose turn to diff. Defaults to the turn of the newest user message.
   * @return messageID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessageID() {
    return messageID;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageID(@jakarta.annotation.Nullable String messageID) {
    this.messageID = messageID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionForkBoundaryAnyOf1 sessionForkBoundaryAnyOf1 = (SessionForkBoundaryAnyOf1) o;
    return Objects.equals(this.type, sessionForkBoundaryAnyOf1.type) &&
        Objects.equals(this.messageID, sessionForkBoundaryAnyOf1.messageID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, messageID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionForkBoundaryAnyOf1 {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
