/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.GlobalEventPayloadAnyOf22Properties;
import com.example.opencode.sdk.model.LocationRef;
import com.example.opencode.sdk.model.SessionStatusDurable;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SessionNextStepFailed
 */
@JsonPropertyOrder({
  SessionNextStepFailed.JSON_PROPERTY_ID,
  SessionNextStepFailed.JSON_PROPERTY_METADATA,
  SessionNextStepFailed.JSON_PROPERTY_TYPE,
  SessionNextStepFailed.JSON_PROPERTY_DURABLE,
  SessionNextStepFailed.JSON_PROPERTY_LOCATION,
  SessionNextStepFailed.JSON_PROPERTY_DATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SessionNextStepFailed {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Object metadata;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    SESSION_NEXT_STEP_FAILED(String.valueOf("session.next.step.failed"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_DURABLE = "durable";
  @jakarta.annotation.Nullable
  private SessionStatusDurable durable;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @jakarta.annotation.Nullable
  private LocationRef location;

  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nonnull
  private GlobalEventPayloadAnyOf22Properties data;

  public SessionNextStepFailed() {
  }

  public SessionNextStepFailed id(@jakarta.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public SessionNextStepFailed metadata(@jakarta.annotation.Nullable Object metadata) {

    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }

  public SessionNextStepFailed type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public SessionNextStepFailed durable(@jakarta.annotation.Nullable SessionStatusDurable durable) {

    this.durable = durable;
    return this;
  }

  /**
   * Get durable
   * @return durable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DURABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionStatusDurable getDurable() {
    return durable;
  }


  @JsonProperty(value = JSON_PROPERTY_DURABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDurable(@jakarta.annotation.Nullable SessionStatusDurable durable) {
    this.durable = durable;
  }

  public SessionNextStepFailed location(@jakarta.annotation.Nullable LocationRef location) {

    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocationRef getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(@jakarta.annotation.Nullable LocationRef location) {
    this.location = location;
  }

  public SessionNextStepFailed data(@jakarta.annotation.Nonnull GlobalEventPayloadAnyOf22Properties data) {

    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GlobalEventPayloadAnyOf22Properties getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@jakarta.annotation.Nonnull GlobalEventPayloadAnyOf22Properties data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionNextStepFailed sessionNextStepFailed = (SessionNextStepFailed) o;
    return Objects.equals(this.id, sessionNextStepFailed.id) &&
        Objects.equals(this.metadata, sessionNextStepFailed.metadata) &&
        Objects.equals(this.type, sessionNextStepFailed.type) &&
        Objects.equals(this.durable, sessionNextStepFailed.durable) &&
        Objects.equals(this.location, sessionNextStepFailed.location) &&
        Objects.equals(this.data, sessionNextStepFailed.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, metadata, type, durable, location, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionNextStepFailed {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    durable: ").append(toIndentedString(durable)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
