/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ShellInfoTime
 */
@JsonPropertyOrder({
  ShellInfoTime.JSON_PROPERTY_STARTED,
  ShellInfoTime.JSON_PROPERTY_COMPLETED
})
@JsonTypeName("Shell_Info_time")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ShellInfoTime {
  public static final String JSON_PROPERTY_STARTED = "started";
  @jakarta.annotation.Nonnull
  private BigDecimal started;

  public static final String JSON_PROPERTY_COMPLETED = "completed";
  @jakarta.annotation.Nullable
  private BigDecimal completed;

  public ShellInfoTime() {
  }

  public ShellInfoTime started(@jakarta.annotation.Nonnull BigDecimal started) {

    this.started = started;
    return this;
  }

  /**
   * Start time in milliseconds since the Unix epoch
   * @return started
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STARTED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getStarted() {
    return started;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStarted(@jakarta.annotation.Nonnull BigDecimal started) {
    this.started = started;
  }

  public ShellInfoTime completed(@jakarta.annotation.Nullable BigDecimal completed) {

    this.completed = completed;
    return this;
  }

  /**
   * Get completed
   * @return completed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPLETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCompleted() {
    return completed;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPLETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompleted(@jakarta.annotation.Nullable BigDecimal completed) {
    this.completed = completed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShellInfoTime shellInfoTime = (ShellInfoTime) o;
    return Objects.equals(this.started, shellInfoTime.started) &&
        Objects.equals(this.completed, shellInfoTime.completed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(started, completed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShellInfoTime {\n");
    sb.append("    started: ").append(toIndentedString(started)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
