/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StepStartPart
 */
@JsonPropertyOrder({
  StepStartPart.JSON_PROPERTY_ID,
  StepStartPart.JSON_PROPERTY_SESSION_I_D,
  StepStartPart.JSON_PROPERTY_MESSAGE_I_D,
  StepStartPart.JSON_PROPERTY_TYPE,
  StepStartPart.JSON_PROPERTY_SNAPSHOT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class StepStartPart {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_SESSION_I_D = "sessionID";
  @jakarta.annotation.Nonnull
  private String sessionID;

  public static final String JSON_PROPERTY_MESSAGE_I_D = "messageID";
  @jakarta.annotation.Nonnull
  private String messageID;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    STEP_START(String.valueOf("step-start"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_SNAPSHOT = "snapshot";
  @jakarta.annotation.Nullable
  private String snapshot;

  public StepStartPart() {
  }

  public StepStartPart id(@jakarta.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public StepStartPart sessionID(@jakarta.annotation.Nonnull String sessionID) {

    this.sessionID = sessionID;
    return this;
  }

  /**
   * Get sessionID
   * @return sessionID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSessionID() {
    return sessionID;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionID(@jakarta.annotation.Nonnull String sessionID) {
    this.sessionID = sessionID;
  }

  public StepStartPart messageID(@jakarta.annotation.Nonnull String messageID) {

    this.messageID = messageID;
    return this;
  }

  /**
   * Get messageID
   * @return messageID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessageID() {
    return messageID;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageID(@jakarta.annotation.Nonnull String messageID) {
    this.messageID = messageID;
  }

  public StepStartPart type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public StepStartPart snapshot(@jakarta.annotation.Nullable String snapshot) {

    this.snapshot = snapshot;
    return this;
  }

  /**
   * Get snapshot
   * @return snapshot
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSnapshot() {
    return snapshot;
  }


  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSnapshot(@jakarta.annotation.Nullable String snapshot) {
    this.snapshot = snapshot;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StepStartPart stepStartPart = (StepStartPart) o;
    return Objects.equals(this.id, stepStartPart.id) &&
        Objects.equals(this.sessionID, stepStartPart.sessionID) &&
        Objects.equals(this.messageID, stepStartPart.messageID) &&
        Objects.equals(this.type, stepStartPart.type) &&
        Objects.equals(this.snapshot, stepStartPart.snapshot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sessionID, messageID, type, snapshot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StepStartPart {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
    sb.append("    messageID: ").append(toIndentedString(messageID)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    snapshot: ").append(toIndentedString(snapshot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
