/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StructuredOutputErrorData
 */
@JsonPropertyOrder({
  StructuredOutputErrorData.JSON_PROPERTY_MESSAGE,
  StructuredOutputErrorData.JSON_PROPERTY_RETRIES
})
@JsonTypeName("StructuredOutputError_data")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class StructuredOutputErrorData {
  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_RETRIES = "retries";
  @jakarta.annotation.Nonnull
  private Integer retries;

  public StructuredOutputErrorData() {
  }

  public StructuredOutputErrorData message(@jakarta.annotation.Nonnull String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }

  public StructuredOutputErrorData retries(@jakarta.annotation.Nonnull Integer retries) {
    
    this.retries = retries;
    return this;
  }

  /**
   * Get retries
   * minimum: 0
   * @return retries
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RETRIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRetries() {
    return retries;
  }


  @JsonProperty(value = JSON_PROPERTY_RETRIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRetries(@jakarta.annotation.Nonnull Integer retries) {
    this.retries = retries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StructuredOutputErrorData structuredOutputErrorData = (StructuredOutputErrorData) o;
    return Objects.equals(this.message, structuredOutputErrorData.message) &&
        Objects.equals(this.retries, structuredOutputErrorData.retries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, retries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StructuredOutputErrorData {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    retries: ").append(toIndentedString(retries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

