/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UnknownError1
 */
@JsonPropertyOrder({
  UnknownError1.JSON_PROPERTY_TAG,
  UnknownError1.JSON_PROPERTY_MESSAGE,
  UnknownError1.JSON_PROPERTY_REF
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class UnknownError1 {
  /**
   * Gets or Sets tag
   */
  public enum TagEnum {
    UNKNOWN_ERROR(String.valueOf("UnknownError"));

    private String value;

    TagEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TagEnum fromValue(String value) {
      for (TagEnum b : TagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TAG = "_tag";
  @jakarta.annotation.Nonnull
  private TagEnum tag;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_REF = "ref";
  @jakarta.annotation.Nullable
  private String ref;

  public UnknownError1() {
  }

  public UnknownError1 tag(@jakarta.annotation.Nonnull TagEnum tag) {

    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TagEnum getTag() {
    return tag;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTag(@jakarta.annotation.Nonnull TagEnum tag) {
    this.tag = tag;
  }

  public UnknownError1 message(@jakarta.annotation.Nonnull String message) {

    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }

  public UnknownError1 ref(@jakarta.annotation.Nullable String ref) {

    this.ref = ref;
    return this;
  }

  /**
   * Get ref
   * @return ref
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRef() {
    return ref;
  }


  @JsonProperty(value = JSON_PROPERTY_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRef(@jakarta.annotation.Nullable String ref) {
    this.ref = ref;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnknownError1 unknownError1 = (UnknownError1) o;
    return Objects.equals(this.tag, unknownError1.tag) &&
        Objects.equals(this.message, unknownError1.message) &&
        Objects.equals(this.ref, unknownError1.ref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, message, ref);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnknownError1 {\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
