-- 只有当表不存在时才创建
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'scheduled_tasks') THEN
        create table scheduled_tasks (
            id bigint generated by default as identity primary key,
            task_key varchar(128) not null unique,
            name varchar(255) not null,
            cron_expression varchar(255) not null,
            enabled boolean not null default true,
            lock_ttl_seconds bigint not null,
            next_fire_at timestamp,
            registration_status varchar(32) not null,
            trace_id varchar(128) not null,
            created_at timestamp not null,
            updated_at timestamp not null,
            constraint chk_scheduled_tasks_lock_ttl check (lock_ttl_seconds > 0)
        );
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'scheduled_task_plans') THEN
        create table scheduled_task_plans (
            id bigint generated by default as identity primary key,
            plan_id varchar(128) not null unique,
            task_key varchar(128) not null,
            owner_user_id varchar(128) not null,
            cron_expression varchar(255) not null,
            payload_json text not null,
            enabled boolean not null default true,
            next_fire_at timestamp,
            trace_id varchar(128) not null,
            created_at timestamp not null,
            updated_at timestamp not null,
            constraint fk_scheduled_task_plans_task foreign key (task_key) references scheduled_tasks(task_key),
            constraint fk_scheduled_task_plans_owner foreign key (owner_user_id) references users(user_id)
        );
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'scheduled_task_runs') THEN
        create table scheduled_task_runs (
            id bigint generated by default as identity primary key,
            task_run_id varchar(128) not null unique,
            task_key varchar(128) not null,
            plan_id varchar(128),
            trigger_type varchar(32) not null,
            status varchar(32) not null,
            requested_by_user_id varchar(128),
            scheduled_fire_at timestamp not null,
            started_at timestamp,
            ended_at timestamp,
            owner_instance_id varchar(255),
            skip_reason varchar(255),
            error_code varchar(128),
            error_message text,
            result_json text not null,
            trace_id varchar(128) not null,
            created_at timestamp not null,
            updated_at timestamp not null,
            constraint fk_scheduled_task_runs_task foreign key (task_key) references scheduled_tasks(task_key),
            constraint fk_scheduled_task_runs_plan foreign key (plan_id) references scheduled_task_plans(plan_id),
            constraint fk_scheduled_task_runs_request_user foreign key (requested_by_user_id) references users(user_id)
        );
    END IF;
END $$;

-- 只有当列不存在时才添加列
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'source_type') THEN
        alter table sessions add column source_type varchar(32) not null default 'MANUAL';
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'source_ref_id') THEN
        alter table sessions add column source_ref_id varchar(128);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sessions' AND column_name = 'created_by_user_id') THEN
        alter table sessions add column created_by_user_id varchar(128);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sessions_created_by_user') THEN
        alter table sessions
            add constraint fk_sessions_created_by_user foreign key (created_by_user_id) references users(user_id);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'runs' AND column_name = 'source_type') THEN
        alter table runs add column source_type varchar(32) not null default 'MANUAL';
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'runs' AND column_name = 'source_ref_id') THEN
        alter table runs add column source_ref_id varchar(128);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'runs' AND column_name = 'triggered_by_user_id') THEN
        alter table runs add column triggered_by_user_id varchar(128);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_runs_triggered_by_user') THEN
        alter table runs
            add constraint fk_runs_triggered_by_user foreign key (triggered_by_user_id) references users(user_id);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'session_messages' AND column_name = 'source_type') THEN
        alter table session_messages add column source_type varchar(32) not null default 'MANUAL';
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'session_messages' AND column_name = 'source_ref_id') THEN
        alter table session_messages add column source_ref_id varchar(128);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'session_messages' AND column_name = 'sender_user_id') THEN
        alter table session_messages add column sender_user_id varchar(128);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_messages_sender_user') THEN
        alter table session_messages
            add constraint fk_session_messages_sender_user foreign key (sender_user_id) references users(user_id);
    END IF;
END $$;

-- 只有当索引不存在时才创建索引
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_scheduled_tasks_due') THEN
        create index idx_scheduled_tasks_due on scheduled_tasks(enabled, registration_status, next_fire_at);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_scheduled_task_plans_owner') THEN
        create index idx_scheduled_task_plans_owner on scheduled_task_plans(owner_user_id, enabled, next_fire_at);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_scheduled_task_runs_task_status') THEN
        create index idx_scheduled_task_runs_task_status on scheduled_task_runs(task_key, status, updated_at);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_scheduled_task_runs_trigger_status') THEN
        create index idx_scheduled_task_runs_trigger_status on scheduled_task_runs(trigger_type, status, scheduled_fire_at);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_scheduled_task_runs_request_user') THEN
        create index idx_scheduled_task_runs_request_user on scheduled_task_runs(requested_by_user_id, updated_at);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_sessions_source') THEN
        create index idx_sessions_source on sessions(source_type, source_ref_id);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_runs_source') THEN
        create index idx_runs_source on runs(source_type, source_ref_id);
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_session_messages_source') THEN
        create index idx_session_messages_source on session_messages(source_type, source_ref_id);
    END IF;
END $$;
