alter table runs add column if not exists agent_id varchar(64);
alter table runs add column if not exists model_id varchar(255);

create index if not exists idx_runs_analytics_user_time on runs(triggered_by_user_id, updated_at, status);
create index if not exists idx_runs_analytics_created_time on runs(created_at, status, triggered_by_user_id);
create index if not exists idx_runs_analytics_agent_model_time on runs(agent_id, model_id, updated_at);
create index if not exists idx_sessions_analytics_creator_time on sessions(created_by_user_id, created_at);
create index if not exists idx_session_messages_analytics_sender_time on session_messages(sender_user_id, role, created_at);
create index if not exists idx_run_events_analytics_type_time on run_events(type, occurred_at);

comment on column runs.agent_id is '运行使用的业务Agent标识快照，用于运营分析过滤';
comment on column runs.model_id is '运行使用的模型标识快照，用于运营分析过滤';

create table if not exists ai_message_feedbacks (
    id bigint generated by default as identity primary key,
    feedback_id varchar(128) not null unique,
    user_id varchar(128) not null,
    session_id varchar(128) not null,
    run_id varchar(128),
    message_id varchar(128) not null,
    rating varchar(16) not null,
    reason_code varchar(64),
    comment varchar(300),
    organization varchar(255),
    rd_department varchar(255),
    department varchar(255),
    trace_id varchar(128) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_ai_feedback_user_message unique (user_id, message_id),
    constraint fk_ai_feedback_user foreign key (user_id) references users(user_id),
    constraint fk_ai_feedback_session foreign key (session_id) references sessions(session_id),
    constraint fk_ai_feedback_run foreign key (run_id) references runs(run_id),
    constraint fk_ai_feedback_message foreign key (message_id) references session_messages(message_id),
    constraint chk_ai_feedback_rating check (rating in ('POSITIVE', 'NEGATIVE')),
    constraint chk_ai_feedback_reason check (
        reason_code is null or reason_code in (
            'WRONG_ANSWER',
            'NOT_HELPFUL',
            'DID_NOT_FOLLOW_INSTRUCTION',
            'CODE_QUALITY_LOW',
            'TEST_RESULT_BAD',
            'TOO_SLOW',
            'TOO_VERBOSE',
            'TOO_SHORT',
            'OTHER'
        )
    )
);

create index if not exists idx_ai_feedback_time on ai_message_feedbacks(created_at);
create index if not exists idx_ai_feedback_org_time on ai_message_feedbacks(organization, rd_department, department, created_at);
create index if not exists idx_ai_feedback_run on ai_message_feedbacks(run_id);

comment on table ai_message_feedbacks is 'AI回复满意度反馈表';
comment on column ai_message_feedbacks.feedback_id is '反馈业务ID，格式如fb_xxx';
comment on column ai_message_feedbacks.user_id is '提交反馈的用户ID';
comment on column ai_message_feedbacks.session_id is '反馈消息所属会话ID';
comment on column ai_message_feedbacks.run_id is '反馈消息关联运行ID，可为空兼容历史消息';
comment on column ai_message_feedbacks.message_id is '被反馈的assistant消息ID';
comment on column ai_message_feedbacks.rating is '反馈评分：POSITIVE满意，NEGATIVE不满意';
comment on column ai_message_feedbacks.reason_code is '不满意原因编码';
comment on column ai_message_feedbacks.comment is '用户补充说明，最多300字';
comment on column ai_message_feedbacks.organization is '反馈提交时用户所属机构快照';
comment on column ai_message_feedbacks.rd_department is '反馈提交时用户所属研发部快照';
comment on column ai_message_feedbacks.department is '反馈提交时用户所属部门快照';

create table if not exists analytics_user_activity_hourly (
    bucket_start timestamp not null,
    user_id varchar(128) not null,
    username varchar(255),
    organization varchar(255),
    rd_department varchar(255),
    department varchar(255),
    workspace_id varchar(128) not null,
    agent_id varchar(64) not null,
    model_id varchar(255) not null,
    login_count bigint not null default 0,
    session_count bigint not null default 0,
    active_session_count bigint not null default 0,
    empty_session_count bigint not null default 0,
    continuous_session_count bigint not null default 0,
    user_message_count bigint not null default 0,
    assistant_message_count bigint not null default 0,
    run_count bigint not null default 0,
    succeeded_run_count bigint not null default 0,
    failed_run_count bigint not null default 0,
    cancelled_run_count bigint not null default 0,
    active_termination_count bigint not null default 0,
    valid_interaction_count bigint not null default 0,
    positive_feedback_count bigint not null default 0,
    negative_feedback_count bigint not null default 0,
    diff_proposed_count bigint not null default 0,
    diff_accepted_count bigint not null default 0,
    diff_rejected_count bigint not null default 0,
    tokens_input bigint not null default 0,
    tokens_output bigint not null default 0,
    tokens_reasoning bigint not null default 0,
    tokens_total bigint not null default 0,
    duration_total_ms bigint not null default 0,
    duration_run_count bigint not null default 0,
    first_activity_at timestamp,
    last_activity_at timestamp,
    updated_at timestamp not null,
    primary key (bucket_start, user_id, workspace_id, agent_id, model_id)
);

create table if not exists analytics_user_activity_daily (
    activity_date date not null,
    user_id varchar(128) not null,
    username varchar(255),
    organization varchar(255),
    rd_department varchar(255),
    department varchar(255),
    workspace_id varchar(128) not null,
    agent_id varchar(64) not null,
    model_id varchar(255) not null,
    login_count bigint not null default 0,
    session_count bigint not null default 0,
    active_session_count bigint not null default 0,
    empty_session_count bigint not null default 0,
    continuous_session_count bigint not null default 0,
    user_message_count bigint not null default 0,
    assistant_message_count bigint not null default 0,
    run_count bigint not null default 0,
    succeeded_run_count bigint not null default 0,
    failed_run_count bigint not null default 0,
    cancelled_run_count bigint not null default 0,
    active_termination_count bigint not null default 0,
    valid_interaction_count bigint not null default 0,
    positive_feedback_count bigint not null default 0,
    negative_feedback_count bigint not null default 0,
    diff_proposed_count bigint not null default 0,
    diff_accepted_count bigint not null default 0,
    diff_rejected_count bigint not null default 0,
    tokens_input bigint not null default 0,
    tokens_output bigint not null default 0,
    tokens_reasoning bigint not null default 0,
    tokens_total bigint not null default 0,
    duration_total_ms bigint not null default 0,
    duration_run_count bigint not null default 0,
    first_activity_at timestamp,
    last_activity_at timestamp,
    updated_at timestamp not null,
    primary key (activity_date, user_id, workspace_id, agent_id, model_id)
);

create index if not exists idx_analytics_hourly_org_bucket on analytics_user_activity_hourly(organization, rd_department, department, bucket_start);
create index if not exists idx_analytics_daily_org_date on analytics_user_activity_daily(organization, rd_department, department, activity_date);

comment on table analytics_user_activity_hourly is '用户运营分析小时汇总表，API只读该类汇总表';
comment on table analytics_user_activity_daily is '用户运营分析日汇总表，API只读该类汇总表';
comment on column analytics_user_activity_hourly.tokens_total is 'input+output+reasoning token总量，不包含cache和成本';
comment on column analytics_user_activity_daily.tokens_total is 'input+output+reasoning token总量，不包含cache和成本';

create table if not exists analytics_run_duration_histogram_hourly (
    bucket_start timestamp not null,
    organization varchar(255) not null,
    rd_department varchar(255) not null,
    department varchar(255) not null,
    workspace_id varchar(128) not null,
    agent_id varchar(64) not null,
    model_id varchar(255) not null,
    le_ms bigint not null,
    run_count bigint not null default 0,
    updated_at timestamp not null,
    primary key (bucket_start, organization, rd_department, department, workspace_id, agent_id, model_id, le_ms)
);

comment on table analytics_run_duration_histogram_hourly is 'Run耗时小时直方图汇总表，用于近似计算p95';
comment on column analytics_run_duration_histogram_hourly.le_ms is '直方图桶上界毫秒，9223372036854775807 表示正无穷';

create table if not exists analytics_rollup_watermarks (
    job_name varchar(128) primary key,
    watermark_at timestamp,
    generated_at timestamp,
    status varchar(16) not null,
    message varchar(500),
    trace_id varchar(128),
    updated_at timestamp not null,
    constraint chk_analytics_watermark_status check (status in ('FRESH', 'STALE', 'FAILED'))
);

create table if not exists analytics_rollup_job_runs (
    id bigint generated by default as identity primary key,
    job_run_id varchar(128) not null unique,
    job_name varchar(128) not null,
    status varchar(16) not null,
    started_at timestamp not null,
    finished_at timestamp,
    message varchar(500),
    trace_id varchar(128) not null,
    constraint chk_analytics_job_status check (status in ('RUNNING', 'SUCCEEDED', 'FAILED'))
);

create table if not exists analytics_job_locks (
    lock_name varchar(128) primary key,
    owner_id varchar(128) not null,
    locked_until timestamp not null,
    updated_at timestamp not null
);

comment on table analytics_rollup_watermarks is '运营分析汇总水位表';
comment on table analytics_rollup_job_runs is '运营分析汇总任务运行记录表';
comment on table analytics_job_locks is '运营分析任务数据库互斥锁表';
