/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ApiAuth;
import com.example.opencode.sdk.model.OAuth;
import com.example.opencode.sdk.model.WellKnownAuth;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Auth
 */
@JsonPropertyOrder({
  Auth.JSON_PROPERTY_TYPE,
  Auth.JSON_PROPERTY_REFRESH,
  Auth.JSON_PROPERTY_ACCESS,
  Auth.JSON_PROPERTY_EXPIRES,
  Auth.JSON_PROPERTY_ACCOUNT_ID,
  Auth.JSON_PROPERTY_ENTERPRISE_URL,
  Auth.JSON_PROPERTY_KEY,
  Auth.JSON_PROPERTY_METADATA,
  Auth.JSON_PROPERTY_TOKEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class Auth {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    OAUTH(String.valueOf("oauth")),
    
    API(String.valueOf("api")),
    
    WELLKNOWN(String.valueOf("wellknown"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_REFRESH = "refresh";
  @jakarta.annotation.Nonnull
  private String refresh;

  public static final String JSON_PROPERTY_ACCESS = "access";
  @jakarta.annotation.Nonnull
  private String access;

  public static final String JSON_PROPERTY_EXPIRES = "expires";
  @jakarta.annotation.Nonnull
  private Integer expires;

  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @jakarta.annotation.Nullable
  private String accountId;

  public static final String JSON_PROPERTY_ENTERPRISE_URL = "enterpriseUrl";
  @jakarta.annotation.Nullable
  private String enterpriseUrl;

  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Map<String, String> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_TOKEN = "token";
  @jakarta.annotation.Nonnull
  private String token;

  public Auth() {
  }

  public Auth type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public Auth refresh(@jakarta.annotation.Nonnull String refresh) {
    
    this.refresh = refresh;
    return this;
  }

  /**
   * Get refresh
   * @return refresh
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REFRESH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRefresh() {
    return refresh;
  }


  @JsonProperty(value = JSON_PROPERTY_REFRESH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRefresh(@jakarta.annotation.Nonnull String refresh) {
    this.refresh = refresh;
  }

  public Auth access(@jakarta.annotation.Nonnull String access) {
    
    this.access = access;
    return this;
  }

  /**
   * Get access
   * @return access
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccess() {
    return access;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccess(@jakarta.annotation.Nonnull String access) {
    this.access = access;
  }

  public Auth expires(@jakarta.annotation.Nonnull Integer expires) {
    
    this.expires = expires;
    return this;
  }

  /**
   * Get expires
   * minimum: 0
   * @return expires
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getExpires() {
    return expires;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpires(@jakarta.annotation.Nonnull Integer expires) {
    this.expires = expires;
  }

  public Auth accountId(@jakarta.annotation.Nullable String accountId) {
    
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountId() {
    return accountId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(@jakarta.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }

  public Auth enterpriseUrl(@jakarta.annotation.Nullable String enterpriseUrl) {
    
    this.enterpriseUrl = enterpriseUrl;
    return this;
  }

  /**
   * Get enterpriseUrl
   * @return enterpriseUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTERPRISE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEnterpriseUrl() {
    return enterpriseUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTERPRISE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnterpriseUrl(@jakarta.annotation.Nullable String enterpriseUrl) {
    this.enterpriseUrl = enterpriseUrl;
  }

  public Auth key(@jakarta.annotation.Nonnull String key) {
    
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@jakarta.annotation.Nonnull String key) {
    this.key = key;
  }

  public Auth metadata(@jakarta.annotation.Nullable Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public Auth putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
  }

  public Auth token(@jakarta.annotation.Nonnull String token) {
    
    this.token = token;
    return this;
  }

  /**
   * Get token
   * @return token
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToken() {
    return token;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToken(@jakarta.annotation.Nonnull String token) {
    this.token = token;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Auth auth = (Auth) o;
    return Objects.equals(this.type, auth.type) &&
        Objects.equals(this.refresh, auth.refresh) &&
        Objects.equals(this.access, auth.access) &&
        Objects.equals(this.expires, auth.expires) &&
        Objects.equals(this.accountId, auth.accountId) &&
        Objects.equals(this.enterpriseUrl, auth.enterpriseUrl) &&
        Objects.equals(this.key, auth.key) &&
        Objects.equals(this.metadata, auth.metadata) &&
        Objects.equals(this.token, auth.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, refresh, access, expires, accountId, enterpriseUrl, key, metadata, token);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Auth {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    refresh: ").append(toIndentedString(refresh)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    enterpriseUrl: ").append(toIndentedString(enterpriseUrl)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

