/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigCommandValue
 */
@JsonPropertyOrder({
  ConfigCommandValue.JSON_PROPERTY_TEMPLATE,
  ConfigCommandValue.JSON_PROPERTY_DESCRIPTION,
  ConfigCommandValue.JSON_PROPERTY_AGENT,
  ConfigCommandValue.JSON_PROPERTY_MODEL,
  ConfigCommandValue.JSON_PROPERTY_VARIANT,
  ConfigCommandValue.JSON_PROPERTY_SUBTASK
})
@JsonTypeName("Config_command_value")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ConfigCommandValue {
  public static final String JSON_PROPERTY_TEMPLATE = "template";
  @jakarta.annotation.Nonnull
  private String template;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_AGENT = "agent";
  @jakarta.annotation.Nullable
  private String agent;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nullable
  private String model;

  public static final String JSON_PROPERTY_VARIANT = "variant";
  @jakarta.annotation.Nullable
  private String variant;

  public static final String JSON_PROPERTY_SUBTASK = "subtask";
  @jakarta.annotation.Nullable
  private Boolean subtask;

  public ConfigCommandValue() {
  }

  public ConfigCommandValue template(@jakarta.annotation.Nonnull String template) {

    this.template = template;
    return this;
  }

  /**
   * Get template
   * @return template
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTemplate() {
    return template;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplate(@jakarta.annotation.Nonnull String template) {
    this.template = template;
  }

  public ConfigCommandValue description(@jakarta.annotation.Nullable String description) {

    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public ConfigCommandValue agent(@jakarta.annotation.Nullable String agent) {

    this.agent = agent;
    return this;
  }

  /**
   * Get agent
   * @return agent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgent(@jakarta.annotation.Nullable String agent) {
    this.agent = agent;
  }

  public ConfigCommandValue model(@jakarta.annotation.Nullable String model) {

    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@jakarta.annotation.Nullable String model) {
    this.model = model;
  }

  public ConfigCommandValue variant(@jakarta.annotation.Nullable String variant) {

    this.variant = variant;
    return this;
  }

  /**
   * Get variant
   * @return variant
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVariant() {
    return variant;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariant(@jakarta.annotation.Nullable String variant) {
    this.variant = variant;
  }

  public ConfigCommandValue subtask(@jakarta.annotation.Nullable Boolean subtask) {

    this.subtask = subtask;
    return this;
  }

  /**
   * Get subtask
   * @return subtask
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBTASK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSubtask() {
    return subtask;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBTASK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubtask(@jakarta.annotation.Nullable Boolean subtask) {
    this.subtask = subtask;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigCommandValue configCommandValue = (ConfigCommandValue) o;
    return Objects.equals(this.template, configCommandValue.template) &&
        Objects.equals(this.description, configCommandValue.description) &&
        Objects.equals(this.agent, configCommandValue.agent) &&
        Objects.equals(this.model, configCommandValue.model) &&
        Objects.equals(this.variant, configCommandValue.variant) &&
        Objects.equals(this.subtask, configCommandValue.subtask);
  }

  @Override
  public int hashCode() {
    return Objects.hash(template, description, agent, model, variant, subtask);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigCommandValue {\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
    sb.append("    subtask: ").append(toIndentedString(subtask)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
