/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ConfigModelEncoded;
import com.example.opencode.sdk.model.ConfigProviderSettings;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigProviderEncoded
 */
@JsonPropertyOrder({
  ConfigProviderEncoded.JSON_PROPERTY_CANONICAL,
  ConfigProviderEncoded.JSON_PROPERTY_NAME,
  ConfigProviderEncoded.JSON_PROPERTY_ENV,
  ConfigProviderEncoded.JSON_PROPERTY_PACKAGE,
  ConfigProviderEncoded.JSON_PROPERTY_SETTINGS,
  ConfigProviderEncoded.JSON_PROPERTY_HEADERS,
  ConfigProviderEncoded.JSON_PROPERTY_BODY,
  ConfigProviderEncoded.JSON_PROPERTY_MODELS
})
@JsonTypeName("Config.ProviderEncoded")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ConfigProviderEncoded {
  public static final String JSON_PROPERTY_CANONICAL = "canonical";
  @jakarta.annotation.Nullable
  private String canonical;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ENV = "env";
  @jakarta.annotation.Nullable
  private List<String> env = new ArrayList<>();

  public static final String JSON_PROPERTY_PACKAGE = "package";
  @jakarta.annotation.Nullable
  private String _package;

  public static final String JSON_PROPERTY_SETTINGS = "settings";
  @jakarta.annotation.Nullable
  private ConfigProviderSettings settings;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @jakarta.annotation.Nullable
  private Map<String, String> headers = new HashMap<>();

  public static final String JSON_PROPERTY_BODY = "body";
  @jakarta.annotation.Nullable
  private Object body;

  public static final String JSON_PROPERTY_MODELS = "models";
  @jakarta.annotation.Nullable
  private Map<String, ConfigModelEncoded> models = new HashMap<>();

  public ConfigProviderEncoded() {
  }

  public ConfigProviderEncoded canonical(@jakarta.annotation.Nullable String canonical) {

    this.canonical = canonical;
    return this;
  }

  /**
   * Get canonical
   * @return canonical
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CANONICAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCanonical() {
    return canonical;
  }


  @JsonProperty(value = JSON_PROPERTY_CANONICAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanonical(@jakarta.annotation.Nullable String canonical) {
    this.canonical = canonical;
  }

  public ConfigProviderEncoded name(@jakarta.annotation.Nullable String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public ConfigProviderEncoded env(@jakarta.annotation.Nullable List<String> env) {

    this.env = env;
    return this;
  }

  public ConfigProviderEncoded addEnvItem(String envItem) {
    if (this.env == null) {
      this.env = new ArrayList<>();
    }
    this.env.add(envItem);
    return this;
  }

  /**
   * Get env
   * @return env
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENV, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getEnv() {
    return env;
  }


  @JsonProperty(value = JSON_PROPERTY_ENV, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnv(@jakarta.annotation.Nullable List<String> env) {
    this.env = env;
  }

  public ConfigProviderEncoded _package(@jakarta.annotation.Nullable String _package) {

    this._package = _package;
    return this;
  }

  /**
   * Get _package
   * @return _package
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PACKAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPackage() {
    return _package;
  }


  @JsonProperty(value = JSON_PROPERTY_PACKAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackage(@jakarta.annotation.Nullable String _package) {
    this._package = _package;
  }

  public ConfigProviderEncoded settings(@jakarta.annotation.Nullable ConfigProviderSettings settings) {

    this.settings = settings;
    return this;
  }

  /**
   * Get settings
   * @return settings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigProviderSettings getSettings() {
    return settings;
  }


  @JsonProperty(value = JSON_PROPERTY_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSettings(@jakarta.annotation.Nullable ConfigProviderSettings settings) {
    this.settings = settings;
  }

  public ConfigProviderEncoded headers(@jakarta.annotation.Nullable Map<String, String> headers) {

    this.headers = headers;
    return this;
  }

  public ConfigProviderEncoded putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeaders(@jakarta.annotation.Nullable Map<String, String> headers) {
    this.headers = headers;
  }

  public ConfigProviderEncoded body(@jakarta.annotation.Nullable Object body) {

    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(@jakarta.annotation.Nullable Object body) {
    this.body = body;
  }

  public ConfigProviderEncoded models(@jakarta.annotation.Nullable Map<String, ConfigModelEncoded> models) {

    this.models = models;
    return this;
  }

  public ConfigProviderEncoded putModelsItem(String key, ConfigModelEncoded modelsItem) {
    if (this.models == null) {
      this.models = new HashMap<>();
    }
    this.models.put(key, modelsItem);
    return this;
  }

  /**
   * Get models
   * @return models
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, ConfigModelEncoded> getModels() {
    return models;
  }


  @JsonProperty(value = JSON_PROPERTY_MODELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModels(@jakarta.annotation.Nullable Map<String, ConfigModelEncoded> models) {
    this.models = models;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigProviderEncoded configProviderEncoded = (ConfigProviderEncoded) o;
    return Objects.equals(this.canonical, configProviderEncoded.canonical) &&
        Objects.equals(this.name, configProviderEncoded.name) &&
        Objects.equals(this.env, configProviderEncoded.env) &&
        Objects.equals(this._package, configProviderEncoded._package) &&
        Objects.equals(this.settings, configProviderEncoded.settings) &&
        Objects.equals(this.headers, configProviderEncoded.headers) &&
        Objects.equals(this.body, configProviderEncoded.body) &&
        Objects.equals(this.models, configProviderEncoded.models);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canonical, name, env, _package, settings, headers, body, models);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigProviderEncoded {\n");
    sb.append("    canonical: ").append(toIndentedString(canonical)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    models: ").append(toIndentedString(models)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
