/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigPluginEntryEncoded
 */
@JsonPropertyOrder({
  ConfigPluginEntryEncoded.JSON_PROPERTY_PACKAGE,
  ConfigPluginEntryEncoded.JSON_PROPERTY_OPTIONS
})
@JsonTypeName("Config.Plugin.EntryEncoded")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ConfigPluginEntryEncoded {
  public static final String JSON_PROPERTY_PACKAGE = "package";
  @jakarta.annotation.Nonnull
  private String _package;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @jakarta.annotation.Nullable
  private Object options;

  public ConfigPluginEntryEncoded() {
  }

  public ConfigPluginEntryEncoded _package(@jakarta.annotation.Nonnull String _package) {

    this._package = _package;
    return this;
  }

  /**
   * Get _package
   * @return _package
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PACKAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPackage() {
    return _package;
  }


  @JsonProperty(value = JSON_PROPERTY_PACKAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPackage(@jakarta.annotation.Nonnull String _package) {
    this._package = _package;
  }

  public ConfigPluginEntryEncoded options(@jakarta.annotation.Nullable Object options) {

    this.options = options;
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getOptions() {
    return options;
  }


  @JsonProperty(value = JSON_PROPERTY_OPTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOptions(@jakarta.annotation.Nullable Object options) {
    this.options = options;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigPluginEntryEncoded configPluginEntryEncoded = (ConfigPluginEntryEncoded) o;
    return Objects.equals(this._package, configPluginEntryEncoded._package) &&
        Objects.equals(this.options, configPluginEntryEncoded.options);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_package, options);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigPluginEntryEncoded {\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
