/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.EventCatalogUpdated;
import com.example.opencode.sdk.model.EventCommandExecuted;
import com.example.opencode.sdk.model.EventFileEdited;
import com.example.opencode.sdk.model.EventFileWatcherUpdated;
import com.example.opencode.sdk.model.EventGlobalDisposed;
import com.example.opencode.sdk.model.EventInstallationUpdateAvailable;
import com.example.opencode.sdk.model.EventInstallationUpdated;
import com.example.opencode.sdk.model.EventIntegrationUpdated;
import com.example.opencode.sdk.model.EventLspUpdated;
import com.example.opencode.sdk.model.EventMcpBrowserOpenFailed;
import com.example.opencode.sdk.model.EventMcpToolsChanged;
import com.example.opencode.sdk.model.EventMessagePartDelta;
import com.example.opencode.sdk.model.EventMessagePartRemoved;
import com.example.opencode.sdk.model.EventMessagePartUpdated;
import com.example.opencode.sdk.model.EventMessageRemoved;
import com.example.opencode.sdk.model.EventMessageUpdated;
import com.example.opencode.sdk.model.EventModelsDevRefreshed;
import com.example.opencode.sdk.model.EventPermissionAsked;
import com.example.opencode.sdk.model.EventPermissionReplied;
import com.example.opencode.sdk.model.EventPermissionV2Asked;
import com.example.opencode.sdk.model.EventPermissionV2Replied;
import com.example.opencode.sdk.model.EventPluginAdded;
import com.example.opencode.sdk.model.EventProjectDirectoriesUpdated;
import com.example.opencode.sdk.model.EventProjectUpdated;
import com.example.opencode.sdk.model.EventPtyCreated;
import com.example.opencode.sdk.model.EventPtyDeleted;
import com.example.opencode.sdk.model.EventPtyExited;
import com.example.opencode.sdk.model.EventPtyUpdated;
import com.example.opencode.sdk.model.EventQuestionAsked;
import com.example.opencode.sdk.model.EventQuestionRejected;
import com.example.opencode.sdk.model.EventQuestionReplied;
import com.example.opencode.sdk.model.EventQuestionV2Asked;
import com.example.opencode.sdk.model.EventQuestionV2Rejected;
import com.example.opencode.sdk.model.EventQuestionV2Replied;
import com.example.opencode.sdk.model.EventReferenceUpdated;
import com.example.opencode.sdk.model.EventServerConnected;
import com.example.opencode.sdk.model.EventServerInstanceDisposed;
import com.example.opencode.sdk.model.EventServerInstanceDisposedProperties;
import com.example.opencode.sdk.model.EventSessionCompacted;
import com.example.opencode.sdk.model.EventSessionCreated;
import com.example.opencode.sdk.model.EventSessionDeleted;
import com.example.opencode.sdk.model.EventSessionDiff;
import com.example.opencode.sdk.model.EventSessionError;
import com.example.opencode.sdk.model.EventSessionIdle;
import com.example.opencode.sdk.model.EventSessionNextAgentSwitched;
import com.example.opencode.sdk.model.EventSessionNextCompactionDelta;
import com.example.opencode.sdk.model.EventSessionNextCompactionEnded;
import com.example.opencode.sdk.model.EventSessionNextCompactionStarted;
import com.example.opencode.sdk.model.EventSessionNextContextUpdated;
import com.example.opencode.sdk.model.EventSessionNextInterruptRequested;
import com.example.opencode.sdk.model.EventSessionNextModelSwitched;
import com.example.opencode.sdk.model.EventSessionNextMoved;
import com.example.opencode.sdk.model.EventSessionNextPromptAdmitted;
import com.example.opencode.sdk.model.EventSessionNextPromptPromoted;
import com.example.opencode.sdk.model.EventSessionNextPrompted;
import com.example.opencode.sdk.model.EventSessionNextReasoningDelta;
import com.example.opencode.sdk.model.EventSessionNextReasoningEnded;
import com.example.opencode.sdk.model.EventSessionNextReasoningStarted;
import com.example.opencode.sdk.model.EventSessionNextRetried;
import com.example.opencode.sdk.model.EventSessionNextShellEnded;
import com.example.opencode.sdk.model.EventSessionNextShellStarted;
import com.example.opencode.sdk.model.EventSessionNextStepEnded;
import com.example.opencode.sdk.model.EventSessionNextStepFailed;
import com.example.opencode.sdk.model.EventSessionNextStepStarted;
import com.example.opencode.sdk.model.EventSessionNextSynthetic;
import com.example.opencode.sdk.model.EventSessionNextTextDelta;
import com.example.opencode.sdk.model.EventSessionNextTextEnded;
import com.example.opencode.sdk.model.EventSessionNextTextStarted;
import com.example.opencode.sdk.model.EventSessionNextToolCalled;
import com.example.opencode.sdk.model.EventSessionNextToolFailed;
import com.example.opencode.sdk.model.EventSessionNextToolInputDelta;
import com.example.opencode.sdk.model.EventSessionNextToolInputEnded;
import com.example.opencode.sdk.model.EventSessionNextToolInputStarted;
import com.example.opencode.sdk.model.EventSessionNextToolProgress;
import com.example.opencode.sdk.model.EventSessionNextToolSuccess;
import com.example.opencode.sdk.model.EventSessionStatus;
import com.example.opencode.sdk.model.EventSessionUpdated;
import com.example.opencode.sdk.model.EventTodoUpdated;
import com.example.opencode.sdk.model.EventTuiCommandExecute;
import com.example.opencode.sdk.model.EventTuiPromptAppend;
import com.example.opencode.sdk.model.EventTuiSessionSelect;
import com.example.opencode.sdk.model.EventTuiToastShow;
import com.example.opencode.sdk.model.EventVcsBranchUpdated;
import com.example.opencode.sdk.model.EventWorkspaceFailed;
import com.example.opencode.sdk.model.EventWorkspaceReady;
import com.example.opencode.sdk.model.EventWorkspaceStatus;
import com.example.opencode.sdk.model.EventWorktreeFailed;
import com.example.opencode.sdk.model.EventWorktreeReady;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Event
 */
@JsonPropertyOrder({
  Event.JSON_PROPERTY_ID,
  Event.JSON_PROPERTY_TYPE,
  Event.JSON_PROPERTY_PROPERTIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class Event {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    PLUGIN_ADDED(String.valueOf("plugin.added")),
    
    INTEGRATION_UPDATED(String.valueOf("integration.updated")),
    
    CATALOG_UPDATED(String.valueOf("catalog.updated")),
    
    INSTALLATION_UPDATED(String.valueOf("installation.updated")),
    
    INSTALLATION_UPDATE_AVAILABLE(String.valueOf("installation.update-available")),
    
    FILE_WATCHER_UPDATED(String.valueOf("file.watcher.updated")),
    
    SESSION_CREATED(String.valueOf("session.created")),
    
    SESSION_UPDATED(String.valueOf("session.updated")),
    
    SESSION_DELETED(String.valueOf("session.deleted")),
    
    MESSAGE_UPDATED(String.valueOf("message.updated")),
    
    MESSAGE_REMOVED(String.valueOf("message.removed")),
    
    MESSAGE_PART_UPDATED(String.valueOf("message.part.updated")),
    
    MESSAGE_PART_REMOVED(String.valueOf("message.part.removed")),
    
    REFERENCE_UPDATED(String.valueOf("reference.updated")),
    
    MODELS_DEV_REFRESHED(String.valueOf("models-dev.refreshed")),
    
    SESSION_NEXT_AGENT_SWITCHED(String.valueOf("session.next.agent.switched")),
    
    SESSION_NEXT_MODEL_SWITCHED(String.valueOf("session.next.model.switched")),
    
    SESSION_NEXT_MOVED(String.valueOf("session.next.moved")),
    
    SESSION_NEXT_PROMPTED(String.valueOf("session.next.prompted")),
    
    SESSION_NEXT_PROMPT_ADMITTED(String.valueOf("session.next.prompt.admitted")),
    
    SESSION_NEXT_PROMPT_PROMOTED(String.valueOf("session.next.prompt.promoted")),
    
    SESSION_NEXT_INTERRUPT_REQUESTED(String.valueOf("session.next.interrupt.requested")),
    
    SESSION_NEXT_CONTEXT_UPDATED(String.valueOf("session.next.context.updated")),
    
    SESSION_NEXT_SYNTHETIC(String.valueOf("session.next.synthetic")),
    
    SESSION_NEXT_SHELL_STARTED(String.valueOf("session.next.shell.started")),
    
    SESSION_NEXT_SHELL_ENDED(String.valueOf("session.next.shell.ended")),
    
    SESSION_NEXT_STEP_STARTED(String.valueOf("session.next.step.started")),
    
    SESSION_NEXT_STEP_ENDED(String.valueOf("session.next.step.ended")),
    
    SESSION_NEXT_STEP_FAILED(String.valueOf("session.next.step.failed")),
    
    SESSION_NEXT_TEXT_STARTED(String.valueOf("session.next.text.started")),
    
    SESSION_NEXT_TEXT_DELTA(String.valueOf("session.next.text.delta")),
    
    SESSION_NEXT_TEXT_ENDED(String.valueOf("session.next.text.ended")),
    
    SESSION_NEXT_REASONING_STARTED(String.valueOf("session.next.reasoning.started")),
    
    SESSION_NEXT_REASONING_DELTA(String.valueOf("session.next.reasoning.delta")),
    
    SESSION_NEXT_REASONING_ENDED(String.valueOf("session.next.reasoning.ended")),
    
    SESSION_NEXT_TOOL_INPUT_STARTED(String.valueOf("session.next.tool.input.started")),
    
    SESSION_NEXT_TOOL_INPUT_DELTA(String.valueOf("session.next.tool.input.delta")),
    
    SESSION_NEXT_TOOL_INPUT_ENDED(String.valueOf("session.next.tool.input.ended")),
    
    SESSION_NEXT_TOOL_CALLED(String.valueOf("session.next.tool.called")),
    
    SESSION_NEXT_TOOL_PROGRESS(String.valueOf("session.next.tool.progress")),
    
    SESSION_NEXT_TOOL_SUCCESS(String.valueOf("session.next.tool.success")),
    
    SESSION_NEXT_TOOL_FAILED(String.valueOf("session.next.tool.failed")),
    
    SESSION_NEXT_RETRIED(String.valueOf("session.next.retried")),
    
    SESSION_NEXT_COMPACTION_STARTED(String.valueOf("session.next.compaction.started")),
    
    SESSION_NEXT_COMPACTION_DELTA(String.valueOf("session.next.compaction.delta")),
    
    SESSION_NEXT_COMPACTION_ENDED(String.valueOf("session.next.compaction.ended")),
    
    PERMISSION_V2_ASKED(String.valueOf("permission.v2.asked")),
    
    PERMISSION_V2_REPLIED(String.valueOf("permission.v2.replied")),
    
    PERMISSION_ASKED(String.valueOf("permission.asked")),
    
    PERMISSION_REPLIED(String.valueOf("permission.replied")),
    
    MESSAGE_PART_DELTA(String.valueOf("message.part.delta")),
    
    SESSION_DIFF(String.valueOf("session.diff")),
    
    SESSION_ERROR(String.valueOf("session.error")),
    
    TUI_PROMPT_APPEND(String.valueOf("tui.prompt.append")),
    
    TUI_COMMAND_EXECUTE(String.valueOf("tui.command.execute")),
    
    TUI_TOAST_SHOW(String.valueOf("tui.toast.show")),
    
    TUI_SESSION_SELECT(String.valueOf("tui.session.select")),
    
    MCP_TOOLS_CHANGED(String.valueOf("mcp.tools.changed")),
    
    MCP_BROWSER_OPEN_FAILED(String.valueOf("mcp.browser.open.failed")),
    
    LSP_UPDATED(String.valueOf("lsp.updated")),
    
    FILE_EDITED(String.valueOf("file.edited")),
    
    PROJECT_DIRECTORIES_UPDATED(String.valueOf("project.directories.updated")),
    
    PTY_CREATED(String.valueOf("pty.created")),
    
    PTY_UPDATED(String.valueOf("pty.updated")),
    
    PTY_EXITED(String.valueOf("pty.exited")),
    
    PTY_DELETED(String.valueOf("pty.deleted")),
    
    QUESTION_V2_ASKED(String.valueOf("question.v2.asked")),
    
    QUESTION_V2_REPLIED(String.valueOf("question.v2.replied")),
    
    QUESTION_V2_REJECTED(String.valueOf("question.v2.rejected")),
    
    TODO_UPDATED(String.valueOf("todo.updated")),
    
    QUESTION_ASKED(String.valueOf("question.asked")),
    
    QUESTION_REPLIED(String.valueOf("question.replied")),
    
    QUESTION_REJECTED(String.valueOf("question.rejected")),
    
    COMMAND_EXECUTED(String.valueOf("command.executed")),
    
    SESSION_STATUS(String.valueOf("session.status")),
    
    SESSION_IDLE(String.valueOf("session.idle")),
    
    SESSION_COMPACTED(String.valueOf("session.compacted")),
    
    PROJECT_UPDATED(String.valueOf("project.updated")),
    
    VCS_BRANCH_UPDATED(String.valueOf("vcs.branch.updated")),
    
    WORKSPACE_READY(String.valueOf("workspace.ready")),
    
    WORKSPACE_FAILED(String.valueOf("workspace.failed")),
    
    WORKSPACE_STATUS(String.valueOf("workspace.status")),
    
    WORKTREE_READY(String.valueOf("worktree.ready")),
    
    WORKTREE_FAILED(String.valueOf("worktree.failed")),
    
    SERVER_CONNECTED(String.valueOf("server.connected")),
    
    GLOBAL_DISPOSED(String.valueOf("global.disposed")),
    
    SERVER_INSTANCE_DISPOSED(String.valueOf("server.instance.disposed"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @jakarta.annotation.Nonnull
  private EventServerInstanceDisposedProperties properties;

  public Event() {
  }

  public Event id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public Event type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public Event properties(@jakarta.annotation.Nonnull EventServerInstanceDisposedProperties properties) {
    
    this.properties = properties;
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROPERTIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EventServerInstanceDisposedProperties getProperties() {
    return properties;
  }


  @JsonProperty(value = JSON_PROPERTY_PROPERTIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProperties(@jakarta.annotation.Nonnull EventServerInstanceDisposedProperties properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.id, event.id) &&
        Objects.equals(this.type, event.type) &&
        Objects.equals(this.properties, event.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, properties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

