/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ExperimentalMigrationV1Status200ResponseAnyOf1Progress
 */
@JsonPropertyOrder({
  ExperimentalMigrationV1Status200ResponseAnyOf1Progress.JSON_PROPERTY_LABEL,
  ExperimentalMigrationV1Status200ResponseAnyOf1Progress.JSON_PROPERTY_NUMERATOR,
  ExperimentalMigrationV1Status200ResponseAnyOf1Progress.JSON_PROPERTY_DENOMINATOR
})
@JsonTypeName("experimental_migration_v1_status_200_response_anyOf_1_progress")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ExperimentalMigrationV1Status200ResponseAnyOf1Progress {
  public static final String JSON_PROPERTY_LABEL = "label";
  @jakarta.annotation.Nullable
  private String label;

  public static final String JSON_PROPERTY_NUMERATOR = "numerator";
  @jakarta.annotation.Nullable
  private Integer numerator;

  public static final String JSON_PROPERTY_DENOMINATOR = "denominator";
  @jakarta.annotation.Nullable
  private Integer denominator;

  public ExperimentalMigrationV1Status200ResponseAnyOf1Progress() {
  }

  public ExperimentalMigrationV1Status200ResponseAnyOf1Progress label(@jakarta.annotation.Nullable String label) {

    this.label = label;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return label
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLabel() {
    return label;
  }


  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabel(@jakarta.annotation.Nullable String label) {
    this.label = label;
  }

  public ExperimentalMigrationV1Status200ResponseAnyOf1Progress numerator(@jakarta.annotation.Nullable Integer numerator) {

    this.numerator = numerator;
    return this;
  }

  /**
   * Get numerator
   * minimum: 0
   * @return numerator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUMERATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumerator() {
    return numerator;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMERATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumerator(@jakarta.annotation.Nullable Integer numerator) {
    this.numerator = numerator;
  }

  public ExperimentalMigrationV1Status200ResponseAnyOf1Progress denominator(@jakarta.annotation.Nullable Integer denominator) {

    this.denominator = denominator;
    return this;
  }

  /**
   * Get denominator
   * minimum: 0
   * @return denominator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DENOMINATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDenominator() {
    return denominator;
  }


  @JsonProperty(value = JSON_PROPERTY_DENOMINATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDenominator(@jakarta.annotation.Nullable Integer denominator) {
    this.denominator = denominator;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentalMigrationV1Status200ResponseAnyOf1Progress experimentalMigrationV1Status200ResponseAnyOf1Progress = (ExperimentalMigrationV1Status200ResponseAnyOf1Progress) o;
    return Objects.equals(this.label, experimentalMigrationV1Status200ResponseAnyOf1Progress.label) &&
        Objects.equals(this.numerator, experimentalMigrationV1Status200ResponseAnyOf1Progress.numerator) &&
        Objects.equals(this.denominator, experimentalMigrationV1Status200ResponseAnyOf1Progress.denominator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, numerator, denominator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentalMigrationV1Status200ResponseAnyOf1Progress {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    numerator: ").append(toIndentedString(numerator)).append("\n");
    sb.append("    denominator: ").append(toIndentedString(denominator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
