/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Health information
 */
@JsonPropertyOrder({
  GlobalHealth200Response.JSON_PROPERTY_HEALTHY,
  GlobalHealth200Response.JSON_PROPERTY_VERSION
})
@JsonTypeName("global_health_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class GlobalHealth200Response {
  /**
   * Gets or Sets healthy
   */
  public enum HealthyEnum {
    TRUE(Boolean.valueOf("true"));

    private Boolean value;

    HealthyEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static HealthyEnum fromValue(Boolean value) {
      for (HealthyEnum b : HealthyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_HEALTHY = "healthy";
  @jakarta.annotation.Nonnull
  private HealthyEnum healthy;

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nonnull
  private String version;

  public GlobalHealth200Response() {
  }

  public GlobalHealth200Response healthy(@jakarta.annotation.Nonnull HealthyEnum healthy) {
    
    this.healthy = healthy;
    return this;
  }

  /**
   * Get healthy
   * @return healthy
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HEALTHY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public HealthyEnum getHealthy() {
    return healthy;
  }


  @JsonProperty(value = JSON_PROPERTY_HEALTHY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHealthy(@jakarta.annotation.Nonnull HealthyEnum healthy) {
    this.healthy = healthy;
  }

  public GlobalHealth200Response version(@jakarta.annotation.Nonnull String version) {
    
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@jakarta.annotation.Nonnull String version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalHealth200Response globalHealth200Response = (GlobalHealth200Response) o;
    return Objects.equals(this.healthy, globalHealth200Response.healthy) &&
        Objects.equals(this.version, globalHealth200Response.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(healthy, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalHealth200Response {\n");
    sb.append("    healthy: ").append(toIndentedString(healthy)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

