/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.QuestionInfo;
import com.example.opencode.sdk.model.QuestionTool;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GlobalEventPayloadAnyOf76Properties
 */
@JsonPropertyOrder({
  GlobalEventPayloadAnyOf76Properties.JSON_PROPERTY_ID,
  GlobalEventPayloadAnyOf76Properties.JSON_PROPERTY_SESSION_I_D,
  GlobalEventPayloadAnyOf76Properties.JSON_PROPERTY_QUESTIONS,
  GlobalEventPayloadAnyOf76Properties.JSON_PROPERTY_TOOL
})
@JsonTypeName("GlobalEvent_payload_anyOf_76_properties")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GlobalEventPayloadAnyOf76Properties {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_SESSION_I_D = "sessionID";
  @jakarta.annotation.Nonnull
  private String sessionID;

  public static final String JSON_PROPERTY_QUESTIONS = "questions";
  @jakarta.annotation.Nonnull
  private List<QuestionInfo> questions = new ArrayList<>();

  public static final String JSON_PROPERTY_TOOL = "tool";
  @jakarta.annotation.Nullable
  private QuestionTool tool;

  public GlobalEventPayloadAnyOf76Properties() {
  }

  public GlobalEventPayloadAnyOf76Properties id(@jakarta.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public GlobalEventPayloadAnyOf76Properties sessionID(@jakarta.annotation.Nonnull String sessionID) {

    this.sessionID = sessionID;
    return this;
  }

  /**
   * Get sessionID
   * @return sessionID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSessionID() {
    return sessionID;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSessionID(@jakarta.annotation.Nonnull String sessionID) {
    this.sessionID = sessionID;
  }

  public GlobalEventPayloadAnyOf76Properties questions(@jakarta.annotation.Nonnull List<QuestionInfo> questions) {

    this.questions = questions;
    return this;
  }

  public GlobalEventPayloadAnyOf76Properties addQuestionsItem(QuestionInfo questionsItem) {
    if (this.questions == null) {
      this.questions = new ArrayList<>();
    }
    this.questions.add(questionsItem);
    return this;
  }

  /**
   * Questions to ask
   * @return questions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUESTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<QuestionInfo> getQuestions() {
    return questions;
  }


  @JsonProperty(value = JSON_PROPERTY_QUESTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuestions(@jakarta.annotation.Nonnull List<QuestionInfo> questions) {
    this.questions = questions;
  }

  public GlobalEventPayloadAnyOf76Properties tool(@jakarta.annotation.Nullable QuestionTool tool) {

    this.tool = tool;
    return this;
  }

  /**
   * Get tool
   * @return tool
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuestionTool getTool() {
    return tool;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTool(@jakarta.annotation.Nullable QuestionTool tool) {
    this.tool = tool;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalEventPayloadAnyOf76Properties globalEventPayloadAnyOf76Properties = (GlobalEventPayloadAnyOf76Properties) o;
    return Objects.equals(this.id, globalEventPayloadAnyOf76Properties.id) &&
        Objects.equals(this.sessionID, globalEventPayloadAnyOf76Properties.sessionID) &&
        Objects.equals(this.questions, globalEventPayloadAnyOf76Properties.questions) &&
        Objects.equals(this.tool, globalEventPayloadAnyOf76Properties.tool);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sessionID, questions, tool);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalEventPayloadAnyOf76Properties {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
    sb.append("    questions: ").append(toIndentedString(questions)).append("\n");
    sb.append("    tool: ").append(toIndentedString(tool)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
