/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * McpLocalConfigEncodedTimeout
 */
@JsonPropertyOrder({
  McpLocalConfigEncodedTimeout.JSON_PROPERTY_STARTUP,
  McpLocalConfigEncodedTimeout.JSON_PROPERTY_CATALOG,
  McpLocalConfigEncodedTimeout.JSON_PROPERTY_EXECUTION
})
@JsonTypeName("Mcp_LocalConfigEncoded_timeout")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class McpLocalConfigEncodedTimeout {
  public static final String JSON_PROPERTY_STARTUP = "startup";
  @jakarta.annotation.Nullable
  private Integer startup;

  public static final String JSON_PROPERTY_CATALOG = "catalog";
  @jakarta.annotation.Nullable
  private Integer catalog;

  public static final String JSON_PROPERTY_EXECUTION = "execution";
  @jakarta.annotation.Nullable
  private Integer execution;

  public McpLocalConfigEncodedTimeout() {
  }

  public McpLocalConfigEncodedTimeout startup(@jakarta.annotation.Nullable Integer startup) {

    this.startup = startup;
    return this;
  }

  /**
   * Get startup
   * minimum: 0
   * @return startup
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STARTUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStartup() {
    return startup;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartup(@jakarta.annotation.Nullable Integer startup) {
    this.startup = startup;
  }

  public McpLocalConfigEncodedTimeout catalog(@jakarta.annotation.Nullable Integer catalog) {

    this.catalog = catalog;
    return this;
  }

  /**
   * Get catalog
   * minimum: 0
   * @return catalog
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CATALOG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCatalog() {
    return catalog;
  }


  @JsonProperty(value = JSON_PROPERTY_CATALOG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCatalog(@jakarta.annotation.Nullable Integer catalog) {
    this.catalog = catalog;
  }

  public McpLocalConfigEncodedTimeout execution(@jakarta.annotation.Nullable Integer execution) {

    this.execution = execution;
    return this;
  }

  /**
   * Get execution
   * minimum: 0
   * @return execution
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXECUTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExecution() {
    return execution;
  }


  @JsonProperty(value = JSON_PROPERTY_EXECUTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecution(@jakarta.annotation.Nullable Integer execution) {
    this.execution = execution;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    McpLocalConfigEncodedTimeout mcpLocalConfigEncodedTimeout = (McpLocalConfigEncodedTimeout) o;
    return Objects.equals(this.startup, mcpLocalConfigEncodedTimeout.startup) &&
        Objects.equals(this.catalog, mcpLocalConfigEncodedTimeout.catalog) &&
        Objects.equals(this.execution, mcpLocalConfigEncodedTimeout.execution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startup, catalog, execution);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class McpLocalConfigEncodedTimeout {\n");
    sb.append("    startup: ").append(toIndentedString(startup)).append("\n");
    sb.append("    catalog: ").append(toIndentedString(catalog)).append("\n");
    sb.append("    execution: ").append(toIndentedString(execution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
