/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ModelFile
 */
@JsonPropertyOrder({
  ModelFile.JSON_PROPERTY_PATH,
  ModelFile.JSON_PROPERTY_ADDED,
  ModelFile.JSON_PROPERTY_REMOVED,
  ModelFile.JSON_PROPERTY_STATUS
})
@JsonTypeName("File")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelFile {
  public static final String JSON_PROPERTY_PATH = "path";
  @jakarta.annotation.Nonnull
  private String path;

  public static final String JSON_PROPERTY_ADDED = "added";
  @jakarta.annotation.Nonnull
  private Integer added;

  public static final String JSON_PROPERTY_REMOVED = "removed";
  @jakarta.annotation.Nonnull
  private Integer removed;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ADDED(String.valueOf("added")),
    
    DELETED(String.valueOf("deleted")),
    
    MODIFIED(String.valueOf("modified"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public ModelFile() {
  }

  public ModelFile path(@jakarta.annotation.Nonnull String path) {
    
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPath(@jakarta.annotation.Nonnull String path) {
    this.path = path;
  }

  public ModelFile added(@jakarta.annotation.Nonnull Integer added) {
    
    this.added = added;
    return this;
  }

  /**
   * Get added
   * minimum: 0
   * @return added
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ADDED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAdded() {
    return added;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdded(@jakarta.annotation.Nonnull Integer added) {
    this.added = added;
  }

  public ModelFile removed(@jakarta.annotation.Nonnull Integer removed) {
    
    this.removed = removed;
    return this;
  }

  /**
   * Get removed
   * minimum: 0
   * @return removed
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REMOVED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRemoved() {
    return removed;
  }


  @JsonProperty(value = JSON_PROPERTY_REMOVED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRemoved(@jakarta.annotation.Nonnull Integer removed) {
    this.removed = removed;
  }

  public ModelFile status(@jakarta.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelFile _file = (ModelFile) o;
    return Objects.equals(this.path, _file.path) &&
        Objects.equals(this.added, _file.added) &&
        Objects.equals(this.removed, _file.removed) &&
        Objects.equals(this.status, _file.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, added, removed, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelFile {\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    added: ").append(toIndentedString(added)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

