/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ModelV2InfoLimit
 */
@JsonPropertyOrder({
  ModelV2InfoLimit.JSON_PROPERTY_CONTEXT,
  ModelV2InfoLimit.JSON_PROPERTY_INPUT,
  ModelV2InfoLimit.JSON_PROPERTY_OUTPUT
})
@JsonTypeName("ModelV2Info_limit")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelV2InfoLimit {
  public static final String JSON_PROPERTY_CONTEXT = "context";
  @jakarta.annotation.Nonnull
  private Integer context;

  public static final String JSON_PROPERTY_INPUT = "input";
  @jakarta.annotation.Nullable
  private Integer input;

  public static final String JSON_PROPERTY_OUTPUT = "output";
  @jakarta.annotation.Nonnull
  private Integer output;

  public ModelV2InfoLimit() {
  }

  public ModelV2InfoLimit context(@jakarta.annotation.Nonnull Integer context) {
    
    this.context = context;
    return this;
  }

  /**
   * Get context
   * @return context
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getContext() {
    return context;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContext(@jakarta.annotation.Nonnull Integer context) {
    this.context = context;
  }

  public ModelV2InfoLimit input(@jakarta.annotation.Nullable Integer input) {
    
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInput() {
    return input;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInput(@jakarta.annotation.Nullable Integer input) {
    this.input = input;
  }

  public ModelV2InfoLimit output(@jakarta.annotation.Nonnull Integer output) {
    
    this.output = output;
    return this;
  }

  /**
   * Get output
   * @return output
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getOutput() {
    return output;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutput(@jakarta.annotation.Nonnull Integer output) {
    this.output = output;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelV2InfoLimit modelV2InfoLimit = (ModelV2InfoLimit) o;
    return Objects.equals(this.context, modelV2InfoLimit.context) &&
        Objects.equals(this.input, modelV2InfoLimit.input) &&
        Objects.equals(this.output, modelV2InfoLimit.output);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, input, output);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelV2InfoLimit {\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

