/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PermissionSavedInfoTime
 */
@JsonPropertyOrder({
  PermissionSavedInfoTime.JSON_PROPERTY_CREATED,
  PermissionSavedInfoTime.JSON_PROPERTY_UPDATED
})
@JsonTypeName("PermissionSaved_Info_time")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PermissionSavedInfoTime {
  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nonnull
  private BigDecimal created;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @jakarta.annotation.Nonnull
  private BigDecimal updated;

  public PermissionSavedInfoTime() {
  }

  public PermissionSavedInfoTime created(@jakarta.annotation.Nonnull BigDecimal created) {

    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@jakarta.annotation.Nonnull BigDecimal created) {
    this.created = created;
  }

  public PermissionSavedInfoTime updated(@jakarta.annotation.Nonnull BigDecimal updated) {

    this.updated = updated;
    return this;
  }

  /**
   * Get updated
   * @return updated
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getUpdated() {
    return updated;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdated(@jakarta.annotation.Nonnull BigDecimal updated) {
    this.updated = updated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionSavedInfoTime permissionSavedInfoTime = (PermissionSavedInfoTime) o;
    return Objects.equals(this.created, permissionSavedInfoTime.created) &&
        Objects.equals(this.updated, permissionSavedInfoTime.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, updated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionSavedInfoTime {\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
