/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PluginStateAnyOf1
 */
@JsonPropertyOrder({
  PluginStateAnyOf1.JSON_PROPERTY_STATUS,
  PluginStateAnyOf1.JSON_PROPERTY_ERROR,
  PluginStateAnyOf1.JSON_PROPERTY_REF
})
@JsonTypeName("Plugin_State_anyOf_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class PluginStateAnyOf1 {
  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    FAILED(String.valueOf("failed"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_ERROR = "error";
  @jakarta.annotation.Nullable
  private String error;

  public static final String JSON_PROPERTY_REF = "ref";
  @jakarta.annotation.Nullable
  private String ref;

  public PluginStateAnyOf1() {
  }

  public PluginStateAnyOf1 status(@jakarta.annotation.Nonnull StatusEnum status) {

    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public PluginStateAnyOf1 error(@jakarta.annotation.Nullable String error) {

    this.error = error;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return error
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setError(@jakarta.annotation.Nullable String error) {
    this.error = error;
  }

  public PluginStateAnyOf1 ref(@jakarta.annotation.Nullable String ref) {

    this.ref = ref;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return ref
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRef() {
    return ref;
  }


  @JsonProperty(value = JSON_PROPERTY_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRef(@jakarta.annotation.Nullable String ref) {
    this.ref = ref;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PluginStateAnyOf1 pluginStateAnyOf1 = (PluginStateAnyOf1) o;
    return Objects.equals(this.status, pluginStateAnyOf1.status) &&
        Objects.equals(this.error, pluginStateAnyOf1.error) &&
        Objects.equals(this.ref, pluginStateAnyOf1.ref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, error, ref);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PluginStateAnyOf1 {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
