/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProviderOauthCallbackRequest
 */
@JsonPropertyOrder({
  ProviderOauthCallbackRequest.JSON_PROPERTY_METHOD,
  ProviderOauthCallbackRequest.JSON_PROPERTY_CODE
})
@JsonTypeName("provider_oauth_callback_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ProviderOauthCallbackRequest {
  public static final String JSON_PROPERTY_METHOD = "method";
  @jakarta.annotation.Nonnull
  private BigDecimal method;

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private String code;

  public ProviderOauthCallbackRequest() {
  }

  public ProviderOauthCallbackRequest method(@jakarta.annotation.Nonnull BigDecimal method) {
    
    this.method = method;
    return this;
  }

  /**
   * Auth method index
   * @return method
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getMethod() {
    return method;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMethod(@jakarta.annotation.Nonnull BigDecimal method) {
    this.method = method;
  }

  public ProviderOauthCallbackRequest code(@jakarta.annotation.Nullable String code) {
    
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@jakarta.annotation.Nullable String code) {
    this.code = code;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProviderOauthCallbackRequest providerOauthCallbackRequest = (ProviderOauthCallbackRequest) o;
    return Objects.equals(this.method, providerOauthCallbackRequest.method) &&
        Objects.equals(this.code, providerOauthCallbackRequest.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(method, code);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProviderOauthCallbackRequest {\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

