/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProviderAuthMethodPromptsInnerAnyOfWhen
 */
@JsonPropertyOrder({
  ProviderAuthMethodPromptsInnerAnyOfWhen.JSON_PROPERTY_KEY,
  ProviderAuthMethodPromptsInnerAnyOfWhen.JSON_PROPERTY_OP,
  ProviderAuthMethodPromptsInnerAnyOfWhen.JSON_PROPERTY_VALUE
})
@JsonTypeName("ProviderAuthMethod_prompts_inner_anyOf_when")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ProviderAuthMethodPromptsInnerAnyOfWhen {
  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nonnull
  private String key;

  /**
   * Gets or Sets op
   */
  public enum OpEnum {
    EQ(String.valueOf("eq")),
    
    NEQ(String.valueOf("neq"));

    private String value;

    OpEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OpEnum fromValue(String value) {
      for (OpEnum b : OpEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OP = "op";
  @jakarta.annotation.Nonnull
  private OpEnum op;

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nonnull
  private String value;

  public ProviderAuthMethodPromptsInnerAnyOfWhen() {
  }

  public ProviderAuthMethodPromptsInnerAnyOfWhen key(@jakarta.annotation.Nonnull String key) {
    
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@jakarta.annotation.Nonnull String key) {
    this.key = key;
  }

  public ProviderAuthMethodPromptsInnerAnyOfWhen op(@jakarta.annotation.Nonnull OpEnum op) {
    
    this.op = op;
    return this;
  }

  /**
   * Get op
   * @return op
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OpEnum getOp() {
    return op;
  }


  @JsonProperty(value = JSON_PROPERTY_OP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOp(@jakarta.annotation.Nonnull OpEnum op) {
    this.op = op;
  }

  public ProviderAuthMethodPromptsInnerAnyOfWhen value(@jakarta.annotation.Nonnull String value) {
    
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@jakarta.annotation.Nonnull String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProviderAuthMethodPromptsInnerAnyOfWhen providerAuthMethodPromptsInnerAnyOfWhen = (ProviderAuthMethodPromptsInnerAnyOfWhen) o;
    return Objects.equals(this.key, providerAuthMethodPromptsInnerAnyOfWhen.key) &&
        Objects.equals(this.op, providerAuthMethodPromptsInnerAnyOfWhen.op) &&
        Objects.equals(this.value, providerAuthMethodPromptsInnerAnyOfWhen.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, op, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProviderAuthMethodPromptsInnerAnyOfWhen {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

