/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WebSocket connect token
 */
@JsonPropertyOrder({
  PtyConnectToken200Response.JSON_PROPERTY_TICKET,
  PtyConnectToken200Response.JSON_PROPERTY_EXPIRES_IN
})
@JsonTypeName("pty_connectToken_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class PtyConnectToken200Response {
  public static final String JSON_PROPERTY_TICKET = "ticket";
  @jakarta.annotation.Nonnull
  private String ticket;

  public static final String JSON_PROPERTY_EXPIRES_IN = "expires_in";
  @jakarta.annotation.Nonnull
  private Integer expiresIn;

  public PtyConnectToken200Response() {
  }

  public PtyConnectToken200Response ticket(@jakarta.annotation.Nonnull String ticket) {
    
    this.ticket = ticket;
    return this;
  }

  /**
   * Get ticket
   * @return ticket
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TICKET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTicket() {
    return ticket;
  }


  @JsonProperty(value = JSON_PROPERTY_TICKET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTicket(@jakarta.annotation.Nonnull String ticket) {
    this.ticket = ticket;
  }

  public PtyConnectToken200Response expiresIn(@jakarta.annotation.Nonnull Integer expiresIn) {
    
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * Get expiresIn
   * minimum: 0
   * @return expiresIn
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getExpiresIn() {
    return expiresIn;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_IN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresIn(@jakarta.annotation.Nonnull Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtyConnectToken200Response ptyConnectToken200Response = (PtyConnectToken200Response) o;
    return Objects.equals(this.ticket, ptyConnectToken200Response.ticket) &&
        Objects.equals(this.expiresIn, ptyConnectToken200Response.expiresIn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticket, expiresIn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtyConnectToken200Response {\n");
    sb.append("    ticket: ").append(toIndentedString(ticket)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

