/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PtyUpdateRequestSize
 */
@JsonPropertyOrder({
  PtyUpdateRequestSize.JSON_PROPERTY_ROWS,
  PtyUpdateRequestSize.JSON_PROPERTY_COLS
})
@JsonTypeName("pty_update_request_size")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class PtyUpdateRequestSize {
  public static final String JSON_PROPERTY_ROWS = "rows";
  @jakarta.annotation.Nonnull
  private Integer rows;

  public static final String JSON_PROPERTY_COLS = "cols";
  @jakarta.annotation.Nonnull
  private Integer cols;

  public PtyUpdateRequestSize() {
  }

  public PtyUpdateRequestSize rows(@jakarta.annotation.Nonnull Integer rows) {
    
    this.rows = rows;
    return this;
  }

  /**
   * Get rows
   * minimum: 0
   * @return rows
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROWS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRows() {
    return rows;
  }


  @JsonProperty(value = JSON_PROPERTY_ROWS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRows(@jakarta.annotation.Nonnull Integer rows) {
    this.rows = rows;
  }

  public PtyUpdateRequestSize cols(@jakarta.annotation.Nonnull Integer cols) {
    
    this.cols = cols;
    return this;
  }

  /**
   * Get cols
   * minimum: 0
   * @return cols
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COLS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCols() {
    return cols;
  }


  @JsonProperty(value = JSON_PROPERTY_COLS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCols(@jakarta.annotation.Nonnull Integer cols) {
    this.cols = cols;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtyUpdateRequestSize ptyUpdateRequestSize = (PtyUpdateRequestSize) o;
    return Objects.equals(this.rows, ptyUpdateRequestSize.rows) &&
        Objects.equals(this.cols, ptyUpdateRequestSize.cols);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rows, cols);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtyUpdateRequestSize {\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    cols: ").append(toIndentedString(cols)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

