/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RangeStart
 */
@JsonPropertyOrder({
  RangeStart.JSON_PROPERTY_LINE,
  RangeStart.JSON_PROPERTY_CHARACTER
})
@JsonTypeName("Range_start")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class RangeStart {
  public static final String JSON_PROPERTY_LINE = "line";
  @jakarta.annotation.Nonnull
  private Integer line;

  public static final String JSON_PROPERTY_CHARACTER = "character";
  @jakarta.annotation.Nonnull
  private Integer character;

  public RangeStart() {
  }

  public RangeStart line(@jakarta.annotation.Nonnull Integer line) {

    this.line = line;
    return this;
  }

  /**
   * Get line
   * minimum: 0
   * @return line
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LINE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getLine() {
    return line;
  }


  @JsonProperty(value = JSON_PROPERTY_LINE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLine(@jakarta.annotation.Nonnull Integer line) {
    this.line = line;
  }

  public RangeStart character(@jakarta.annotation.Nonnull Integer character) {

    this.character = character;
    return this;
  }

  /**
   * Get character
   * minimum: 0
   * @return character
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHARACTER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCharacter() {
    return character;
  }


  @JsonProperty(value = JSON_PROPERTY_CHARACTER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCharacter(@jakarta.annotation.Nonnull Integer character) {
    this.character = character;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RangeStart rangeStart = (RangeStart) o;
    return Objects.equals(this.line, rangeStart.line) &&
        Objects.equals(this.character, rangeStart.character);
  }

  @Override
  public int hashCode() {
    return Objects.hash(line, character);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RangeStart {\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    character: ").append(toIndentedString(character)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
