/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.FilePartSourceText;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResourceSource
 */
@JsonPropertyOrder({
  ResourceSource.JSON_PROPERTY_TEXT,
  ResourceSource.JSON_PROPERTY_TYPE,
  ResourceSource.JSON_PROPERTY_CLIENT_NAME,
  ResourceSource.JSON_PROPERTY_URI
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class ResourceSource {
  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nonnull
  private FilePartSourceText text;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    RESOURCE(String.valueOf("resource"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_CLIENT_NAME = "clientName";
  @jakarta.annotation.Nonnull
  private String clientName;

  public static final String JSON_PROPERTY_URI = "uri";
  @jakarta.annotation.Nonnull
  private String uri;

  public ResourceSource() {
  }

  public ResourceSource text(@jakarta.annotation.Nonnull FilePartSourceText text) {

    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FilePartSourceText getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@jakarta.annotation.Nonnull FilePartSourceText text) {
    this.text = text;
  }

  public ResourceSource type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public ResourceSource clientName(@jakarta.annotation.Nonnull String clientName) {

    this.clientName = clientName;
    return this;
  }

  /**
   * Get clientName
   * @return clientName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CLIENT_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientName() {
    return clientName;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientName(@jakarta.annotation.Nonnull String clientName) {
    this.clientName = clientName;
  }

  public ResourceSource uri(@jakarta.annotation.Nonnull String uri) {

    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   * @return uri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUri() {
    return uri;
  }


  @JsonProperty(value = JSON_PROPERTY_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUri(@jakarta.annotation.Nonnull String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceSource resourceSource = (ResourceSource) o;
    return Objects.equals(this.text, resourceSource.text) &&
        Objects.equals(this.type, resourceSource.type) &&
        Objects.equals(this.clientName, resourceSource.clientName) &&
        Objects.equals(this.uri, resourceSource.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, type, clientName, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceSource {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
