/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.InvalidRequestErrorEncoded;
import com.example.opencode.sdk.model.RpcErrorEncoded;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RpcCall400Response
 */
@JsonPropertyOrder({
  RpcCall400Response.JSON_PROPERTY_TAG,
  RpcCall400Response.JSON_PROPERTY_TYPE,
  RpcCall400Response.JSON_PROPERTY_MESSAGE,
  RpcCall400Response.JSON_PROPERTY_DATA,
  RpcCall400Response.JSON_PROPERTY_KIND,
  RpcCall400Response.JSON_PROPERTY_FIELD
})
@JsonTypeName("rpc_call_400_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class RpcCall400Response {
  /**
   * Gets or Sets tag
   */
  public enum TagEnum {
    INVALID_REQUEST_ERROR(String.valueOf("InvalidRequestError"));

    private String value;

    TagEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TagEnum fromValue(String value) {
      for (TagEnum b : TagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TAG = "_tag";
  @jakarta.annotation.Nonnull
  private TagEnum tag;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private String type;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nullable
  private Object data;

  public static final String JSON_PROPERTY_KIND = "kind";
  @jakarta.annotation.Nullable
  private String kind;

  public static final String JSON_PROPERTY_FIELD = "field";
  @jakarta.annotation.Nullable
  private String field;

  public RpcCall400Response() {
  }

  public RpcCall400Response tag(@jakarta.annotation.Nonnull TagEnum tag) {

    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TagEnum getTag() {
    return tag;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTag(@jakarta.annotation.Nonnull TagEnum tag) {
    this.tag = tag;
  }

  public RpcCall400Response type(@jakarta.annotation.Nonnull String type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull String type) {
    this.type = type;
  }

  public RpcCall400Response message(@jakarta.annotation.Nonnull String message) {

    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }

  public RpcCall400Response data(@jakarta.annotation.Nullable Object data) {

    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@jakarta.annotation.Nullable Object data) {
    this.data = data;
  }

  public RpcCall400Response kind(@jakarta.annotation.Nullable String kind) {

    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(@jakarta.annotation.Nullable String kind) {
    this.kind = kind;
  }

  public RpcCall400Response field(@jakarta.annotation.Nullable String field) {

    this.field = field;
    return this;
  }

  /**
   * Get field
   * @return field
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIELD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getField() {
    return field;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setField(@jakarta.annotation.Nullable String field) {
    this.field = field;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RpcCall400Response rpcCall400Response = (RpcCall400Response) o;
    return Objects.equals(this.tag, rpcCall400Response.tag) &&
        Objects.equals(this.type, rpcCall400Response.type) &&
        Objects.equals(this.message, rpcCall400Response.message) &&
        Objects.equals(this.data, rpcCall400Response.data) &&
        Objects.equals(this.kind, rpcCall400Response.kind) &&
        Objects.equals(this.field, rpcCall400Response.field);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, type, message, data, kind, field);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RpcCall400Response {\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
