/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.ModelRef;
import com.example.opencode.sdk.model.SessionMessageAgentSelectedTime;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SessionMessageModelSelected
 */
@JsonPropertyOrder({
  SessionMessageModelSelected.JSON_PROPERTY_ID,
  SessionMessageModelSelected.JSON_PROPERTY_METADATA,
  SessionMessageModelSelected.JSON_PROPERTY_TIME,
  SessionMessageModelSelected.JSON_PROPERTY_TYPE,
  SessionMessageModelSelected.JSON_PROPERTY_MODEL,
  SessionMessageModelSelected.JSON_PROPERTY_PREVIOUS
})
@JsonTypeName("Session.Message.ModelSelected")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SessionMessageModelSelected {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Object metadata;

  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nonnull
  private SessionMessageAgentSelectedTime time;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    MODEL_SWITCHED(String.valueOf("model-switched"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nonnull
  private ModelRef model;

  public static final String JSON_PROPERTY_PREVIOUS = "previous";
  @jakarta.annotation.Nullable
  private ModelRef previous;

  public SessionMessageModelSelected() {
  }

  public SessionMessageModelSelected id(@jakarta.annotation.Nullable String id) {

    this.id = id;
    return this;
  }

  /**
   * User message whose turn to diff. Defaults to the turn of the newest user message.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public SessionMessageModelSelected metadata(@jakarta.annotation.Nullable Object metadata) {

    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }

  public SessionMessageModelSelected time(@jakarta.annotation.Nonnull SessionMessageAgentSelectedTime time) {

    this.time = time;
    return this;
  }

  /**
   * Get time
   * @return time
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SessionMessageAgentSelectedTime getTime() {
    return time;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(@jakarta.annotation.Nonnull SessionMessageAgentSelectedTime time) {
    this.time = time;
  }

  public SessionMessageModelSelected type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public SessionMessageModelSelected model(@jakarta.annotation.Nonnull ModelRef model) {

    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ModelRef getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@jakarta.annotation.Nonnull ModelRef model) {
    this.model = model;
  }

  public SessionMessageModelSelected previous(@jakarta.annotation.Nullable ModelRef previous) {

    this.previous = previous;
    return this;
  }

  /**
   * Get previous
   * @return previous
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModelRef getPrevious() {
    return previous;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrevious(@jakarta.annotation.Nullable ModelRef previous) {
    this.previous = previous;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionMessageModelSelected sessionMessageModelSelected = (SessionMessageModelSelected) o;
    return Objects.equals(this.id, sessionMessageModelSelected.id) &&
        Objects.equals(this.metadata, sessionMessageModelSelected.metadata) &&
        Objects.equals(this.time, sessionMessageModelSelected.time) &&
        Objects.equals(this.type, sessionMessageModelSelected.type) &&
        Objects.equals(this.model, sessionMessageModelSelected.model) &&
        Objects.equals(this.previous, sessionMessageModelSelected.previous);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, metadata, time, type, model, previous);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionMessageModelSelected {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
