/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.PermissionRule;
import com.example.opencode.sdk.model.SessionCreateRequestModel;
import com.example.opencode.sdk.model.SessionRevert;
import com.example.opencode.sdk.model.SessionShare;
import com.example.opencode.sdk.model.SessionSummary;
import com.example.opencode.sdk.model.SessionTime;
import com.example.opencode.sdk.model.SessionTokens;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Session
 */
@JsonPropertyOrder({
  Session.JSON_PROPERTY_ID,
  Session.JSON_PROPERTY_SLUG,
  Session.JSON_PROPERTY_PROJECT_I_D,
  Session.JSON_PROPERTY_WORKSPACE_I_D,
  Session.JSON_PROPERTY_DIRECTORY,
  Session.JSON_PROPERTY_PATH,
  Session.JSON_PROPERTY_PARENT_I_D,
  Session.JSON_PROPERTY_SUMMARY,
  Session.JSON_PROPERTY_COST,
  Session.JSON_PROPERTY_TOKENS,
  Session.JSON_PROPERTY_SHARE,
  Session.JSON_PROPERTY_TITLE,
  Session.JSON_PROPERTY_AGENT,
  Session.JSON_PROPERTY_MODEL,
  Session.JSON_PROPERTY_VERSION,
  Session.JSON_PROPERTY_METADATA,
  Session.JSON_PROPERTY_TIME,
  Session.JSON_PROPERTY_PERMISSION,
  Session.JSON_PROPERTY_REVERT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Session {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @jakarta.annotation.Nonnull
  private String slug;

  public static final String JSON_PROPERTY_PROJECT_I_D = "projectID";
  @jakarta.annotation.Nonnull
  private String projectID;

  public static final String JSON_PROPERTY_WORKSPACE_I_D = "workspaceID";
  @jakarta.annotation.Nullable
  private String workspaceID;

  public static final String JSON_PROPERTY_DIRECTORY = "directory";
  @jakarta.annotation.Nonnull
  private String directory;

  public static final String JSON_PROPERTY_PATH = "path";
  @jakarta.annotation.Nullable
  private String path;

  public static final String JSON_PROPERTY_PARENT_I_D = "parentID";
  @jakarta.annotation.Nullable
  private String parentID;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @jakarta.annotation.Nullable
  private SessionSummary summary;

  public static final String JSON_PROPERTY_COST = "cost";
  @jakarta.annotation.Nullable
  private BigDecimal cost;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  @jakarta.annotation.Nullable
  private SessionTokens tokens;

  public static final String JSON_PROPERTY_SHARE = "share";
  @jakarta.annotation.Nullable
  private SessionShare share;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nonnull
  private String title;

  public static final String JSON_PROPERTY_AGENT = "agent";
  @jakarta.annotation.Nullable
  private String agent;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nullable
  private SessionCreateRequestModel model;

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nonnull
  private String version;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Object metadata;

  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nonnull
  private SessionTime time;

  public static final String JSON_PROPERTY_PERMISSION = "permission";
  @jakarta.annotation.Nullable
  private List<PermissionRule> permission = new ArrayList<>();

  public static final String JSON_PROPERTY_REVERT = "revert";
  @jakarta.annotation.Nullable
  private SessionRevert revert;

  public Session() {
  }

  public Session id(@jakarta.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public Session slug(@jakarta.annotation.Nonnull String slug) {

    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlug() {
    return slug;
  }


  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlug(@jakarta.annotation.Nonnull String slug) {
    this.slug = slug;
  }

  public Session projectID(@jakarta.annotation.Nonnull String projectID) {

    this.projectID = projectID;
    return this;
  }

  /**
   * Get projectID
   * @return projectID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectID() {
    return projectID;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectID(@jakarta.annotation.Nonnull String projectID) {
    this.projectID = projectID;
  }

  public Session workspaceID(@jakarta.annotation.Nullable String workspaceID) {

    this.workspaceID = workspaceID;
    return this;
  }

  /**
   * Get workspaceID
   * @return workspaceID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WORKSPACE_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWorkspaceID() {
    return workspaceID;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKSPACE_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkspaceID(@jakarta.annotation.Nullable String workspaceID) {
    this.workspaceID = workspaceID;
  }

  public Session directory(@jakarta.annotation.Nonnull String directory) {

    this.directory = directory;
    return this;
  }

  /**
   * Get directory
   * @return directory
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DIRECTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDirectory() {
    return directory;
  }


  @JsonProperty(value = JSON_PROPERTY_DIRECTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDirectory(@jakarta.annotation.Nonnull String directory) {
    this.directory = directory;
  }

  public Session path(@jakarta.annotation.Nullable String path) {

    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPath(@jakarta.annotation.Nullable String path) {
    this.path = path;
  }

  public Session parentID(@jakarta.annotation.Nullable String parentID) {

    this.parentID = parentID;
    return this;
  }

  /**
   * Get parentID
   * @return parentID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARENT_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentID() {
    return parentID;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentID(@jakarta.annotation.Nullable String parentID) {
    this.parentID = parentID;
  }

  public Session summary(@jakarta.annotation.Nullable SessionSummary summary) {

    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionSummary getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@jakarta.annotation.Nullable SessionSummary summary) {
    this.summary = summary;
  }

  public Session cost(@jakarta.annotation.Nullable BigDecimal cost) {

    this.cost = cost;
    return this;
  }

  /**
   * Get cost
   * @return cost
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCost() {
    return cost;
  }


  @JsonProperty(value = JSON_PROPERTY_COST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCost(@jakarta.annotation.Nullable BigDecimal cost) {
    this.cost = cost;
  }

  public Session tokens(@jakarta.annotation.Nullable SessionTokens tokens) {

    this.tokens = tokens;
    return this;
  }

  /**
   * Get tokens
   * @return tokens
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionTokens getTokens() {
    return tokens;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokens(@jakarta.annotation.Nullable SessionTokens tokens) {
    this.tokens = tokens;
  }

  public Session share(@jakarta.annotation.Nullable SessionShare share) {

    this.share = share;
    return this;
  }

  /**
   * Get share
   * @return share
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHARE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionShare getShare() {
    return share;
  }


  @JsonProperty(value = JSON_PROPERTY_SHARE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShare(@jakarta.annotation.Nullable SessionShare share) {
    this.share = share;
  }

  public Session title(@jakarta.annotation.Nonnull String title) {

    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TITLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTitle(@jakarta.annotation.Nonnull String title) {
    this.title = title;
  }

  public Session agent(@jakarta.annotation.Nullable String agent) {

    this.agent = agent;
    return this;
  }

  /**
   * Get agent
   * @return agent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgent(@jakarta.annotation.Nullable String agent) {
    this.agent = agent;
  }

  public Session model(@jakarta.annotation.Nullable SessionCreateRequestModel model) {

    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionCreateRequestModel getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@jakarta.annotation.Nullable SessionCreateRequestModel model) {
    this.model = model;
  }

  public Session version(@jakarta.annotation.Nonnull String version) {

    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@jakarta.annotation.Nonnull String version) {
    this.version = version;
  }

  public Session metadata(@jakarta.annotation.Nullable Object metadata) {

    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }

  public Session time(@jakarta.annotation.Nonnull SessionTime time) {

    this.time = time;
    return this;
  }

  /**
   * Get time
   * @return time
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SessionTime getTime() {
    return time;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(@jakarta.annotation.Nonnull SessionTime time) {
    this.time = time;
  }

  public Session permission(@jakarta.annotation.Nullable List<PermissionRule> permission) {

    this.permission = permission;
    return this;
  }

  public Session addPermissionItem(PermissionRule permissionItem) {
    if (this.permission == null) {
      this.permission = new ArrayList<>();
    }
    this.permission.add(permissionItem);
    return this;
  }

  /**
   * Get permission
   * @return permission
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERMISSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PermissionRule> getPermission() {
    return permission;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermission(@jakarta.annotation.Nullable List<PermissionRule> permission) {
    this.permission = permission;
  }

  public Session revert(@jakarta.annotation.Nullable SessionRevert revert) {

    this.revert = revert;
    return this;
  }

  /**
   * Get revert
   * @return revert
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REVERT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionRevert getRevert() {
    return revert;
  }


  @JsonProperty(value = JSON_PROPERTY_REVERT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevert(@jakarta.annotation.Nullable SessionRevert revert) {
    this.revert = revert;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Session session = (Session) o;
    return Objects.equals(this.id, session.id) &&
        Objects.equals(this.slug, session.slug) &&
        Objects.equals(this.projectID, session.projectID) &&
        Objects.equals(this.workspaceID, session.workspaceID) &&
        Objects.equals(this.directory, session.directory) &&
        Objects.equals(this.path, session.path) &&
        Objects.equals(this.parentID, session.parentID) &&
        Objects.equals(this.summary, session.summary) &&
        Objects.equals(this.cost, session.cost) &&
        Objects.equals(this.tokens, session.tokens) &&
        Objects.equals(this.share, session.share) &&
        Objects.equals(this.title, session.title) &&
        Objects.equals(this.agent, session.agent) &&
        Objects.equals(this.model, session.model) &&
        Objects.equals(this.version, session.version) &&
        Objects.equals(this.metadata, session.metadata) &&
        Objects.equals(this.time, session.time) &&
        Objects.equals(this.permission, session.permission) &&
        Objects.equals(this.revert, session.revert);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, slug, projectID, workspaceID, directory, path, parentID, summary, cost, tokens, share, title, agent, model, version, metadata, time, permission, revert);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Session {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    projectID: ").append(toIndentedString(projectID)).append("\n");
    sb.append("    workspaceID: ").append(toIndentedString(workspaceID)).append("\n");
    sb.append("    directory: ").append(toIndentedString(directory)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    parentID: ").append(toIndentedString(parentID)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    share: ").append(toIndentedString(share)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    revert: ").append(toIndentedString(revert)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
