/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.LocationPublicRef;
import com.example.opencode.sdk.model.ModelRef;
import com.example.opencode.sdk.model.PromptAgentAttachment;
import com.example.opencode.sdk.model.PromptFileAttachment;
import com.example.opencode.sdk.model.PromptSkillAttachment;
import com.example.opencode.sdk.model.SessionMessageAgentSelected;
import com.example.opencode.sdk.model.SessionMessageAgentSelectedTime;
import com.example.opencode.sdk.model.SessionMessageAssistant;
import com.example.opencode.sdk.model.SessionMessageAssistantContentInner;
import com.example.opencode.sdk.model.SessionMessageAssistantRetry;
import com.example.opencode.sdk.model.SessionMessageAssistantSnapshot;
import com.example.opencode.sdk.model.SessionMessageCompaction;
import com.example.opencode.sdk.model.SessionMessageIdle;
import com.example.opencode.sdk.model.SessionMessageLocationSwitched;
import com.example.opencode.sdk.model.SessionMessageLocationSwitchedPrevious;
import com.example.opencode.sdk.model.SessionMessageModelSelected;
import com.example.opencode.sdk.model.SessionMessageShell;
import com.example.opencode.sdk.model.SessionMessageShellExit;
import com.example.opencode.sdk.model.SessionMessageSkill;
import com.example.opencode.sdk.model.SessionMessageSynthetic;
import com.example.opencode.sdk.model.SessionMessageSystem;
import com.example.opencode.sdk.model.SessionMessageUser;
import com.example.opencode.sdk.model.SessionStructuredError;
import com.example.opencode.sdk.model.ShellOutput200ResponseData;
import com.example.opencode.sdk.model.TokenUsageInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SessionMessageInfo
 */
@JsonPropertyOrder({
  SessionMessageInfo.JSON_PROPERTY_ID,
  SessionMessageInfo.JSON_PROPERTY_METADATA,
  SessionMessageInfo.JSON_PROPERTY_TIME,
  SessionMessageInfo.JSON_PROPERTY_TYPE,
  SessionMessageInfo.JSON_PROPERTY_AGENT,
  SessionMessageInfo.JSON_PROPERTY_PREVIOUS,
  SessionMessageInfo.JSON_PROPERTY_MODEL,
  SessionMessageInfo.JSON_PROPERTY_PROJECT_I_D,
  SessionMessageInfo.JSON_PROPERTY_SUBPATH,
  SessionMessageInfo.JSON_PROPERTY_LOCATION,
  SessionMessageInfo.JSON_PROPERTY_TEXT,
  SessionMessageInfo.JSON_PROPERTY_FILES,
  SessionMessageInfo.JSON_PROPERTY_AGENTS,
  SessionMessageInfo.JSON_PROPERTY_SKILLS,
  SessionMessageInfo.JSON_PROPERTY_DESCRIPTION,
  SessionMessageInfo.JSON_PROPERTY_SKILL,
  SessionMessageInfo.JSON_PROPERTY_NAME,
  SessionMessageInfo.JSON_PROPERTY_SHELL_I_D,
  SessionMessageInfo.JSON_PROPERTY_COMMAND,
  SessionMessageInfo.JSON_PROPERTY_STATUS,
  SessionMessageInfo.JSON_PROPERTY_EXIT,
  SessionMessageInfo.JSON_PROPERTY_OUTPUT,
  SessionMessageInfo.JSON_PROPERTY_CONTENT,
  SessionMessageInfo.JSON_PROPERTY_SNAPSHOT,
  SessionMessageInfo.JSON_PROPERTY_FINISH,
  SessionMessageInfo.JSON_PROPERTY_RAW_FINISH,
  SessionMessageInfo.JSON_PROPERTY_PROVIDER_STATE,
  SessionMessageInfo.JSON_PROPERTY_COST,
  SessionMessageInfo.JSON_PROPERTY_TOKENS,
  SessionMessageInfo.JSON_PROPERTY_ERROR,
  SessionMessageInfo.JSON_PROPERTY_RETRY,
  SessionMessageInfo.JSON_PROPERTY_REASON,
  SessionMessageInfo.JSON_PROPERTY_SUMMARY,
  SessionMessageInfo.JSON_PROPERTY_RECENT,
  SessionMessageInfo.JSON_PROPERTY_PROVIDER_CONTEXT,
  SessionMessageInfo.JSON_PROPERTY_OUTCOME
})
@JsonTypeName("Session.Message.Info")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class SessionMessageInfo {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Object metadata;

  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nonnull
  private SessionMessageAgentSelectedTime time;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    AGENT_SWITCHED(String.valueOf("agent-switched")),

    MODEL_SWITCHED(String.valueOf("model-switched")),

    LOCATION_SWITCHED(String.valueOf("location-switched")),

    USER(String.valueOf("user")),

    SYNTHETIC(String.valueOf("synthetic")),

    SYSTEM(String.valueOf("system")),

    SKILL(String.valueOf("skill")),

    SHELL(String.valueOf("shell")),

    ASSISTANT(String.valueOf("assistant")),

    COMPACTION(String.valueOf("compaction")),

    IDLE(String.valueOf("idle"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_AGENT = "agent";
  @jakarta.annotation.Nonnull
  private String agent;

  public static final String JSON_PROPERTY_PREVIOUS = "previous";
  @jakarta.annotation.Nullable
  private SessionMessageLocationSwitchedPrevious previous;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nonnull
  private ModelRef model;

  public static final String JSON_PROPERTY_PROJECT_I_D = "projectID";
  @jakarta.annotation.Nullable
  private String projectID;

  public static final String JSON_PROPERTY_SUBPATH = "subpath";
  @jakarta.annotation.Nullable
  private String subpath;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @jakarta.annotation.Nonnull
  private LocationPublicRef location;

  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nonnull
  private String text;

  public static final String JSON_PROPERTY_FILES = "files";
  @jakarta.annotation.Nullable
  private List<PromptFileAttachment> files = new ArrayList<>();

  public static final String JSON_PROPERTY_AGENTS = "agents";
  @jakarta.annotation.Nullable
  private List<PromptAgentAttachment> agents = new ArrayList<>();

  public static final String JSON_PROPERTY_SKILLS = "skills";
  @jakarta.annotation.Nullable
  private List<PromptSkillAttachment> skills = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_SKILL = "skill";
  @jakarta.annotation.Nonnull
  private String skill;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SHELL_I_D = "shellID";
  @jakarta.annotation.Nonnull
  private String shellID;

  public static final String JSON_PROPERTY_COMMAND = "command";
  @jakarta.annotation.Nonnull
  private String command;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    FAILED(String.valueOf("failed"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_EXIT = "exit";
  @jakarta.annotation.Nullable
  private SessionMessageShellExit exit;

  public static final String JSON_PROPERTY_OUTPUT = "output";
  @jakarta.annotation.Nullable
  private ShellOutput200ResponseData output;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @jakarta.annotation.Nonnull
  private List<SessionMessageAssistantContentInner> content = new ArrayList<>();

  public static final String JSON_PROPERTY_SNAPSHOT = "snapshot";
  @jakarta.annotation.Nullable
  private SessionMessageAssistantSnapshot snapshot;

  /**
   * Gets or Sets finish
   */
  public enum FinishEnum {
    STOP(String.valueOf("stop")),

    LENGTH(String.valueOf("length")),

    TOOL_CALLS(String.valueOf("tool-calls")),

    CONTENT_FILTER(String.valueOf("content-filter")),

    ERROR(String.valueOf("error")),

    UNKNOWN(String.valueOf("unknown"));

    private String value;

    FinishEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FinishEnum fromValue(String value) {
      for (FinishEnum b : FinishEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FINISH = "finish";
  @jakarta.annotation.Nullable
  private FinishEnum finish;

  public static final String JSON_PROPERTY_RAW_FINISH = "rawFinish";
  @jakarta.annotation.Nullable
  private String rawFinish;

  public static final String JSON_PROPERTY_PROVIDER_STATE = "providerState";
  @jakarta.annotation.Nullable
  private Object providerState;

  public static final String JSON_PROPERTY_COST = "cost";
  @jakarta.annotation.Nullable
  private BigDecimal cost;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  @jakarta.annotation.Nullable
  private TokenUsageInfo tokens;

  public static final String JSON_PROPERTY_ERROR = "error";
  @jakarta.annotation.Nonnull
  private SessionStructuredError error;

  public static final String JSON_PROPERTY_RETRY = "retry";
  @jakarta.annotation.Nullable
  private SessionMessageAssistantRetry retry;

  /**
   * Gets or Sets reason
   */
  public enum ReasonEnum {
    AUTO(String.valueOf("auto")),

    MANUAL(String.valueOf("manual"));

    private String value;

    ReasonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReasonEnum fromValue(String value) {
      for (ReasonEnum b : ReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REASON = "reason";
  @jakarta.annotation.Nonnull
  private ReasonEnum reason;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @jakarta.annotation.Nonnull
  private String summary;

  public static final String JSON_PROPERTY_RECENT = "recent";
  @jakarta.annotation.Nonnull
  private String recent;

  public static final String JSON_PROPERTY_PROVIDER_CONTEXT = "providerContext";
  @jakarta.annotation.Nullable
  private java.lang.Object providerContext;

  /**
   * Gets or Sets outcome
   */
  public enum OutcomeEnum {
    SUCCEEDED(String.valueOf("succeeded")),

    FAILED(String.valueOf("failed")),

    INTERRUPTED(String.valueOf("interrupted"));

    private String value;

    OutcomeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OutcomeEnum fromValue(String value) {
      for (OutcomeEnum b : OutcomeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  @jakarta.annotation.Nonnull
  private OutcomeEnum outcome;

  public SessionMessageInfo() {
  }

  public SessionMessageInfo id(@jakarta.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * User message whose turn to diff. Defaults to the turn of the newest user message.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public SessionMessageInfo metadata(@jakarta.annotation.Nullable Object metadata) {

    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }

  public SessionMessageInfo time(@jakarta.annotation.Nonnull SessionMessageAgentSelectedTime time) {

    this.time = time;
    return this;
  }

  /**
   * Get time
   * @return time
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SessionMessageAgentSelectedTime getTime() {
    return time;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(@jakarta.annotation.Nonnull SessionMessageAgentSelectedTime time) {
    this.time = time;
  }

  public SessionMessageInfo type(@jakarta.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public SessionMessageInfo agent(@jakarta.annotation.Nonnull String agent) {

    this.agent = agent;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return agent
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgent(@jakarta.annotation.Nonnull String agent) {
    this.agent = agent;
  }

  public SessionMessageInfo previous(@jakarta.annotation.Nullable SessionMessageLocationSwitchedPrevious previous) {

    this.previous = previous;
    return this;
  }

  /**
   * Get previous
   * @return previous
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionMessageLocationSwitchedPrevious getPrevious() {
    return previous;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrevious(@jakarta.annotation.Nullable SessionMessageLocationSwitchedPrevious previous) {
    this.previous = previous;
  }

  public SessionMessageInfo model(@jakarta.annotation.Nonnull ModelRef model) {

    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ModelRef getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@jakarta.annotation.Nonnull ModelRef model) {
    this.model = model;
  }

  public SessionMessageInfo projectID(@jakarta.annotation.Nullable String projectID) {

    this.projectID = projectID;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return projectID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectID() {
    return projectID;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectID(@jakarta.annotation.Nullable String projectID) {
    this.projectID = projectID;
  }

  public SessionMessageInfo subpath(@jakarta.annotation.Nullable String subpath) {

    this.subpath = subpath;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return subpath
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBPATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubpath() {
    return subpath;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBPATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubpath(@jakarta.annotation.Nullable String subpath) {
    this.subpath = subpath;
  }

  public SessionMessageInfo location(@jakarta.annotation.Nonnull LocationPublicRef location) {

    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocationPublicRef getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(@jakarta.annotation.Nonnull LocationPublicRef location) {
    this.location = location;
  }

  public SessionMessageInfo text(@jakarta.annotation.Nonnull String text) {

    this.text = text;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return text
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@jakarta.annotation.Nonnull String text) {
    this.text = text;
  }

  public SessionMessageInfo files(@jakarta.annotation.Nullable List<PromptFileAttachment> files) {

    this.files = files;
    return this;
  }

  public SessionMessageInfo addFilesItem(PromptFileAttachment filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

  /**
   * Get files
   * @return files
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PromptFileAttachment> getFiles() {
    return files;
  }


  @JsonProperty(value = JSON_PROPERTY_FILES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiles(@jakarta.annotation.Nullable List<PromptFileAttachment> files) {
    this.files = files;
  }

  public SessionMessageInfo agents(@jakarta.annotation.Nullable List<PromptAgentAttachment> agents) {

    this.agents = agents;
    return this;
  }

  public SessionMessageInfo addAgentsItem(PromptAgentAttachment agentsItem) {
    if (this.agents == null) {
      this.agents = new ArrayList<>();
    }
    this.agents.add(agentsItem);
    return this;
  }

  /**
   * Get agents
   * @return agents
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PromptAgentAttachment> getAgents() {
    return agents;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgents(@jakarta.annotation.Nullable List<PromptAgentAttachment> agents) {
    this.agents = agents;
  }

  public SessionMessageInfo skills(@jakarta.annotation.Nullable List<PromptSkillAttachment> skills) {

    this.skills = skills;
    return this;
  }

  public SessionMessageInfo addSkillsItem(PromptSkillAttachment skillsItem) {
    if (this.skills == null) {
      this.skills = new ArrayList<>();
    }
    this.skills.add(skillsItem);
    return this;
  }

  /**
   * Get skills
   * @return skills
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SKILLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PromptSkillAttachment> getSkills() {
    return skills;
  }


  @JsonProperty(value = JSON_PROPERTY_SKILLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSkills(@jakarta.annotation.Nullable List<PromptSkillAttachment> skills) {
    this.skills = skills;
  }

  public SessionMessageInfo description(@jakarta.annotation.Nullable String description) {

    this.description = description;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public SessionMessageInfo skill(@jakarta.annotation.Nonnull String skill) {

    this.skill = skill;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return skill
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SKILL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSkill() {
    return skill;
  }


  @JsonProperty(value = JSON_PROPERTY_SKILL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSkill(@jakarta.annotation.Nonnull String skill) {
    this.skill = skill;
  }

  public SessionMessageInfo name(@jakarta.annotation.Nonnull String name) {

    this.name = name;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public SessionMessageInfo shellID(@jakarta.annotation.Nonnull String shellID) {

    this.shellID = shellID;
    return this;
  }

  /**
   * Get shellID
   * @return shellID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SHELL_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getShellID() {
    return shellID;
  }


  @JsonProperty(value = JSON_PROPERTY_SHELL_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShellID(@jakarta.annotation.Nonnull String shellID) {
    this.shellID = shellID;
  }

  public SessionMessageInfo command(@jakarta.annotation.Nonnull String command) {

    this.command = command;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return command
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCommand() {
    return command;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMAND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCommand(@jakarta.annotation.Nonnull String command) {
    this.command = command;
  }

  public SessionMessageInfo status(@jakarta.annotation.Nonnull StatusEnum status) {

    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public SessionMessageInfo exit(@jakarta.annotation.Nullable SessionMessageShellExit exit) {

    this.exit = exit;
    return this;
  }

  /**
   * Get exit
   * @return exit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionMessageShellExit getExit() {
    return exit;
  }


  @JsonProperty(value = JSON_PROPERTY_EXIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExit(@jakarta.annotation.Nullable SessionMessageShellExit exit) {
    this.exit = exit;
  }

  public SessionMessageInfo output(@jakarta.annotation.Nullable ShellOutput200ResponseData output) {

    this.output = output;
    return this;
  }

  /**
   * Get output
   * @return output
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShellOutput200ResponseData getOutput() {
    return output;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutput(@jakarta.annotation.Nullable ShellOutput200ResponseData output) {
    this.output = output;
  }

  public SessionMessageInfo content(@jakarta.annotation.Nonnull List<SessionMessageAssistantContentInner> content) {

    this.content = content;
    return this;
  }

  public SessionMessageInfo addContentItem(SessionMessageAssistantContentInner contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SessionMessageAssistantContentInner> getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@jakarta.annotation.Nonnull List<SessionMessageAssistantContentInner> content) {
    this.content = content;
  }

  public SessionMessageInfo snapshot(@jakarta.annotation.Nullable SessionMessageAssistantSnapshot snapshot) {

    this.snapshot = snapshot;
    return this;
  }

  /**
   * Get snapshot
   * @return snapshot
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionMessageAssistantSnapshot getSnapshot() {
    return snapshot;
  }


  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSnapshot(@jakarta.annotation.Nullable SessionMessageAssistantSnapshot snapshot) {
    this.snapshot = snapshot;
  }

  public SessionMessageInfo finish(@jakarta.annotation.Nullable FinishEnum finish) {

    this.finish = finish;
    return this;
  }

  /**
   * Get finish
   * @return finish
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINISH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FinishEnum getFinish() {
    return finish;
  }


  @JsonProperty(value = JSON_PROPERTY_FINISH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinish(@jakarta.annotation.Nullable FinishEnum finish) {
    this.finish = finish;
  }

  public SessionMessageInfo rawFinish(@jakarta.annotation.Nullable String rawFinish) {

    this.rawFinish = rawFinish;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return rawFinish
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RAW_FINISH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRawFinish() {
    return rawFinish;
  }


  @JsonProperty(value = JSON_PROPERTY_RAW_FINISH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRawFinish(@jakarta.annotation.Nullable String rawFinish) {
    this.rawFinish = rawFinish;
  }

  public SessionMessageInfo providerState(@jakarta.annotation.Nullable Object providerState) {

    this.providerState = providerState;
    return this;
  }

  /**
   * Get providerState
   * @return providerState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getProviderState() {
    return providerState;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderState(@jakarta.annotation.Nullable Object providerState) {
    this.providerState = providerState;
  }

  public SessionMessageInfo cost(@jakarta.annotation.Nullable BigDecimal cost) {

    this.cost = cost;
    return this;
  }

  /**
   * Get cost
   * @return cost
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCost() {
    return cost;
  }


  @JsonProperty(value = JSON_PROPERTY_COST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCost(@jakarta.annotation.Nullable BigDecimal cost) {
    this.cost = cost;
  }

  public SessionMessageInfo tokens(@jakarta.annotation.Nullable TokenUsageInfo tokens) {

    this.tokens = tokens;
    return this;
  }

  /**
   * Get tokens
   * @return tokens
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TokenUsageInfo getTokens() {
    return tokens;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokens(@jakarta.annotation.Nullable TokenUsageInfo tokens) {
    this.tokens = tokens;
  }

  public SessionMessageInfo error(@jakarta.annotation.Nonnull SessionStructuredError error) {

    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SessionStructuredError getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setError(@jakarta.annotation.Nonnull SessionStructuredError error) {
    this.error = error;
  }

  public SessionMessageInfo retry(@jakarta.annotation.Nullable SessionMessageAssistantRetry retry) {

    this.retry = retry;
    return this;
  }

  /**
   * Get retry
   * @return retry
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionMessageAssistantRetry getRetry() {
    return retry;
  }


  @JsonProperty(value = JSON_PROPERTY_RETRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetry(@jakarta.annotation.Nullable SessionMessageAssistantRetry retry) {
    this.retry = retry;
  }

  public SessionMessageInfo reason(@jakarta.annotation.Nonnull ReasonEnum reason) {

    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REASON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ReasonEnum getReason() {
    return reason;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReason(@jakarta.annotation.Nonnull ReasonEnum reason) {
    this.reason = reason;
  }

  public SessionMessageInfo summary(@jakarta.annotation.Nonnull String summary) {

    this.summary = summary;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return summary
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummary(@jakarta.annotation.Nonnull String summary) {
    this.summary = summary;
  }

  public SessionMessageInfo recent(@jakarta.annotation.Nonnull String recent) {

    this.recent = recent;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return recent
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRecent() {
    return recent;
  }


  @JsonProperty(value = JSON_PROPERTY_RECENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecent(@jakarta.annotation.Nonnull String recent) {
    this.recent = recent;
  }

  public SessionMessageInfo providerContext(@jakarta.annotation.Nullable java.lang.Object providerContext) {

    this.providerContext = providerContext;
    return this;
  }

  /**
   * Get providerContext
   * @return providerContext
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.lang.Object getProviderContext() {
    return providerContext;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderContext(@jakarta.annotation.Nullable java.lang.Object providerContext) {
    this.providerContext = providerContext;
  }

  public SessionMessageInfo outcome(@jakarta.annotation.Nonnull OutcomeEnum outcome) {

    this.outcome = outcome;
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTCOME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OutcomeEnum getOutcome() {
    return outcome;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTCOME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutcome(@jakarta.annotation.Nonnull OutcomeEnum outcome) {
    this.outcome = outcome;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionMessageInfo sessionMessageInfo = (SessionMessageInfo) o;
    return Objects.equals(this.id, sessionMessageInfo.id) &&
        Objects.equals(this.metadata, sessionMessageInfo.metadata) &&
        Objects.equals(this.time, sessionMessageInfo.time) &&
        Objects.equals(this.type, sessionMessageInfo.type) &&
        Objects.equals(this.agent, sessionMessageInfo.agent) &&
        Objects.equals(this.previous, sessionMessageInfo.previous) &&
        Objects.equals(this.model, sessionMessageInfo.model) &&
        Objects.equals(this.projectID, sessionMessageInfo.projectID) &&
        Objects.equals(this.subpath, sessionMessageInfo.subpath) &&
        Objects.equals(this.location, sessionMessageInfo.location) &&
        Objects.equals(this.text, sessionMessageInfo.text) &&
        Objects.equals(this.files, sessionMessageInfo.files) &&
        Objects.equals(this.agents, sessionMessageInfo.agents) &&
        Objects.equals(this.skills, sessionMessageInfo.skills) &&
        Objects.equals(this.description, sessionMessageInfo.description) &&
        Objects.equals(this.skill, sessionMessageInfo.skill) &&
        Objects.equals(this.name, sessionMessageInfo.name) &&
        Objects.equals(this.shellID, sessionMessageInfo.shellID) &&
        Objects.equals(this.command, sessionMessageInfo.command) &&
        Objects.equals(this.status, sessionMessageInfo.status) &&
        Objects.equals(this.exit, sessionMessageInfo.exit) &&
        Objects.equals(this.output, sessionMessageInfo.output) &&
        Objects.equals(this.content, sessionMessageInfo.content) &&
        Objects.equals(this.snapshot, sessionMessageInfo.snapshot) &&
        Objects.equals(this.finish, sessionMessageInfo.finish) &&
        Objects.equals(this.rawFinish, sessionMessageInfo.rawFinish) &&
        Objects.equals(this.providerState, sessionMessageInfo.providerState) &&
        Objects.equals(this.cost, sessionMessageInfo.cost) &&
        Objects.equals(this.tokens, sessionMessageInfo.tokens) &&
        Objects.equals(this.error, sessionMessageInfo.error) &&
        Objects.equals(this.retry, sessionMessageInfo.retry) &&
        Objects.equals(this.reason, sessionMessageInfo.reason) &&
        Objects.equals(this.summary, sessionMessageInfo.summary) &&
        Objects.equals(this.recent, sessionMessageInfo.recent) &&
        Objects.equals(this.providerContext, sessionMessageInfo.providerContext) &&
        Objects.equals(this.outcome, sessionMessageInfo.outcome);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, metadata, time, type, agent, previous, model, projectID, subpath, location, text, files, agents, skills, description, skill, name, shellID, command, status, exit, output, content, snapshot, finish, rawFinish, providerState, cost, tokens, error, retry, reason, summary, recent, providerContext, outcome);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionMessageInfo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    projectID: ").append(toIndentedString(projectID)).append("\n");
    sb.append("    subpath: ").append(toIndentedString(subpath)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    agents: ").append(toIndentedString(agents)).append("\n");
    sb.append("    skills: ").append(toIndentedString(skills)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    skill: ").append(toIndentedString(skill)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    shellID: ").append(toIndentedString(shellID)).append("\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    exit: ").append(toIndentedString(exit)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    snapshot: ").append(toIndentedString(snapshot)).append("\n");
    sb.append("    finish: ").append(toIndentedString(finish)).append("\n");
    sb.append("    rawFinish: ").append(toIndentedString(rawFinish)).append("\n");
    sb.append("    providerState: ").append(toIndentedString(providerState)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    retry: ").append(toIndentedString(retry)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    recent: ").append(toIndentedString(recent)).append("\n");
    sb.append("    providerContext: ").append(toIndentedString(providerContext)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
