/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * V2IntegrationConnectOauthRequest
 */
@JsonPropertyOrder({
  V2IntegrationConnectOauthRequest.JSON_PROPERTY_METHOD_I_D,
  V2IntegrationConnectOauthRequest.JSON_PROPERTY_INPUTS,
  V2IntegrationConnectOauthRequest.JSON_PROPERTY_LABEL
})
@JsonTypeName("v2_integration_connect_oauth_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class V2IntegrationConnectOauthRequest {
  public static final String JSON_PROPERTY_METHOD_I_D = "methodID";
  @jakarta.annotation.Nonnull
  private String methodID;

  public static final String JSON_PROPERTY_INPUTS = "inputs";
  @jakarta.annotation.Nonnull
  private Map<String, String> inputs = new HashMap<>();

  public static final String JSON_PROPERTY_LABEL = "label";
  @jakarta.annotation.Nullable
  private String label;

  public V2IntegrationConnectOauthRequest() {
  }

  public V2IntegrationConnectOauthRequest methodID(@jakarta.annotation.Nonnull String methodID) {

    this.methodID = methodID;
    return this;
  }

  /**
   * Get methodID
   * @return methodID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_METHOD_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMethodID() {
    return methodID;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMethodID(@jakarta.annotation.Nonnull String methodID) {
    this.methodID = methodID;
  }

  public V2IntegrationConnectOauthRequest inputs(@jakarta.annotation.Nonnull Map<String, String> inputs) {

    this.inputs = inputs;
    return this;
  }

  public V2IntegrationConnectOauthRequest putInputsItem(String key, String inputsItem) {
    this.inputs.put(key, inputsItem);
    return this;
  }

  /**
   * Get inputs
   * @return inputs
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, String> getInputs() {
    return inputs;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInputs(@jakarta.annotation.Nonnull Map<String, String> inputs) {
    this.inputs = inputs;
  }

  public V2IntegrationConnectOauthRequest label(@jakarta.annotation.Nullable String label) {

    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLabel() {
    return label;
  }


  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(@jakarta.annotation.Nullable String label) {
    this.label = label;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2IntegrationConnectOauthRequest v2IntegrationConnectOauthRequest = (V2IntegrationConnectOauthRequest) o;
    return Objects.equals(this.methodID, v2IntegrationConnectOauthRequest.methodID) &&
        Objects.equals(this.inputs, v2IntegrationConnectOauthRequest.inputs) &&
        Objects.equals(this.label, v2IntegrationConnectOauthRequest.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(methodID, inputs, label);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2IntegrationConnectOauthRequest {\n");
    sb.append("    methodID: ").append(toIndentedString(methodID)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
