/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.opencode.sdk.model.PermissionV2Source;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * V2SessionPermissionCreateRequest
 */
@JsonPropertyOrder({
  V2SessionPermissionCreateRequest.JSON_PROPERTY_ID,
  V2SessionPermissionCreateRequest.JSON_PROPERTY_ACTION,
  V2SessionPermissionCreateRequest.JSON_PROPERTY_RESOURCES,
  V2SessionPermissionCreateRequest.JSON_PROPERTY_SAVE,
  V2SessionPermissionCreateRequest.JSON_PROPERTY_METADATA,
  V2SessionPermissionCreateRequest.JSON_PROPERTY_SOURCE,
  V2SessionPermissionCreateRequest.JSON_PROPERTY_AGENT
})
@JsonTypeName("v2_session_permission_create_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class V2SessionPermissionCreateRequest {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nonnull
  private String action;

  public static final String JSON_PROPERTY_RESOURCES = "resources";
  @jakarta.annotation.Nonnull
  private List<String> resources = new ArrayList<>();

  public static final String JSON_PROPERTY_SAVE = "save";
  @jakarta.annotation.Nullable
  private List<String> save = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Object metadata;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nullable
  private PermissionV2Source source;

  public static final String JSON_PROPERTY_AGENT = "agent";
  @jakarta.annotation.Nullable
  private String agent;

  public V2SessionPermissionCreateRequest() {
  }

  public V2SessionPermissionCreateRequest id(@jakarta.annotation.Nullable String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public V2SessionPermissionCreateRequest action(@jakarta.annotation.Nonnull String action) {

    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(@jakarta.annotation.Nonnull String action) {
    this.action = action;
  }

  public V2SessionPermissionCreateRequest resources(@jakarta.annotation.Nonnull List<String> resources) {

    this.resources = resources;
    return this;
  }

  public V2SessionPermissionCreateRequest addResourcesItem(String resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

  /**
   * Get resources
   * @return resources
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESOURCES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getResources() {
    return resources;
  }


  @JsonProperty(value = JSON_PROPERTY_RESOURCES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResources(@jakarta.annotation.Nonnull List<String> resources) {
    this.resources = resources;
  }

  public V2SessionPermissionCreateRequest save(@jakarta.annotation.Nullable List<String> save) {

    this.save = save;
    return this;
  }

  public V2SessionPermissionCreateRequest addSaveItem(String saveItem) {
    if (this.save == null) {
      this.save = new ArrayList<>();
    }
    this.save.add(saveItem);
    return this;
  }

  /**
   * Get save
   * @return save
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SAVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSave() {
    return save;
  }


  @JsonProperty(value = JSON_PROPERTY_SAVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSave(@jakarta.annotation.Nullable List<String> save) {
    this.save = save;
  }

  public V2SessionPermissionCreateRequest metadata(@jakarta.annotation.Nullable Object metadata) {

    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }

  public V2SessionPermissionCreateRequest source(@jakarta.annotation.Nullable PermissionV2Source source) {

    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PermissionV2Source getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(@jakarta.annotation.Nullable PermissionV2Source source) {
    this.source = source;
  }

  public V2SessionPermissionCreateRequest agent(@jakarta.annotation.Nullable String agent) {

    this.agent = agent;
    return this;
  }

  /**
   * Get agent
   * @return agent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgent(@jakarta.annotation.Nullable String agent) {
    this.agent = agent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2SessionPermissionCreateRequest v2SessionPermissionCreateRequest = (V2SessionPermissionCreateRequest) o;
    return Objects.equals(this.id, v2SessionPermissionCreateRequest.id) &&
        Objects.equals(this.action, v2SessionPermissionCreateRequest.action) &&
        Objects.equals(this.resources, v2SessionPermissionCreateRequest.resources) &&
        Objects.equals(this.save, v2SessionPermissionCreateRequest.save) &&
        Objects.equals(this.metadata, v2SessionPermissionCreateRequest.metadata) &&
        Objects.equals(this.source, v2SessionPermissionCreateRequest.source) &&
        Objects.equals(this.agent, v2SessionPermissionCreateRequest.agent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, action, resources, save, metadata, source, agent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2SessionPermissionCreateRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    save: ").append(toIndentedString(save)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
