/*
 * opencode HttpApi
 * Experimental HttpApi surface for selected instance routes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WebsearchQueryRequest
 */
@JsonPropertyOrder({
  WebsearchQueryRequest.JSON_PROPERTY_QUERY,
  WebsearchQueryRequest.JSON_PROPERTY_PROVIDER_I_D
})
@JsonTypeName("websearch_query_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class WebsearchQueryRequest {
  public static final String JSON_PROPERTY_QUERY = "query";
  @jakarta.annotation.Nullable
  private String query;

  public static final String JSON_PROPERTY_PROVIDER_I_D = "providerID";
  @jakarta.annotation.Nullable
  private String providerID;

  public WebsearchQueryRequest() {
  }

  public WebsearchQueryRequest query(@jakarta.annotation.Nullable String query) {

    this.query = query;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return query
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQuery() {
    return query;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuery(@jakarta.annotation.Nullable String query) {
    this.query = query;
  }

  public WebsearchQueryRequest providerID(@jakarta.annotation.Nullable String providerID) {

    this.providerID = providerID;
    return this;
  }

  /**
   * Maximum number of sessions to return. Defaults to the newest 50 sessions.
   * @return providerID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProviderID() {
    return providerID;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderID(@jakarta.annotation.Nullable String providerID) {
    this.providerID = providerID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebsearchQueryRequest websearchQueryRequest = (WebsearchQueryRequest) o;
    return Objects.equals(this.query, websearchQueryRequest.query) &&
        Objects.equals(this.providerID, websearchQueryRequest.providerID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, providerID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebsearchQueryRequest {\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    providerID: ").append(toIndentedString(providerID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}
