/*
 * opencode
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.opencode.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Worktree
 */
@JsonPropertyOrder({
  Worktree.JSON_PROPERTY_NAME,
  Worktree.JSON_PROPERTY_BRANCH,
  Worktree.JSON_PROPERTY_DIRECTORY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class Worktree {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_BRANCH = "branch";
  @jakarta.annotation.Nullable
  private String branch;

  public static final String JSON_PROPERTY_DIRECTORY = "directory";
  @jakarta.annotation.Nonnull
  private String directory;

  public Worktree() {
  }

  public Worktree name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public Worktree branch(@jakarta.annotation.Nullable String branch) {
    
    this.branch = branch;
    return this;
  }

  /**
   * Get branch
   * @return branch
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRANCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBranch() {
    return branch;
  }


  @JsonProperty(value = JSON_PROPERTY_BRANCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBranch(@jakarta.annotation.Nullable String branch) {
    this.branch = branch;
  }

  public Worktree directory(@jakarta.annotation.Nonnull String directory) {
    
    this.directory = directory;
    return this;
  }

  /**
   * Get directory
   * @return directory
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DIRECTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDirectory() {
    return directory;
  }


  @JsonProperty(value = JSON_PROPERTY_DIRECTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDirectory(@jakarta.annotation.Nonnull String directory) {
    this.directory = directory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Worktree worktree = (Worktree) o;
    return Objects.equals(this.name, worktree.name) &&
        Objects.equals(this.branch, worktree.branch) &&
        Objects.equals(this.directory, worktree.directory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, branch, directory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Worktree {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    directory: ").append(toIndentedString(directory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

