package com.enterprise.testagent.domain.opencodeprocess;

/**
 * 后端 Java 进程心跳上报的 Linux 服务器、Java 进程和 JVM 资源指标；空字段表示运行环境暂不可采集。
 *
 * <p>兼容字段：
 * <ul>
 *     <li>{@code cpuUsagePercent}：服务器 CPU 使用率。</li>
 *     <li>{@code memoryMaxBytes}：旧字段，等同 {@code memoryTotalBytes}。</li>
 *     <li>{@code jvmGcPauseMillis}：旧字段，等同 {@code jvmGcCollectionTimeDeltaMillis}。</li>
 * </ul>
 */
public record BackendRuntimeMetrics(
        Double cpuUsagePercent,
        Integer cpuCoreCount,
        Double loadAverage1m,
        Double loadAverage5m,
        Double loadAverage15m,
        Long memoryMaxBytes,
        Long memoryTotalBytes,
        Long memoryAvailableBytes,
        Long memoryFreeBytes,
        Long memoryUsedBytes,
        Double memoryUsagePercent,
        Long memoryBuffersBytes,
        Long memoryCachedBytes,
        Long swapTotalBytes,
        Long swapFreeBytes,
        Long swapUsedBytes,
        Double swapUsagePercent,
        Long diskMaxBytes,
        Long diskAvailableBytes,
        Long diskUsedBytes,
        Double diskUsagePercent,
        Double jvmProcessCpuUsagePercent,
        Double jvmProcessCpuCoreUsage,
        Long jvmProcessCpuTimeNanos,
        Long jvmProcessResidentMemoryBytes,
        Long jvmProcessPeakResidentMemoryBytes,
        Long jvmProcessVirtualMemoryBytes,
        Long jvmProcessSwapBytes,
        Long jvmOpenFileDescriptorCount,
        Long jvmMaxFileDescriptorCount,
        Long jvmMemoryUsedBytes,
        Long jvmMemoryCommittedBytes,
        Long jvmMemoryMaxBytes,
        Long jvmHeapUsedBytes,
        Long jvmHeapCommittedBytes,
        Long jvmHeapMaxBytes,
        Long jvmNonHeapUsedBytes,
        Long jvmNonHeapCommittedBytes,
        Long jvmNonHeapMaxBytes,
        Long jvmDirectBufferCount,
        Long jvmDirectBufferUsedBytes,
        Long jvmDirectBufferCapacityBytes,
        Long jvmMappedBufferCount,
        Long jvmMappedBufferUsedBytes,
        Long jvmMappedBufferCapacityBytes,
        Long jvmGcPauseMillis,
        Long jvmGcCollectionTimeDeltaMillis,
        Long jvmGcCollectionCountDelta,
        Double jvmGcTimePercent,
        Integer jvmThreadsLive,
        Integer jvmThreadsDaemon,
        Integer jvmThreadsPeak,
        Long jvmThreadsTotalStarted) {

    /**
     * 兼容旧测试和旧构造点；新增字段按不可采集处理。
     */
    public BackendRuntimeMetrics(
            Double cpuUsagePercent,
            Long memoryMaxBytes,
            Long memoryUsedBytes,
            Double memoryUsagePercent,
            Long diskMaxBytes,
            Long diskUsedBytes,
            Double diskUsagePercent,
            Long jvmMemoryUsedBytes,
            Long jvmMemoryCommittedBytes,
            Long jvmMemoryMaxBytes,
            Long jvmGcPauseMillis,
            Integer jvmThreadsLive) {
        this(
                cpuUsagePercent,
                null,
                null,
                null,
                null,
                memoryMaxBytes,
                memoryMaxBytes,
                null,
                null,
                memoryUsedBytes,
                memoryUsagePercent,
                null,
                null,
                null,
                null,
                null,
                null,
                diskMaxBytes,
                null,
                diskUsedBytes,
                diskUsagePercent,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                jvmMemoryUsedBytes,
                jvmMemoryCommittedBytes,
                jvmMemoryMaxBytes,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                jvmGcPauseMillis,
                jvmGcPauseMillis,
                null,
                null,
                jvmThreadsLive,
                null,
                null,
                null);
    }
}
