package com.enterprise.testagent.opencode.runtime.process;

import java.time.Instant;
import java.util.Objects;

/**
 * 运行管理接口返回的后端 Java 进程指标采样点。
 */
public record RuntimeManagementBackendMetricSample(
        Instant sampledAt,
        Double cpuUsagePercent,
        Integer cpuCoreCount,
        Double loadAverage1m,
        Double loadAverage5m,
        Double loadAverage15m,
        Long memoryMaxBytes,
        Long memoryTotalBytes,
        Long memoryAvailableBytes,
        Long memoryFreeBytes,
        Long memoryUsedBytes,
        Double memoryUsagePercent,
        Long memoryBuffersBytes,
        Long memoryCachedBytes,
        Long swapTotalBytes,
        Long swapFreeBytes,
        Long swapUsedBytes,
        Double swapUsagePercent,
        Long diskMaxBytes,
        Long diskAvailableBytes,
        Long diskUsedBytes,
        Double diskUsagePercent,
        Double jvmProcessCpuUsagePercent,
        Double jvmProcessCpuCoreUsage,
        Long jvmProcessCpuTimeNanos,
        Long jvmProcessResidentMemoryBytes,
        Long jvmProcessPeakResidentMemoryBytes,
        Long jvmProcessVirtualMemoryBytes,
        Long jvmProcessSwapBytes,
        Long jvmOpenFileDescriptorCount,
        Long jvmMaxFileDescriptorCount,
        Long jvmMemoryUsedBytes,
        Long jvmMemoryCommittedBytes,
        Long jvmMemoryMaxBytes,
        Long jvmHeapUsedBytes,
        Long jvmHeapCommittedBytes,
        Long jvmHeapMaxBytes,
        Long jvmNonHeapUsedBytes,
        Long jvmNonHeapCommittedBytes,
        Long jvmNonHeapMaxBytes,
        Long jvmDirectBufferCount,
        Long jvmDirectBufferUsedBytes,
        Long jvmDirectBufferCapacityBytes,
        Long jvmMappedBufferCount,
        Long jvmMappedBufferUsedBytes,
        Long jvmMappedBufferCapacityBytes,
        Long jvmGcPauseMillis,
        Long jvmGcCollectionTimeDeltaMillis,
        Long jvmGcCollectionCountDelta,
        Double jvmGcTimePercent,
        Integer jvmThreadsLive,
        Integer jvmThreadsDaemon,
        Integer jvmThreadsPeak,
        Long jvmThreadsTotalStarted) {

    public RuntimeManagementBackendMetricSample {
        sampledAt = Objects.requireNonNull(sampledAt, "sampledAt must not be null");
    }

    /**
     * 兼容旧测试构造器；新增字段按不可采集处理。
     */
    public RuntimeManagementBackendMetricSample(
            Instant sampledAt,
            Double cpuUsagePercent,
            Long memoryMaxBytes,
            Long memoryUsedBytes,
            Double memoryUsagePercent,
            Long diskMaxBytes,
            Long diskUsedBytes,
            Double diskUsagePercent,
            Long jvmMemoryUsedBytes,
            Long jvmMemoryCommittedBytes,
            Long jvmMemoryMaxBytes,
            Long jvmGcPauseMillis,
            Integer jvmThreadsLive) {
        this(
                sampledAt,
                cpuUsagePercent,
                null,
                null,
                null,
                null,
                memoryMaxBytes,
                memoryMaxBytes,
                null,
                null,
                memoryUsedBytes,
                memoryUsagePercent,
                null,
                null,
                null,
                null,
                null,
                null,
                diskMaxBytes,
                null,
                diskUsedBytes,
                diskUsagePercent,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                jvmMemoryUsedBytes,
                jvmMemoryCommittedBytes,
                jvmMemoryMaxBytes,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                jvmGcPauseMillis,
                jvmGcPauseMillis,
                null,
                null,
                jvmThreadsLive,
                null,
                null,
                null);
    }
}
