package com.enterprise.testagent.localclient.protocol;

/** v1 反向隧道支持的帧类型。 */
public enum LocalClientFrameType {
    REGISTER,
    REGISTERED,
    HEARTBEAT,
    HEARTBEAT_ACK,
    LIFECYCLE_COMMAND,
    LIFECYCLE_RESULT,
    HTTP_REQUEST,
    HTTP_RESPONSE,
    STREAM_OPEN,
    STREAM_CHUNK,
    STREAM_END,
    FILE_REQUEST,
    FILE_RESPONSE,
    WORKSPACE_REGISTER,
    WORKSPACE_REGISTERED,
    BINARY_CHUNK,
    MODEL_GRANT,
    VERSION_CHECK,
    VERSION_POLICY,
    UPDATE_COMMAND,
    UPDATE_PREPARED,
    UPDATE_APPLY,
    UPDATE_CANCEL,
    UPDATE_STATUS,
    UPDATE_STATUS_ACK,
    CANCEL,
    ERROR
}
